import test from 'node:test';
import assert from 'node:assert/strict';
import {Game,freshProgress,readProgress,saveProgress} from '../game.mjs';
import {WEAPONS,ENEMIES,LANDMARKS,SPAWNS,SAVE_KEY,walkable,inStrike} from '../world-data.mjs';
const tick=(g,n=60)=>{for(let i=0;i<n;i++)g.update(1/60);};
function duel(weapon='shear'){const g=new Game();g.player.x=0;g.player.z=0;g.player.yaw=0;g.player.weapon=weapon;for(const e of g.enemies)e.alive=false;const e=g.enemies[0];Object.assign(e,{alive:true,x:0,z:3,hp:1000,cooldown:100});return [g,e];}
test('weapon contact happens after windup, once per strike, followed by recovery',()=>{for(const id of Object.keys(WEAPONS)){const [g,e]=duel(id);assert.equal(g.attack(),true);assert.equal(g.attack(),false);g.update(.05);assert.equal(e.hp,1000);tick(g,25);const hp=e.hp;assert.ok(hp<1000);tick(g,45);assert.equal(e.hp,hp);assert.equal(g.player.attack,null);}});
test('directional attacks exclude enemies behind and lance excludes wide flank',()=>{assert.equal(inStrike({x:0,z:0,yaw:0},{x:0,z:-2},10,3),false);const [g,e]=duel('pike');g.player.move=1;e.x=3;g.attack();tick(g);assert.equal(e.hp,1000);});
test('third cut is stronger and combo resets after inactivity',()=>{const [g,e]=duel();const damage=[];for(let i=0;i<3;i++){g.player.x=0;g.player.z=0;e.x=0;e.z=3;const hp=e.hp;g.attack();tick(g,30);damage.push(hp-e.hp);}assert.ok(damage[2]>damage[0]);tick(g,100);g.attack();assert.equal(g.player.combo,0);});
test('vent spends pressure, pierces a line, and cannot fire without fuel',()=>{const [g,e]=duel('pike');e.z=15;const e2=g.enemies[1];Object.assign(e2,{alive:true,x:0,z:9,hp:1000,cooldown:100});assert.equal(g.vent(),true);assert.equal(g.player.charge,0);tick(g);assert.ok(e.hp<1000&&e2.hp<1000);g.player.charge=0;assert.equal(g.vent(),false);});
test('hammer breaks posture and exposed cores take extra damage',()=>{const [g,e]=duel('maul');g.attack();tick(g,25);assert.equal(e.state,'stagger');const hp=e.hp;g.hurtEnemy(e,10);assert.equal(hp-e.hp,14.5);});
test('perfect evade rewards pressure and protects from damage',()=>{const [g,e]=duel();Object.assign(e,{state:'windup',timer:.2,attackX:0,attackZ:3,attackYaw:Math.PI});const charge=g.player.charge;assert.equal(g.dodge(),true);assert.equal(g.player.charge,charge+20);g.hurtPlayer(100);assert.equal(g.player.hp,120);assert.equal(g.dodge(),false);});
test('evade cancels windup but cannot cancel a committed hit',()=>{const [g]=duel('maul');g.attack();assert.equal(g.dodge(),true);assert.equal(g.player.attack,null);tick(g,90);g.attack();tick(g,24);assert.equal(g.player.attack.hit,true);assert.equal(g.dodge(),false);});
test('death returns to anchorage, keeps objectives and clears projectiles',()=>{const g=new Game();g.progress.teeth.push('west');g.shots.push({id:1});g.hurtPlayer(999);assert.deepEqual([g.player.x,g.player.z,g.player.hp],[0,25,120]);assert.deepEqual(g.progress.teeth,['west']);assert.equal(g.shots.length,0);});
test('gentle mode reduces damage and heals out of combat',()=>{const g=new Game();g.progress.gentle=true;g.hurtPlayer(20);assert.equal(g.player.hp,111);tick(g,420);assert.equal(g.player.hp,120);});
test('full objective sequence: briefing, guarded teeth, engine, return, survey cases',()=>{const g=new Game();const visit=id=>{const l=LANDMARKS.find(l=>l.id===id);Object.assign(g.player,{x:l.x,z:l.z});g.interact();};visit('sera');assert.equal(g.progress.briefed,true);const boss=g.enemies.find(e=>e.type==='engine');assert.equal(g.active(boss),false);visit('west');assert.equal(g.progress.teeth.length,0);for(const e of g.enemies)if(e!==boss)g.hurtEnemy(e,9999);for(const id of ['west','north','east'])visit(id);assert.equal(g.progress.teeth.length,3);assert.equal(g.active(boss),true);assert.equal(g.quest().target.id,'engine');g.hurtEnemy(boss,9999);assert.equal(g.progress.won,true);assert.equal(g.quest().target.id,'sera');visit('sera');assert.equal(g.progress.returned,true);for(const id of ['cache-a','cache-b','cache-c'])visit(id);assert.equal(g.maxHP,150);visit('cache-a');assert.equal(g.maxHP,150);});
test('saves use isolated key, round trip progress, and tolerate corrupt/unavailable storage',()=>{const values=new Map([['nq.save','legacy untouched']]);const storage={getItem:k=>values.get(k),setItem:(k,v)=>values.set(k,v)};const g=new Game();g.progress.teeth=['west'];g.player.weapon='maul';assert.equal(saveProgress(storage,g),true);assert.equal(readProgress(storage).weapon,'maul');assert.deepEqual(readProgress(storage).teeth,['west']);assert.equal(values.get('nq.save'),'legacy untouched');values.set(SAVE_KEY,'{broken');assert.deepEqual(readProgress(storage),freshProgress());assert.equal(saveProgress({setItem(){throw Error();}},g),false);});
test('all objectives and enemy spawn areas reachable from anchorage',()=>{const todo=[[0,25]],seen=new Set(['0,25']);for(let i=0;i<todo.length;i++){const [x,z]=todo[i];for(const [dx,dz]of [[1,0],[-1,0],[0,1],[0,-1]]){const nx=x+dx,nz=z+dz,key=nx+','+nz;if(!seen.has(key)&&walkable(nx,nz)&&walkable(x+dx*.5,z+dz*.5)){seen.add(key);todo.push([nx,nz]);}}}for(const l of [...LANDMARKS,...SPAWNS.map(([id,x,z])=>({id,x,z,radius:3}))])assert.ok(todo.some(([x,z])=>Math.hypot(x-l.x,z-l.z)<Math.min(3,l.radius)),l.id+' is unreachable');});
