import test from 'node:test';
import assert from 'node:assert/strict';
import {FloatingStick,installPointerControls,installGameplayGestures} from '../touch-controls.mjs';
class Node {
 constructor(){this.listeners={};this.style={};this.firstElementChild={style:{}};this.classList={toggle(){}};this.captures=new Set();}
 addEventListener(name,fn){(this.listeners[name]??=[]).push(fn);}
 emit(name,values={}){const event={pointerType:'touch',pointerId:1,clientX:100,clientY:200,button:0,cancelable:true,currentTarget:this,target:this,defaultPrevented:false,preventDefault(){this.defaultPrevented=true;},...values};for(const fn of this.listeners[name]||[])fn(event);return event;}
 setPointerCapture(id){this.captures.add(id);}hasPointerCapture(id){return this.captures.has(id);}releasePointerCapture(id){this.captures.delete(id);this.emit('lostpointercapture',{pointerId:id});}
}
test('floating stick starts under the finger, has a deadzone, follows and reverses without returning to its old origin',()=>{const s=new FloatingStick();s.start(1,100,200);s.move(1,102,200);assert.deepEqual(s.value,{x:0,z:0});s.move(1,700,200);assert.equal(s.x,664);assert.equal(s.value.x,1);s.move(1,600,200);assert.equal(s.value.x,-1);assert.equal(s.x,636);s.end(1);assert.deepEqual(s.value,{x:0,z:0});});
test('movement pointer ownership survives crossing the screen and a second finger ending',()=>{const world=new Node(),stick=new Node();let value,look=0;installPointerControls({world,stick,canMove:()=>true,canLook:()=>true,width:()=>800,onMove:v=>value=v,onLook:dx=>look+=dx,onStart(){}});world.emit('pointerdown');world.emit('pointerdown',{pointerId:2,clientX:650});world.emit('pointermove',{clientX:750});assert.equal(value.x,1);assert.equal(look,0);world.emit('pointermove',{pointerId:2,clientX:670});assert.equal(look,20);world.emit('pointerup',{pointerId:2});assert.equal(value.x,1);world.emit('pointercancel');assert.deepEqual(value,{x:0,z:0});});
test('pause/reset releases captures and late pointer events cannot restart movement',()=>{const world=new Node(),stick=new Node();let value;const controls=installPointerControls({world,stick,canMove:()=>true,canLook:()=>true,width:()=>800,onMove:v=>value=v,onLook(){},onStart(){}});world.emit('pointerdown');world.emit('pointermove',{clientX:180});controls.reset();world.emit('pointermove',{clientX:190});assert.deepEqual(value,{x:0,z:0});assert.equal(world.captures.size,0);assert.equal(stick.style.left,'');});
test('mouse canvas dragging stays camera control and paused touch cannot move',()=>{const world=new Node(),stick=new Node();let value={x:0,z:0},look=0;installPointerControls({world,stick,canMove:()=>false,canLook:()=>true,width:()=>800,onMove:v=>value=v,onLook:dx=>look+=dx,onStart(){}});world.emit('pointerdown',{pointerType:'mouse'});world.emit('pointermove',{pointerType:'mouse',clientX:120});assert.equal(look,20);assert.deepEqual(value,{x:0,z:0});});
test('iOS touchend cancels zoom defaults while a HUD button activates once per tap, including rapid repeats',()=>{const doc=new Node();let clicks=0;const button={disabled:false,click(){clicks++;},closest(s){return s==='#world, #hud'||s==='#hud button'?this:null;}};installGameplayGestures(doc,()=>true);for(let i=0;i<2;i++){const touches=[{identifier:1,target:button,clientX:20,clientY:30}];doc.emit('touchstart',{target:button,changedTouches:touches});const e=doc.emit('touchend',{target:button,changedTouches:touches});assert.equal(e.defaultPrevented,true);}assert.equal(clicks,2);});
test('dragged buttons do not click, combat is not double-fired, and dialogs retain gestures',()=>{const doc=new Node();let clicks=0;const button={click(){clicks++;},closest(s){return s==='#world, #hud'||s==='#hud button'?this:null;}};installGameplayGestures(doc,()=>true);doc.emit('touchstart',{target:button,changedTouches:[{identifier:1,target:button,clientX:0,clientY:0}]});doc.emit('touchmove',{target:button,changedTouches:[{identifier:1,clientX:30,clientY:0}]});doc.emit('touchend',{target:button,changedTouches:[{identifier:1,clientX:0,clientY:0}]});assert.equal(clicks,0);const combat={click(){clicks++;},closest(){return this;}};doc.emit('touchstart',{target:combat,changedTouches:[{identifier:2,target:combat,clientX:0,clientY:0}]});doc.emit('touchend',{target:combat,changedTouches:[{identifier:2,clientX:0,clientY:0}]});assert.equal(clicks,0);const dialog={closest:s=>s==='dialog'?true:null};assert.equal(doc.emit('touchmove',{target:dialog,changedTouches:[]}).defaultPrevented,false);assert.equal(doc.emit('gesturestart',{target:dialog}).defaultPrevented,false);});
