// Original procedural score and foley. No recordings or external audio assets.
export class Soundscape {
 constructor(){this.ctx=null;this.enabled=true;this.step=0;this.clock=0;this.foot=0;this.noises=new Map();this.plucks=new Map();this.hush=0;this.scoring=false;}
 unlock(enabled=true){this.enabled=enabled;if(!this.ctx){const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)return;const c=this.ctx=new Audio(),master=this.master=c.createGain(),limiter=c.createDynamicsCompressor();this.scoreBus=c.createGain();this.scoreBus.connect(master);master.gain.value=enabled?.38:0;limiter.threshold.value=-16;limiter.ratio.value=5;master.connect(limiter);limiter.connect(c.destination);this.room=c.createConvolver();const b=c.createBuffer(2,c.sampleRate*1.6,c.sampleRate);for(let channel=0;channel<2;channel++){const d=b.getChannelData(channel);let smoothed=0;for(let i=0;i<d.length;i++){smoothed=.65*smoothed+.35*(Math.random()*2-1);d[i]=smoothed*Math.pow(1-i/d.length,3)*.35;}}this.room.buffer=b;const wet=c.createGain();wet.gain.value=.2;this.room.connect(wet);wet.connect(master);}this.master.gain.setTargetAtTime(enabled?.38:0,this.ctx.currentTime,.05);if(this.ctx.state==='suspended')this.ctx.resume().catch(()=>{});}
 tone(freq,duration=.25,volume=.12,end=freq,type='sine',delay=0){if(!this.ctx||!this.enabled)return;const c=this.ctx,t=c.currentTime+delay,o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);o.frequency.exponentialRampToValueAtTime(Math.max(20,end),t+duration);g.gain.setValueAtTime(.001,t);g.gain.linearRampToValueAtTime(volume,t+.006);g.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(g);g.connect(this.scoring?this.scoreBus:this.master);g.connect(this.room);o.start(t);o.stop(t+duration+.03);}
 noise(duration=.1,volume=.1,freq=1100,q=.5){if(!this.ctx||!this.enabled)return;const c=this.ctx,key=Math.ceil(duration*20);if(!this.noises.has(key)){const b=c.createBuffer(1,Math.ceil(c.sampleRate*key/20),c.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*Math.pow(1-i/d.length,2);this.noises.set(key,b);}const o=c.createBufferSource(),g=c.createGain(),filter=c.createBiquadFilter();o.buffer=this.noises.get(key);filter.type='bandpass';filter.frequency.value=freq;filter.Q.value=q;g.gain.value=volume;o.connect(filter);filter.connect(g);g.connect(this.scoring?this.scoreBus:this.master);g.connect(this.room);o.start();}
 pluck(note,volume=.09,delay=0){if(!this.ctx||!this.enabled)return;const c=this.ctx,f=440*2**((note-69)/12);if(!this.plucks.has(note)){const length=Math.round(c.sampleRate/f),buffer=c.createBuffer(1,c.sampleRate*3,c.sampleRate),d=buffer.getChannelData(0),ring=new Float32Array(length);for(let i=0;i<length;i++)ring[i]=Math.random()*2-1;for(let i=0;i<d.length;i++){const j=i%length;d[i]=ring[j]*Math.min(1,i/100);ring[j]=.496*(ring[j]+ring[(j+1)%length]);}this.plucks.set(note,buffer);}const o=c.createBufferSource(),g=c.createGain(),low=c.createBiquadFilter();o.buffer=this.plucks.get(note);low.type='lowpass';low.frequency.value=1900;g.gain.value=volume;o.connect(low);low.connect(g);g.connect(this.scoring?this.scoreBus:this.master);g.connect(this.room);o.start(c.currentTime+delay);}
 event(e){if(e.type==='engine-answer'){
  this.hush=3.4;if(this.ctx&&this.scoreBus){const t=this.ctx.currentTime;this.scoreBus.gain.cancelScheduledValues(t);this.scoreBus.gain.setTargetAtTime(.05,t,.08);this.scoreBus.gain.setTargetAtTime(1,t+2.8,.4);}this.noise(1.4,.22,95,1.8);this.tone(61,1.8,.17,36,'sine');this.tone(123,1.3,.07,72,'triangle',.12);
 }if(e.type==='coupling-cleared'){this.noise(.3,.2,1400,1.4);this.tone(220,.65,.08,80,'triangle');}
 const heavy=e.weapon==='maul'||e.heavy;if(e.type==='swing'){this.noise(heavy?.3:.15,heavy?.32:.2,e.weapon==='pike'?2400:780);this.tone(heavy?110:260,heavy?.22:.12,.12,heavy?38:90);if(e.vent){this.noise(.5,.35,350);this.tone(190,.5,.12,34);}}if(e.type==='hit'){this.noise(.1,.42,heavy?510:1700,1);this.tone(heavy?76:160,.16,.19,heavy?32:59);this.tone(1250,.09,.035,830);}if(e.type==='damage'){this.noise(.2,.24,440);this.tone(74,.3,.13,38);}if(e.type==='dodge')this.noise(.22,.17,690);if(e.type==='equip'){this.noise(.07,.13,2300,2);this.tone(930,.07,.02,740);}if(e.type==='perfect'){this.pluck(83,.12);this.pluck(88,.07,.08);}if(e.type==='stagger'){this.noise(.28,.45,880,1.8);this.tone(290,.3,.07,42);}if(e.type==='pickup')this.pluck(76,.04);if(['tooth','relay-secured','salvage','crew-home'].includes(e.type))for(const [i,n]of [64,71,76,78].entries())this.pluck(n,.12,i*.22);if(['victory','rescue-victory'].includes(e.type))for(const [i,n]of [52,59,64,66,71,76].entries())this.pluck(n,.15,i*.3);}
 tick(dt,combat,moving){if(this.hush>0){this.hush=Math.max(0,this.hush-dt);return;}if(!this.ctx||!this.enabled)return;this.scoring=true;try{this.score(dt,combat,moving);}finally{this.scoring=false;}}
 score(dt,combat,moving){this.foot-=dt;if(moving&&this.foot<=0){this.foot=.31;this.noise(.08,.045,650+Math.random()*250);this.tone(95,.06,.025,62);}this.clock-=dt;if(this.clock>0)return;this.clock=.68;const beat=this.step++%128,bar=Math.floor(beat/8),roots=[40,40,43,43,38,38,45,45,40,40,47,43,38,45,40,40],root=roots[bar];if(beat%8===0){this.tone(440*2**((root-69)/12),5,.045,440*2**((root-69)/12));this.pluck(root+12,.085);}
 const melody={2:71,5:76,11:78,15:76,20:71,25:67,29:69,34:66,38:71,43:74,49:73,54:69,60:71,68:76,71:78,75:83,81:78,86:76,90:71,98:69,101:66,109:64,117:71,122:64};if(melody[beat])this.pluck(melody[beat],.055);if(combat){if(beat%2===0)this.tone(90,.18,.065,38);if(beat%4===3)this.noise(.12,.055,600);if(beat%2===1)this.pluck(root+19,.045);}else if(beat%16===7)this.noise(.9,.018,350,.3);
 }
}
