const {test}=require('node:test'),assert=require('node:assert/strict'),runtime=require('../tools/lib/classic-runtime.cjs');
function setup(){const r=runtime();r.load('shattercoast');r.drain();r.G.state.enemies=[];r.G.W=768;r.G.H=480;return r;}
function capture(G){const draws=[],stack=[],ctx=new Proxy({globalAlpha:1,measureText:t=>({width:String(t).length*5}),save(){stack.push(this.globalAlpha);},restore(){this.globalAlpha=stack.pop();}},{get:(o,k)=>o[k]??(()=>{}),set:(o,k,v)=>(o[k]=v,true)});G.drawSprite=(c,s,f,x,y)=>draws.push({s,f,x,y,alpha:c.globalAlpha});return {ctx,draws};}
const go=(G,x,y)=>Object.assign(G.state.player,{x:x*16+8,y:y*16+8});
test('coastal teaching houses preserve all five native trial entries and both regional crossings',()=>{
 const r=setup(),{G}=r,{ctx,draws}=capture(G),S=G.coastScenery;G.state.opening.complete=true;G.state.delivery.complete=true;const saved=JSON.stringify({grid:G.state.grid,items:G.state.items,world:G.state.worldwake});for(const hd of [true,false]){G.hdPilot=hd;draws.length=0;G.world.draw(ctx,{x:0,y:0},3);for(const d of G.openingDrawables(ctx))d.fn();for(const id of ['shelf','saltGrass','bastion','foldHall','observatory','walkingGarden','coliseum','cairn','notice','roadStep'])assert.ok(draws.some(d=>d.s===S[id]),id);for(const sprite of Object.values(S))for(const f of G.activeSpriteDefinition(sprite).frames)for(const row of f)for(const p of row)assert.ok(p==='.'||G.activeSpriteDefinition(sprite).palette[p]);}assert.equal(JSON.stringify({grid:G.state.grid,items:G.state.items,world:G.state.worldwake}),saved);
 for(const [x,y,dest]of [[11,5,'turtleTrial'],[36,5,'samuraiTrial'],[11,24,'astronomerTrial'],[36,24,'druidTrial'],[23,14,'gauntletArena'],[23,0,'frostbellTundra'],[47,14,'overworld']]){r.load('shattercoast');r.drain();G.state.enemies=[];const cell=G.state.grid[y][x];assert.equal(G.world.portalBlockReason(cell),null);assert.equal(G.world.solid(x*16+8,y*16+8),false);go(G,x,y);G.state.portalNeedsRelease=false;G.state.portalGrace=0;G.world.checkTriggers(.5);r.drain();assert.equal(G.state.mapId,dest);assert.ok(G.world.isSafeSpawn(G.state.player.x,G.state.player.y));}
});
test('cairn keepsakes fit only actual earned hollows; native reward, pantry and atlas remain persistent',()=>{
 const r=setup(),{G}=r,{ctx,draws}=capture(G),S=G.coastScenery,draw=()=>{draws.length=0;G.world.draw(ctx,{x:0,y:0},3);for(const d of G.openingDrawables(ctx))d.fn();};G.state.opening.complete=true;G.state.delivery.complete=true;go(G,26,10);draw();assert.equal(draws.filter(d=>[S.shell,S.crane,S.key,S.acorn].includes(d.s)).length,0);G.tryOpeningInteraction();r.drain();assert.equal(G.shattercoastChronicle().complete,false);const stars=G.state.stars,spirit=G.ensureTown().spirit;G.state.items.push('tide-shell','paper-crane','orrery-key','elder-acorn');draw();assert.equal(draws.filter(d=>[S.shell,S.crane,S.key,S.acorn].includes(d.s)).length,4);assert.ok(draws.some(d=>d.s===S.cairn&&d.f===0));G.tryOpeningInteraction();r.drain();assert.equal(G.state.stars,stars+1);assert.equal(G.ensureTown().spirit,spirit+8);draw();assert.ok(draws.some(d=>d.s===S.cairn&&d.f===1));assert.ok(G.openingDrawables(ctx).some(d=>d.y===164));G.tryOpeningInteraction();r.drain();assert.equal(G.state.stars,stars+1);r.load('shattercoast');r.drain();assert.ok(G.shattercoastChronicle().complete);
 const pantry=G.state.chests.find(ch=>ch.food);go(G,pantry.x,pantry.y);G.state.player.damageTaken=2;G.world.checkTriggers(.5);r.drain();assert.equal(G.state.player.damageTaken,0);draw();assert.ok(draws.some(d=>d.s===G.homeScenery.pantryEmpty));G.state.wayfinder.posts=[];draw();assert.ok(draws.some(d=>d.s===G.greenfieldScenery.postSleeping));G.activateWayfinderPost('shattercoast',true);draw();assert.ok(draws.some(d=>d.s===G.greenfieldScenery.postAwake));
 go(G,11,3);G.reducedMotion=true;draw();assert.ok(draws.some(d=>d.s===S.bastion&&d.alpha<=.35));assert.equal(ctx.globalAlpha,1);r.load('glasswaterDesert');r.drain();assert.equal(G.drawCoastTile(ctx,{tile:'grass'},1,1,0),false);
});
