const test=require('node:test'),assert=require('node:assert/strict'),runtime=require('../tools/lib/classic-runtime.cjs');
const collect=require('./helpers/collect-treasure.cjs'),cross=require('./helpers/cross-road.cjs');
const sources=[['admiralTortoise','turtleTrial','tide-shell','turtle','blunt'],['paperRonin','samuraiTrial','paper-crane','samurai','sharp'],['professorPerihelion','astronomerTrial','orrery-key','astronomer','light'],['grandmotherBriar','druidTrial','elder-acorn','druid','dark']];
for(const [id,map,item,form,type]of sources)test(`${id} saves a ground gift, preserves physical trial return and delays its form/cairn consumers until collection`,()=>{
 const r=runtime(),{G}=r;G.state.opening.complete=G.state.delivery.complete=true;G.state.stars=28;
 G.state.claimedForms=Object.keys(G.forms).filter(f=>!['nobody','god',form].includes(f));G.questsDone=Object.values(G.forms).flatMap(f=>f.quests.map(q=>q.id));
 G.state.items=sources.map(s=>s[2]).filter(i=>i!==item);r.load(map);r.drain();
 assert.equal(G.formReady(form),false);assert.equal(G.formEchoFor(form),null);assert.equal(G.shattercoastChronicle().gathered,3);
 const e=G.state.enemies.find(e=>e.id===id);e.bossEngaged=true;e.bossIntroT=0;G.state.bossCutscene=null;
 if(id==='paperRonin')e.x=G.state.mapW*G.TILE-28;
 const stars=G.state.stars;G.combat.damageEnemy(e,{damage:e.ward.hp,type,knockback:0});G.combat.damageEnemy(e,{damage:100,type,knockback:0});r.drain();
 assert.ok(e.dead);assert.ok(G.groundRewardFor(item));
 if(id==='paperRonin'){assert.ok(G.groundRewardFor(item).x<=G.state.mapW*G.TILE-80,'a wall-side victory places the gift on clear floor');assert.ok(G.world.isSafeSpawn(G.groundRewardFor(item).x,G.groundRewardFor(item).y));}assert.ok(!G.state.items.includes(item));assert.equal(G.state.stars,stars);
 assert.equal(G.formReady(form),false);assert.equal(G.formEchoFor(form),null);assert.equal(G.storyGoal().itemId,item);
 G.saveGame();const saved=G.loadSaveData();assert.ok(saved.groundRewards.some(g=>g.item===item));assert.ok(!saved.items.includes(item));
 assert.equal(G.canWayfinderTravel(),false,'a pending victory does not make instanced travel available');
 cross(r,'shattercoast');G.state.enemies=[];Object.assign(G.state.player,{x:26*16+8,y:10*16+8});G.tryOpeningInteraction();r.drain();
 assert.ok(!G.state.items.includes('shattercoast-tideglass-chronicle'));assert.equal(G.shattercoastChronicle().gathered,3);
 cross(r,map);assert.ok(!G.state.enemies.some(e=>e.id===id),'the saved pending victory suppresses a repeat fight');
 G.state.groundRewards=G.normalizeGroundRewards(saved.groundRewards);r.load(map);r.drain();assert.ok(!G.state.enemies.some(e=>e.id===id));
 const gift=G.groundRewardFor(item);Object.assign(G.state.player,{x:gift.x,y:gift.y});collect(r,item);
 assert.equal(G.state.stars,stars+1);assert.ok(G.formReady(form));assert.ok(G.formEchoFor(form));assert.ok(!G.state.claimedForms.includes(form),'a trophy does not skip its Form Echo');
 assert.equal(G.shattercoastChronicle().gathered,4);assert.equal(G.shattercoastChronicle().complete,false);
 G.saveGame();assert.ok(G.loadSaveData().items.includes(item));assert.ok(!G.loadSaveData().groundRewards.some(g=>g.item===item));
 const rematch=G.makeEnemy(id,e.x,e.y);rematch.ward.hp=0;G.combat.damageEnemy(rematch,{damage:100,type,knockback:0});r.drain();assert.equal(G.state.stars,stars+1);assert.equal(G.groundRewardFor(item),null);
 cross(r,'shattercoast');G.state.enemies=[];Object.assign(G.state.player,{x:26*16+8,y:10*16+8});
 const spirit=G.state.town.spirit,before=G.state.stars;G.tryOpeningInteraction();r.drain();
 assert.equal(G.state.stars,before+1);assert.equal(G.state.town.spirit,spirit+8);assert.equal(G.shattercoastChronicle().complete,true);
 G.tryOpeningInteraction();r.drain();assert.equal(G.state.stars,before+1);assert.equal(G.state.town.spirit,spirit+8);
 cross(r,map);assert.ok(G.state.enemies.some(e=>e.id===id),'claimed trial keeps its original optional rematch');
 assert.equal(G.normalizeGroundRewards(saved.groundRewards).length,0,'legacy ownership discards stale pending credit');
});
