const {test}=require('node:test'),assert=require('node:assert/strict'),runtime=require('../tools/lib/classic-runtime.cjs');
const ids=['admiralTortoise','grandmotherBriar','royalFool'];
function setup(){const r=runtime();r.load('gauntletArena');r.drain();r.G.W=448;r.G.H=272;return r;}
function capture(G){const draws=[],texts=[],stack=[],ctx=new Proxy({globalAlpha:1,measureText:t=>({width:String(t).length*5}),save(){stack.push(this.globalAlpha);},restore(){this.globalAlpha=stack.pop();},fillText(t){texts.push(t);}},{get:(o,k)=>o[k]??(()=>{}),set:(o,k,v)=>(o[k]=v,true)});G.drawSprite=(c,s,f,x,y)=>draws.push({s,f,x,y,alpha:c.globalAlpha});return {ctx,draws,texts};}
const go=(G,x,y)=>Object.assign(G.state.player,{x:x*16+8,y:y*16+8});
function start(r,recovery){const {G}=r;G.state.items=ids.map(id=>G.enemies[id].trophy);assert.equal(G.startGauntlet(3,recovery),true);r.drain();}
test('Coliseum keeps four native solid benches, seven single props and its two-way coastal return',()=>{
 const r=setup(),{G}=r,{ctx,draws}=capture(G),S=G.coliseumScenery,grid=JSON.stringify(G.state.grid);assert.equal(G.state.chests.length,0);for(const [x,y]of [[4,2],[23,2],[4,14],[23,14]])assert.ok(G.world.solid(x*16+8,y*16+8));G.world.draw(ctx,{x:0,y:0},3);const props=G.openingDrawables(ctx);assert.equal(props.length,7);for(const d of props)d.fn();assert.equal(draws.filter(d=>d.s===S.bench).length,4);assert.ok(draws.some(d=>d.s===S.notice));assert.ok(draws.some(d=>d.s===S.returnStep));assert.equal(JSON.stringify(G.state.grid),grid);go(G,0,8);G.world.checkTriggers(.5);r.drain();assert.equal(G.state.mapId,'shattercoast');assert.equal(G.state.player.x,22*16+8);assert.equal(G.state.player.y,13*16+8);assert.ok(G.world.isSafeSpawn(G.state.player.x,G.state.player.y));G.state.stars=0;const entry=G.state.grid[14][23];assert.equal(entry.portal.map,'gauntletArena');assert.equal(G.world.portalBlockReason(entry),null);go(G,23,14);G.state.portalNeedsRelease=false;G.state.portalGrace=0;G.world.checkTriggers(.5);r.drain();assert.equal(G.state.mapId,'gauntletArena');assert.equal(JSON.stringify(G.state.grid),grid);assert.equal(G.startGauntlet(3,true),false);
});
test('brazier reflects actual recovery rounds and record board follows earned bests without granting healing',()=>{
 const r=setup(),{G}=r,{ctx,draws,texts}=capture(G),S=G.coliseumScenery;start(r,true);G.reducedMotion=true;const paint=()=>{draws.length=0;texts.length=0;for(const d of G.openingDrawables(ctx))d.fn();return draws.find(d=>d.s===S.brazier).f;};assert.equal(paint(),0);G.updateGauntlet(1.2);assert.equal(paint(),0);const bosses=[...G.state.gauntletRun.bosses];assert.equal(new Set(bosses).size,3);G.state.player.damageTaken=2;G.state.player.mana=1;G.gauntletBossDefeated(G.state.enemies[0]);assert.equal(G.state.player.damageTaken,0);assert.equal(G.state.player.mana,4);const saved=JSON.stringify(G.state.gauntletRun),between=JSON.stringify(G.state.gauntletBetween),damage=G.state.player.damageTaken;assert.equal(paint(),1);assert.equal(JSON.stringify(G.state.gauntletRun),saved);assert.equal(JSON.stringify(G.state.gauntletBetween),between);assert.equal(G.state.player.damageTaken,damage);G.updateGauntlet(2.1);assert.equal(paint(),0);G.gauntletBossDefeated(G.state.enemies[0]);G.updateGauntlet(2.1);G.gauntletBossDefeated(G.state.enemies[0]);G.updateGauntlet(2.7);r.drain();assert.equal(G.state.mapId,'shattercoast');assert.equal(G.state.gauntletBest,3);assert.equal(G.state.gauntletRun,null);assert.equal(G.state.stars,1);assert.ok(G.state.items.includes('manyfold-crown'));r.load('gauntletArena');r.drain();paint();assert.ok(texts.includes('REST 3'));assert.ok(texts.includes('IRON 0'));
 start(r,false);G.updateGauntlet(1.2);G.state.player.damageTaken=2;G.state.player.mana=1;G.gauntletBossDefeated(G.state.enemies[0]);assert.equal(paint(),0);assert.equal(G.state.player.damageTaken,2);assert.equal(G.state.player.mana,1);go(G,0,8);G.world.checkTriggers(.5);r.drain();assert.equal(G.state.gauntletRun,null);
});
test('benches, mounted cloth and hearth yield over travellers and NPCs without changing the grid in either pixel setting',()=>{
 const r=setup(),{G}=r,{ctx,draws}=capture(G),S=G.coliseumScenery,grid=JSON.stringify(G.state.grid);go(G,4,1);for(const hd of [true,false]){G.hdPilot=hd;draws.length=0;for(const d of G.openingDrawables(ctx))d.fn();assert.ok(draws.some(d=>d.s===S.bench&&d.alpha===.35));for(const s of Object.values(S))for(const frame of G.activeSpriteDefinition(s).frames)for(const row of frame)for(const px of row)assert.ok(px==='.'||G.activeSpriteDefinition(s).palette[px]);assert.equal(ctx.globalAlpha,1);}go(G,3,8);draws.length=0;G.drawColiseumNotice(ctx,G.state.grid[8][3],3,8);assert.ok(draws.some(d=>d.s===S.notice&&d.alpha===.35));go(G,14,8);G.state.npcs=[{x:312,y:24}];draws.length=0;for(const d of G.openingDrawables(ctx))d.fn();assert.ok(draws.some(d=>d.s===S.recordBoard&&d.alpha===.35));G.state.npcs=[{x:56,y:80}];draws.length=0;for(const d of G.openingDrawables(ctx))d.fn();assert.ok(draws.some(d=>d.s===S.brazier&&d.alpha===.35));assert.equal(JSON.stringify(G.state.grid),grid);r.load('overworld');assert.equal(G.drawColiseumTile(ctx,{tile:'floor'},1,1),false);
});
test('actual Gauntlet rematches reuse rounded pies, shells, seeds and flowers without changing their live hazards or projectiles',()=>{
 const r=setup(),{G}=r,{ctx,draws}=capture(G);start(r,true);for(const [id,action,asset,kind]of [['royalFool','pieRain',G.stageScenery.combatPie,'hazard'],['admiralTortoise','shells',G.bastionScenery.combatShell,'projectile'],['grandmotherBriar','seeds',G.hedgewayScenery.combatSeed,'projectile'],['grandmotherBriar','gardenBeds',G.hedgewayScenery.combatBloom,'bloom']]){G.state.gauntletRun.bosses=[id,...ids.filter(v=>v!==id)];G.state.gauntletRun.index=0;G.state.gauntletBetween={t:.01,opening:true};G.updateGauntlet(.02);const e=G.state.enemies[0];G.state.bossCutscene=null;G.state.bossHazards=[];Object.assign(G.state.player,{x:e.x-60,y:e.y});Object.assign(e,{bossEngaged:true,bossIntroT:0,bossPhase:3,hp:e.def.hp*.3,bossTelegraphT:.01,bossPendingAction:action});G.updateEnemies(.02);if(kind==='bloom'){G.state.player.x=e.x-20;G.updateBossHazards(1.11);}const h=JSON.stringify(G.state.bossHazards),p=JSON.stringify(G.state.projectiles);for(const hd of [true,false]){G.hdPilot=hd;draws.length=0;if(kind==='projectile')G.drawProjectiles(ctx);else G.drawBossHazards(ctx);assert.ok(draws.length>0);assert.ok(draws.every(d=>d.s===asset));assert.equal(JSON.stringify(G.state.bossHazards),h);assert.equal(JSON.stringify(G.state.projectiles),p);}if(action==='pieRain'){G.state.player.x=40;G.updateBossHazards(1.1);draws.length=0;G.drawBossHazards(ctx);assert.ok(draws.some(d=>d.s===G.stageScenery.pieImpact));}}
});
