const {test}=require('node:test'),assert=require('node:assert/strict'),runtime=require('../tools/lib/classic-runtime.cjs');
function capture(G){const draws=[],stack=[],ctx=new Proxy({globalAlpha:1,save(){stack.push(this.globalAlpha);},restore(){this.globalAlpha=stack.pop();}},{get:(o,k)=>o[k]??(()=>{}),set:(o,k,v)=>(o[k]=v,true)});G.drawSprite=(c,s,f,x,y)=>draws.push({sprite:s,frame:f,x,y,alpha:c.globalAlpha});return {ctx,draws};}
test('river lanterns and gates reflect a real awakening while canopies protect nearby travellers',()=>{
 const r=runtime(),{G}=r;r.load('lanternReach');r.drain();G.state.opening.complete=true;G.state.delivery.started=true;const {ctx,draws}=capture(G),S=G.deliveryScenery;
 G.drawDeliveryProp(ctx,'lantern',232,392,2);assert.equal(draws.pop().sprite,S.lampOff);G.drawDeliveryProp(ctx,'rainGate',392,296,2);assert.equal(draws.pop().sprite,S.gateClosed);
 Object.assign(G.state.player,{x:232,y:392});assert.equal(G.deliveryCandidate().id,'lamp0');G.tryOpeningInteraction();r.drain();assert.equal(G.state.delivery.lamps[0],1);G.drawDeliveryProp(ctx,'lantern',232,392,2);assert.equal(draws.pop().sprite,S.lampOn);G.drawDeliveryProp(ctx,'rainGate',392,296,2);assert.equal(draws.pop().sprite,S.gateClosed,'a lit lamp must still await its encounter');
 const n=G.state.npcs[0];Object.assign(n,{x:160,y:142});Object.assign(G.state.player,{x:600,y:500});G.reducedMotion=true;G.drawDeliveryProp(ctx,'willow',160,160,5);const d=draws.pop();assert.equal(d.sprite,S.willow);assert.equal(d.frame,0);assert.ok(d.alpha<=.35);assert.equal(ctx.globalAlpha,1);
 G.state.delivery.lamps[0]=2;G.drawDeliveryProp(ctx,'rainGate',392,296,2);assert.equal(draws.pop().sprite,S.gateOpen);const grid=JSON.stringify(G.state.grid),save=JSON.stringify(G.state.delivery);G.openingDrawables(ctx).forEach(d=>d.fn());assert.ok(draws.some(d=>d.sprite===G.openingScenery.props.cart&&d.x===29*16+12),'advanced courier cart uses authored art');assert.equal(JSON.stringify(G.state.grid),grid);assert.equal(JSON.stringify(G.state.delivery),save);
 for(const hd of [true,false]){G.hdPilot=hd;for(const sprite of Object.values(S)){const m=G.spriteMetrics(sprite),s=G.activeSpriteDefinition(sprite);assert.ok(m.w>0&&m.h>0);for(const f of s.frames)for(const row of f)for(const p of row)assert.ok(p==='.'||s.palette[p]);}}
});
test('quay houses show native delivery payoffs and drawing cannot award another parcel',()=>{
 const r=runtime(),{G}=r;r.load('sunriseQuay');r.drain();G.state.delivery.started=true;G.state.delivery.keeper=true;const {ctx,draws}=capture(G),S=G.deliveryScenery;
 G.drawDeliveryProp(ctx,'birthdayHouse',456,392,2);assert.equal(draws.pop().sprite,S.birthdayHouseCold);Object.assign(G.state.player,{x:456,y:424});assert.equal(G.deliveryCandidate().id,'present');G.tryOpeningInteraction();r.drain();assert.ok(G.state.delivery.parcels.includes('present'));G.drawDeliveryProp(ctx,'birthdayHouse',456,392,2);assert.equal(draws.pop().sprite,S.birthdayHouseWarm);
 const progress=JSON.stringify(G.state.delivery),grid=JSON.stringify(G.state.grid),spirit=G.state.town.spirit;G.reducedMotion=true;G.drawDeliveryProp(ctx,'birthdayHouse',456,392,2);assert.equal(draws.pop().frame,0);G.drawDeliveryProp(ctx,'lantern',360,440,2);assert.equal(draws.pop().sprite,S.lampOn);G.drawDeliveryProp(ctx,'bakery',200,168,2);assert.equal(draws.pop().sprite,S.bakeryCold);G.drawDeliveryProp(ctx,'letterHouse',488,184,2);assert.equal(draws.pop().sprite,S.letterHouseCold);
 G.drawDeliveryProp(ctx,'trailhead',568,328,2);assert.ok(!draws.some(d=>d.sprite===S.trailhead));assert.equal(JSON.stringify(G.state.delivery),progress);assert.equal(JSON.stringify(G.state.grid),grid);assert.equal(G.state.town.spirit,spirit);
});
