const {test}=require('node:test'),assert=require('node:assert/strict'),runtime=require('../tools/lib/classic-runtime.cjs');
function setup(){const r=runtime();r.G.state.opening.complete=true;r.G.state.delivery.complete=true;r.load('dungeon');r.drain();r.G.W=464;r.G.H=288;return r;}
function capture(G){const draws=[],stack=[],ctx=new Proxy({globalAlpha:1,measureText:t=>({width:String(t).length*5}),save(){stack.push(this.globalAlpha);},restore(){this.globalAlpha=stack.pop();}},{get:(o,k)=>o[k]??(()=>{}),set:(o,k,v)=>(o[k]=v,true)});G.drawSprite=(c,s,f,x,y)=>draws.push({s,f,x,y,alpha:c.globalAlpha});return {ctx,draws};}
const go=(G,x,y)=>Object.assign(G.state.player,{x:x*16+8,y:y*16+8});
function paint(G,ctx){G.world.draw(ctx,{x:0,y:0},3);const props=G.openingDrawables(ctx);for(const d of props)d.fn();return props;}
test('the storehouse preserves native cover, both vault corridors, eleven encounters and its gated two-way Greenfield road',()=>{
 const r=setup(),{G}=r,{ctx,draws}=capture(G),S=G.dungeonScenery,grid=JSON.stringify(G.state.grid),enemies=JSON.stringify(G.state.enemies);assert.equal(G.state.mapW,29);assert.equal(G.state.mapH,18);assert.equal(G.state.enemies.length,11);assert.equal(G.state.enemies.find(e=>e.def.id==='brute').x,72);assert.ok(G.world.solid(56,152));assert.ok(G.world.solid(392,152));const props=paint(G,ctx);assert.equal(props.length,4);assert.equal(draws.filter(d=>d.s===S.brokenPillar).length,2);assert.equal(draws.filter(d=>d.s===S.bracketLamp).length,2);assert.ok(draws.some(d=>d.s===S.returnStep));assert.equal(JSON.stringify(G.state.grid),grid);assert.equal(JSON.stringify(G.state.enemies),enemies);const seen=new Set(['15,14']),queue=[[15,14]];for(let i=0;i<queue.length;i++)for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){const x=queue[i][0]+dx,y=queue[i][1]+dy,key=x+','+y;if(seen.has(key)||G.world.solid(x*16+8,y*16+8))continue;seen.add(key);queue.push([x,y]);}for(const key of ['4,5','21,5','1,1','8,1','13,15','15,16','24,1'])assert.ok(seen.has(key));go(G,15,16);G.world.checkTriggers(.5);r.drain();assert.equal(G.state.mapId,'overworld');assert.ok(G.world.isSafeSpawn(G.state.player.x,G.state.player.y));assert.equal(G.state.player.x,968);assert.equal(G.state.player.y,24);const entry=G.state.grid[0][60];G.state.stars=0;assert.ok(G.world.portalBlockReason(entry));G.state.stars=3;assert.equal(G.world.portalBlockReason(entry),null);go(G,60,0);G.state.portalGrace=0;G.state.portalNeedsRelease=false;G.world.checkTriggers(.5);r.drain();assert.equal(G.state.mapId,'dungeon');assert.equal(JSON.stringify(G.state.grid),grid);
});
test('the Crest case opens only through native interaction and restores its empty appearance for existing saves',()=>{
 const r=setup(),{G}=r,{ctx,draws}=capture(G),S=G.dungeonScenery,ch=G.state.chests.find(c=>!c.food);paint(G,ctx);assert.ok(draws.some(d=>d.s===S.crestChest&&d.f===0));assert.ok(!G.state.items.includes('knights-crest'));go(G,1,1);G.world.checkTriggers(.5);r.drain();assert.ok(ch.opened);assert.equal(G.state.items.filter(id=>id==='knights-crest').length,1);assert.ok(G.state.opened.includes(ch.key));draws.length=0;const items=JSON.stringify(G.state.items);paint(G,ctx);assert.ok(draws.some(d=>d.s===S.crestChest&&d.f===1));assert.equal(JSON.stringify(G.state.items),items);G.world.checkTriggers(.5);r.drain();assert.equal(G.state.items.filter(id=>id==='knights-crest').length,1);G.state.opened=G.state.opened.filter(id=>id!==ch.key);r.load('dungeon');r.drain();assert.ok(G.state.chests.find(c=>!c.food).opened);assert.equal(G.state.items.filter(id=>id==='knights-crest').length,1);
});
test('the biscuit crate and road atlas follow real serving, early-return, refill and activation without granting progress during drawing',()=>{
 const r=setup(),{G}=r,{ctx,draws}=capture(G),S=G.dungeonScenery,ch=G.state.chests.find(c=>c.food);G.state.wayfinder.posts=[];paint(G,ctx);assert.ok(draws.some(d=>d.s===S.biscuitCrate&&d.f===0));assert.ok(draws.some(d=>d.s===S.roadAtlas&&d.f===0));assert.equal(G.activateWayfinderPost('dungeon',true),true);go(G,8,1);G.state.player.damageTaken=2;G.world.checkTriggers(.5);r.drain();assert.equal(G.state.player.damageTaken,0);assert.equal(G.state.pantries[ch.key].servings,1);draws.length=0;const pantry=JSON.stringify(G.state.pantries),atlas=JSON.stringify(G.state.wayfinder);paint(G,ctx);assert.ok(draws.some(d=>d.s===S.biscuitCrate&&d.f===1));assert.ok(draws.some(d=>d.s===S.roadAtlas&&d.f===1));assert.equal(JSON.stringify(G.state.pantries),pantry);assert.equal(JSON.stringify(G.state.wayfinder),atlas);r.load('dungeon');r.drain();assert.ok(G.state.chests.find(c=>c.food).opened);G.state.pantries[ch.key].readyAt=Date.now()-1;go(G,8,1);G.world.checkTriggers(.5);assert.ok(G.state.chests.find(c=>c.food).needsLeave);assert.equal(G.state.pantries[ch.key].servings,1);go(G,9,2);G.world.checkTriggers(.5);go(G,8,1);G.world.checkTriggers(.5);r.drain();assert.equal(G.state.pantries[ch.key].servings,2);
});
test('authored vault fittings yield over actors and support every frame in both pixel settings without replacing other maps',()=>{
 const r=setup(),{G}=r,{ctx,draws}=capture(G),S=G.dungeonScenery;assert.equal(Object.keys(S).length,8);const grid=JSON.stringify(G.state.grid);for(const hd of [true,false]){G.hdPilot=hd;G.reducedMotion=true;for(const sprite of Object.values(S))for(const frame of G.activeSpriteDefinition(sprite).frames)for(const row of frame)for(const px of row)assert.ok(px==='.'||G.activeSpriteDefinition(sprite).palette[px]);go(G,3,8);draws.length=0;paint(G,ctx);assert.ok(draws.some(d=>d.s===S.brokenPillar&&d.alpha===.35));go(G,4,5);draws.length=0;paint(G,ctx);assert.ok(draws.some(d=>d.s===S.bracketLamp&&d.alpha===.35));go(G,15,14);G.state.npcs=[{x:24,y:24}];draws.length=0;paint(G,ctx);assert.ok(draws.some(d=>d.s===S.crestChest&&d.alpha===.35));assert.equal(ctx.globalAlpha,1);}assert.equal(JSON.stringify(G.state.grid),grid);r.load('overworld');assert.equal(G.drawDungeonTile(ctx,{tile:'floor'},1,1),false);assert.equal(G.drawDungeonCache(ctx,{food:false,x:1,y:1}),false);assert.equal(G.drawDungeonPost(ctx,{x:0,y:0},true,true),false);
});
