const {test}=require('node:test'),assert=require('node:assert/strict'),runtime=require('../tools/lib/classic-runtime.cjs');
function setup(){const r=runtime(),{G}=r;G.state.opening.complete=true;G.state.delivery.complete=true;r.load('jesterTrial');r.drain();r.run('js/engine/ui.js');G.state.enemies=[];G.state.bossCutscene=null;G.guidanceShowStoryCard=()=>true;const c=r.nodes.get('ui').getContext('2d'),labels=[],rects=[];c.fillText=t=>labels.push(String(t));c.fillRect=(x,y,w,h)=>rects.push({x,y,w,h});const draw=cam=>{labels.length=0;rects.length=0;G.ui.drawHUD(cam);};return {r,G,labels,rects,draw};}
test('story and mastery panels yield at the Stage cover approach and return without changing progress across HUD modes, camera offsets and form sizes',()=>{
 const {G,labels,draw}=setup(),cam={x:128,y:0};G.questCounts[G.forms.nobody.quests[0].id]=1;const progress=JSON.stringify({counts:G.questCounts,done:G.questsDone}),time=G.state.time;
 for(const mode of ['keyboard','touch','controller'])for(const id of ['nobody','dragon']){G.input.isTouch=mode==='touch';G.input.hasGamepad=mode==='controller';G.state.formId=id;Object.assign(G.state.player,{x:cam.x+100,y:56});draw(cam);assert.ok(!labels.some(t=>t.includes('MAIN STORY')),'northern cover approach must reveal the traveller');Object.assign(G.state.player,{x:cam.x+G.W-65,y:G.input.isTouch?68:90});draw(cam);assert.ok(!labels.some(t=>t.includes('MASTERY')),'right-hand lessons must yield over either form');Object.assign(G.state.player,{x:cam.x+100,y:140});draw(cam);assert.ok(labels.some(t=>t.includes('MAIN STORY')));assert.ok(labels.some(t=>t.includes('MASTERY')));assert.ok(labels.some(t=>t.includes('Lv')),'essential form information stays visible');}
 assert.equal(JSON.stringify({counts:G.questCounts,done:G.questsDone}),progress);assert.equal(G.state.time,time);
});
test('tutorial and minimap yield over the traveller then return, without advancing the tutorial',()=>{
 const {G,labels,rects,draw}=setup(),cam={x:0,y:0};G.tutorial.init(null);const prompt=G.tutorial.prompt();assert.ok(prompt);
 for(const touch of [true,false]){G.input.isTouch=touch;const y=touch?72:G.H-38;Object.assign(G.state.player,{x:touch?90:G.W/2,y});draw(cam);assert.ok(!labels.includes(prompt.title));Object.assign(G.state.player,{x:touch?230:30,y:130});draw(cam);assert.ok(labels.includes(prompt.title));assert.equal(G.tutorial.prompt().title,prompt.title);}
 G.input.isTouch=false;Object.assign(G.state.player,{x:G.W-32,y:52});draw(cam);assert.ok(!rects.some(q=>q.w===62&&q.h===42));Object.assign(G.state.player,{x:100,y:140});draw(cam);assert.ok(rects.some(q=>q.w===62&&q.h===42));
});
test('engaged boss focus clears wayfinder labels through actual pie warnings and restores guidance after the encounter',()=>{
 const {r,G,labels,draw}=setup();r.load('jesterTrial');r.drain();G.state.bossCutscene=null;const e=G.state.enemies.find(e=>e.def.id==='royalFool');G.state.enemies=[e];Object.assign(G.state.player,{x:e.x-60,y:e.y});Object.assign(e,{bossEngaged:true,bossIntroT:0,bossPhase:3,hp:e.def.hp*.3,bossTelegraphT:.01,bossPendingAction:'pieRain'});G.updateEnemies(.02);assert.equal(G.state.bossHazards.filter(h=>h.kind==='pieRain').length,3);G.drawGuidanceHud=c=>c.fillText('WAYFINDER TARGET',100,135);const hazards=JSON.stringify(G.state.bossHazards.map(h=>({x:h.x,y:h.y,t:h.t,warning:h.warning,active:h.active}))),cam={x:128,y:46};
 for(const mode of ['keyboard','touch','controller']){G.input.isTouch=mode==='touch';G.input.hasGamepad=mode==='controller';draw(cam);assert.ok(!labels.includes('WAYFINDER TARGET'));assert.ok(labels.some(t=>t.includes('TANSY')),'boss health and phase remain visible');}
 assert.equal(JSON.stringify(G.state.bossHazards.map(h=>({x:h.x,y:h.y,t:h.t,warning:h.warning,active:h.active}))),hazards);e.dead=true;draw(cam);assert.ok(labels.includes('WAYFINDER TARGET'));
});
