const {test}=require('node:test'),assert=require('node:assert/strict'),runtime=require('../tools/lib/classic-runtime.cjs');
function setup(){const r=runtime();r.load('godTrial');r.drain();r.G.state.enemies=[];r.G.W=448;r.G.H=272;return r;}
function capture(G){const draws=[],bars=[],stack=[],ctx=new Proxy({globalAlpha:1,measureText:t=>({width:String(t).length*5}),save(){stack.push(this.globalAlpha);},restore(){this.globalAlpha=stack.pop();},fillRect(x,y,w,h){bars.push({x,y,w,h,color:this.fillStyle});}},{get:(o,k)=>o[k]??(()=>{}),set:(o,k,v)=>(o[k]=v,true)});G.drawSprite=(c,s,f,x,y)=>draws.push({s,f,x,y,alpha:c.globalAlpha});return {ctx,draws,bars};}
const go=(G,x,y)=>Object.assign(G.state.player,{x:x*16+8,y:y*16+8});
test('Firmament keeps four solid cover points and the native mastery/Worldmark gate and west return',()=>{
 const r=setup(),{G}=r,{ctx,draws}=capture(G),S=G.firmamentScenery,cover=[[9,3],[18,3],[9,13],[18,13]],saved=JSON.stringify(G.state.grid);
 for(const [x,y]of cover)assert.ok(G.world.solid(x*16+8,y*16+8));assert.equal(G.state.grid.flat().filter(c=>c.tile==='rock').length,4);G.world.draw(ctx,{x:0,y:0},3);for(const d of G.openingDrawables(ctx))d.fn();assert.equal(draws.filter(d=>d.s===S.routeCase).length,4);assert.ok(draws.some(d=>d.s===S.routeArchive));assert.ok(draws.some(d=>d.s===S.blankChart));assert.ok(draws.some(d=>d.s===S.notice));assert.ok(draws.some(d=>d.s===S.returnStep));assert.equal(JSON.stringify(G.state.grid),saved);
 go(G,0,8);G.world.checkTriggers(.5);r.drain();assert.equal(G.state.mapId,'overworld');assert.equal(G.state.player.x,110*16+8);assert.equal(G.state.player.y,1*16+8);const entry=G.state.grid.flatMap((row,y)=>row.flatMap((cell,x)=>cell.portal?.map==='godTrial'?[{cell,x,y}]:[]))[0];assert.equal(entry.cell.masteryPortfolio,true);assert.equal(entry.cell.allWorldMarks,true);G.state.stars=99;assert.ok(G.world.portalBlockReason(entry.cell));G.state.worldwake.marks=['sky','stone','thread','echo','light','heart'];const forms=G.formOrder.filter(id=>id!=='god');G.questsDone=forms.flatMap(id=>G.forms[id].quests.slice(0,2).map(q=>q.id));assert.ok(G.world.portalBlockReason(entry.cell));for(const id of forms.slice(0,6))G.questsDone.push(...G.forms[id].quests.slice(2).map(q=>q.id));G.state.worldwake.marks.pop();assert.ok(G.world.portalBlockReason(entry.cell));G.state.worldwake.marks.push('heart');assert.equal(G.world.portalBlockReason(entry.cell),null);go(G,entry.x,entry.y);G.state.portalNeedsRelease=false;G.state.portalGrace=0;G.world.checkTriggers(.5);r.drain();assert.equal(G.state.mapId,'godTrial');assert.equal(JSON.stringify(G.state.grid),saved);
});
test('Firmament map-cookie pantry follows actual renewable pantry healing, cooldown, leave-to-refill and saved servings',()=>{
 const r=setup(),{G}=r,{ctx,draws,bars}=capture(G),ch=G.state.chests[0],S=G.firmamentScenery;assert.equal(ch.food,true);assert.equal(ch.key,'godTrial:6,5');const draw=()=>{draws.length=0;bars.length=0;G.drawFirmamentCache(ctx,G.state.chests[0]);};draw();assert.equal(draws[0].f,0);G.state.player.damageTaken=2;go(G,6,5);G.world.checkTriggers(.5);r.drain();assert.equal(G.state.player.damageTaken,0);assert.equal(G.state.pantries[ch.key].servings,1);assert.ok(ch.readyAt>Date.now());draw();assert.equal(draws[0].s,S.cookieFolio);assert.equal(draws[0].f,1);assert.ok(bars.some(b=>b.w===20&&b.color==='#394453'));assert.ok(!G.state.opened.includes(ch.key));G.world.checkTriggers(.5);assert.equal(G.state.pantries[ch.key].servings,1);
 r.load('godTrial');r.drain();G.state.enemies=[];draw();assert.equal(draws[0].f,1);const current=G.state.chests[0];G.state.pantries[ch.key].readyAt=Date.now()-1;go(G,6,5);G.world.checkTriggers(.5);assert.equal(current.opened,false);assert.equal(current.needsLeave,true);G.world.checkTriggers(.5);assert.equal(G.state.pantries[ch.key].servings,1);go(G,8,5);G.world.checkTriggers(.5);go(G,6,5);G.world.checkTriggers(.5);assert.equal(G.state.pantries[ch.key].servings,2);const journal=JSON.stringify(G.state.pantries);draw();assert.equal(JSON.stringify(G.state.pantries),journal);
});
test('folded-map cases and mounted folios yield to player and NPCs in both pixel settings without changing terrain or painter state',()=>{
 const r=setup(),{G}=r,{ctx,draws}=capture(G),S=G.firmamentScenery;G.reducedMotion=true;go(G,9,2);const saved=JSON.stringify(G.state.grid);for(const hd of [true,false]){G.hdPilot=hd;draws.length=0;for(const d of G.openingDrawables(ctx))d.fn();assert.ok(draws.some(d=>d.s===S.routeCase&&d.alpha<=.35));assert.ok(draws.filter(d=>d.s===S.routeCase).every(d=>d.f===0));for(const sprite of Object.values(S))for(const frame of G.activeSpriteDefinition(sprite).frames)for(const row of frame)for(const p of row)assert.ok(p==='.'||G.activeSpriteDefinition(sprite).palette[p]);assert.equal(ctx.globalAlpha,1);}assert.equal(JSON.stringify(G.state.grid),saved);go(G,13,8);G.state.npcs=[{x:152,y:40}];draws.length=0;for(const d of G.openingDrawables(ctx))d.fn();assert.ok(draws.some(d=>d.s===S.routeCase&&d.alpha<=.35));G.state.npcs=[{x:104,y:24}];draws.length=0;for(const d of G.openingDrawables(ctx))d.fn();assert.ok(draws.some(d=>d.s===S.routeArchive&&d.alpha<=.35));r.load('overworld');assert.equal(G.drawFirmamentTile(ctx,{tile:'floor'},1,1),false);assert.equal(G.drawFirmamentCache(ctx,{x:1,y:1}),false);
});
