const {test}=require('node:test'),assert=require('node:assert/strict'),runtime=require('../tools/lib/classic-runtime.cjs');
test('optional cards clear nearby living foes with their actual bounds, then return for distant and defeated foes',()=>{
 const r=runtime(),{G}=r;G.state.opening.complete=true;G.state.delivery.complete=true;r.load('overworld');r.drain();r.run('js/engine/ui.js');G.tutorial.prompt=()=>null;G.world.nearPortal=()=>null;G.guidanceShowStoryCard=()=>true;G.questCounts[G.forms.nobody.quests[0].id]=1;
 const cam={x:320,y:160},c=r.nodes.get('ui').getContext('2d'),labels=[];c.fillText=t=>labels.push(String(t));const draw=()=>{labels.length=0;G.ui.drawHUD(cam);};
 for(const hd of [true,false])for(const mode of ['touch','keyboard','controller']){G.hdPilot=hd;G.input.isTouch=mode==='touch';G.input.hasGamepad=mode==='controller';Object.assign(G.state.player,{x:cam.x+160,y:cam.y+100});const e=G.makeEnemy('brute',cam.x+205,cam.y+(mode==='touch'?87:105));G.state.enemies=[e];const before=JSON.stringify({e,counts:G.questCounts,p:G.state.player});draw();assert.ok(!labels.some(t=>t.includes('MASTERY')));assert.ok(labels.some(t=>t.includes(' Lv')));assert.equal(JSON.stringify({e,counts:G.questCounts,p:G.state.player}),before);e.dead=true;draw();assert.ok(labels.some(t=>t.includes('MASTERY')));e.dead=false;G.state.player.x=cam.x+30;draw();assert.ok(labels.some(t=>t.includes('MASTERY')));}
});
test('foe guidance clears authored heads while preserving distant navigation and measured ranged practice geometry',()=>{
 const r=runtime(),{G}=r;G.state.opening.complete=true;G.state.delivery.complete=true;r.load('overworld');r.drain();const e=G.makeEnemy('brute',240,120);G.state.enemies=[e];G.storyGoal=()=>({guide:'mastery',formId:'nobody'});const actual=G.guidanceTarget();assert.equal(actual.entity,e,'ordinary mastery retains its live actor reference');
 let target={x:e.x,y:e.y,entity:e,kind:'form',color:'#aa77cc',spatial:true,destination:'practice',text:'Practice here',tileX:15,tileY:7,practiceDistance:64};G.guidanceTarget=()=>target;G.requestGuidance(false);
 const points=[],arcs=[],rects=[],labels=[];const ctx=new Proxy({save(){},restore(){},translate(x,y){points.push({x,y});},arc(x,y,r){arcs.push({x,y,r});},fillRect(x,y,w,h){rects.push({x,y,w,h});},fillText(t){labels.push(t);},measureText:t=>({width:String(t).length*5})},{get:(o,k)=>o[k]??(()=>{})});
 for(const hd of [true,false]){G.hdPilot=hd;points.length=arcs.length=rects.length=labels.length=0;const before=JSON.stringify(e),cam={x:80,y:32};G.drawWorldGuidance(ctx,cam,1);G.drawGuidanceHud(ctx,cam);assert.ok(arcs.some(a=>a.r===64));assert.ok(!arcs.some(a=>a.r<20),'generic circle no longer overlays the body');assert.ok(rects.some(q=>q.y===e.y+3&&q.h===1));assert.ok(points.at(-1).y+10<=e.y-cam.y-G.spriteMetrics(e.def.sprite).h);assert.equal(labels.length,0,'nearby foe label cannot hide another fighter');assert.equal(JSON.stringify(e),before);points.length=0;target={...target,x:1000,entity:null};G.drawGuidanceHud(ctx,cam);assert.ok(points.length);assert.ok(labels.length);target={...target,x:e.x,entity:e};}
});
