const {test}=require('node:test'),assert=require('node:assert/strict'),runtime=require('../tools/lib/classic-runtime.cjs');
function setup(){const r=runtime();r.load('frostbellTundra');r.drain();r.G.state.enemies=[];r.G.W=736;r.G.H=464;return r;}
function capture(G){const draws=[],stack=[],ctx=new Proxy({globalAlpha:1,measureText:t=>({width:String(t).length*5}),save(){stack.push(this.globalAlpha);},restore(){this.globalAlpha=stack.pop();}},{get:(o,k)=>o[k]??(()=>{}),set:(o,k,v)=>(o[k]=v,true)});G.drawSprite=(c,s,f,x,y)=>draws.push({s,f,x,y,alpha:c.globalAlpha});return {ctx,draws};}
const go=(G,x,y)=>Object.assign(G.state.player,{x:x*16+8,y:y*16+8});
test('five authored bell arches leave native passages intact and Echo slabs follow actual victory and saved returns',()=>{
 const r=setup(),{G}=r,{ctx,draws}=capture(G),S=G.frostbellStations,draw=()=>{draws.length=0;for(const d of G.openingDrawables(ctx))d.fn();};const saved=JSON.stringify({grid:G.state.grid,items:G.state.items,world:G.state.worldwake});for(const hd of [true,false]){G.hdPilot=hd;draw();assert.equal(draws.filter(d=>d.s===S.arch).length,5);assert.equal(draws.filter(d=>d.s===S.echoSlab).length,0);for(const sprite of Object.values(S))for(const f of G.activeSpriteDefinition(sprite).frames)for(const row of f)for(const p of row)assert.ok(p==='.'||G.activeSpriteDefinition(sprite).palette[p]);}assert.equal(JSON.stringify({grid:G.state.grid,items:G.state.items,world:G.state.worldwake}),saved);assert.ok(G.world.solid(248,312));G.events.emit('pickup',{item:'trophy-bell-titan'});assert.ok(G.hasWorldMark('echo'));assert.equal(G.world.solid(248,312),false);draw();assert.equal(draws.filter(d=>d.s===S.echoSlab).length,12);r.load('frostbellTundra');r.drain();draw();assert.equal(draws.filter(d=>d.s===S.echoSlab).length,12);assert.equal(G.state.grid[19][17].tile,'water');
});
test('mounted snow roofs yield around travellers, hold still under reduced motion and preserve the painter context',()=>{
 const r=setup(),{G}=r,{ctx,draws}=capture(G),S=G.frostbellStations;G.reducedMotion=true;go(G,7,6);const alpha=ctx.globalAlpha;for(const d of G.openingDrawables(ctx))d.fn();assert.ok(draws.some(d=>d.s===S.arch&&d.alpha<=.35));assert.ok(draws.filter(d=>d.s===S.arch).every(d=>d.f===0));assert.equal(ctx.globalAlpha,alpha);G.state.npcs=[{x:280,y:112}];go(G,23,14);draws.length=0;for(const d of G.openingDrawables(ctx))d.fn();assert.ok(draws.some(d=>d.s===S.arch&&d.x===280&&d.alpha<=.35));r.load('shattercoast');r.drain();assert.equal(G.drawFrostbellArch(ctx,0,0),false);
});
