const {test}=require('node:test'),assert=require('node:assert/strict'),runtime=require('../tools/lib/classic-runtime.cjs');
function setup(){const r=runtime();r.load('frostbellTundra');r.drain();r.G.state.enemies=[];r.G.W=736;r.G.H=464;return r;}
function capture(G){const draws=[],stack=[],ctx=new Proxy({globalAlpha:1,measureText:t=>({width:String(t).length*5}),save(){stack.push(this.globalAlpha);},restore(){this.globalAlpha=stack.pop();}},{get:(o,k)=>o[k]??(()=>{}),set:(o,k,v)=>(o[k]=v,true)});G.drawSprite=(c,s,f,x,y)=>draws.push({s,f,x,y,alpha:c.globalAlpha});return {ctx,draws};}
const go=(G,x,y)=>Object.assign(G.state.player,{x:x*16+8,y:y*16+8});
test('Frostbell scenery reads actual Chime, atlas, recovery and restoration state while both seamless exits remain native',()=>{
 const r=setup(),{G}=r,{ctx,draws}=capture(G),S=G.frostbellScenery,draw=()=>{draws.length=0;G.world.draw(ctx,{x:0,y:0},3);for(const d of G.openingDrawables(ctx))d.fn();};G.state.items.push('trophy-bell-titan');G.state.worldwake=G.normalizeWorldwake(undefined,{items:G.state.items});r.load('frostbellTundra');r.drain();G.state.enemies=[];const before=JSON.stringify({items:G.state.items,world:G.state.worldwake,grid:G.state.grid,stars:G.state.stars,details:G.state.restorationDetails});draw();assert.equal(G.state.restorationDetails.length,28);assert.ok(draws.some(d=>d.s===G.groveScenery.flower));assert.ok(draws.some(d=>d.s===G.townScenery.lantern));assert.ok(draws.some(d=>d.s===S.shrub));assert.equal(draws.filter(d=>d.s===G.frostbellStations.echoSlab).length,12);assert.equal(JSON.stringify({items:G.state.items,world:G.state.worldwake,grid:G.state.grid,stars:G.state.stars,details:G.state.restorationDetails}),before);
 go(G,7,20);Object.assign(G.state.player,{damageTaken:2,mana:0});G.world.checkTriggers(.5);assert.equal(G.state.player.damageTaken,0);assert.equal(G.state.player.mana,G.playerMaxMana());const box=G.state.chests.find(c=>c.chest.item==='frostbell-chime');go(G,box.x,box.y);G.world.checkTriggers(.5);r.drain();draw();assert.ok(draws.some(d=>d.s===S.cache&&d.f===1));assert.equal(G.state.items.filter(i=>i==='frostbell-chime').length,1);r.load('frostbellTundra');r.drain();G.state.enemies=[];draw();assert.ok(draws.some(d=>d.s===S.cache&&d.f===1));G.state.wayfinder.posts=[];draw();assert.ok(draws.some(d=>d.s===G.greenfieldScenery.postSleeping));G.activateWayfinderPost('frostbellTundra',true);draw();assert.ok(draws.some(d=>d.s===G.greenfieldScenery.postAwake));go(G,45,14);G.world.checkTriggers(.5);r.drain();assert.equal(G.state.mapId,'stormspinePeaks');r.load('frostbellTundra');r.drain();go(G,23,28);G.world.checkTriggers(.5);r.drain();assert.equal(G.state.mapId,'shattercoast');assert.equal(G.drawFrostbellTile(ctx,{tile:'grass'},1,1,3),false);
});
test('snowy pines yield around travellers and both pixel settings preserve collision, poses and the native frozen basins',()=>{
 const r=setup(),{G}=r,{ctx,draws}=capture(G),S=G.frostbellScenery;G.reducedMotion=true;const saved=JSON.stringify({grid:G.state.grid,items:G.state.items,details:G.state.restorationDetails});for(const hd of [true,false]){G.hdPilot=hd;for(const sprite of Object.values(S))for(const frame of G.activeSpriteDefinition(sprite).frames)for(const row of frame)for(const p of row)assert.ok(p==='.'||G.activeSpriteDefinition(sprite).palette[p]);go(G,3,3);draws.length=0;G.world.draw(ctx,{x:0,y:0},10);for(const d of G.openingDrawables(ctx))d.fn();assert.ok(draws.some(d=>d.s===S.pine&&d.alpha<=.35));assert.ok(draws.filter(d=>d.s===S.pine).every(d=>d.f===0));assert.ok(draws.some(d=>d.s===G.prairieScenery.hearth&&d.f===0));for(const id of Object.keys(S))assert.ok(draws.some(d=>d.s===S[id]),id);assert.equal(ctx.globalAlpha,1);}assert.equal(JSON.stringify({grid:G.state.grid,items:G.state.items,details:G.state.restorationDetails}),saved);assert.ok(G.world.solid(248,312));assert.equal(G.world.solid(248,360),false);assert.ok(G.frostbellWaterColors());
});
