const {test}=require('node:test'),assert=require('node:assert/strict'),runtime=require('../tools/lib/classic-runtime.cjs');
function setup(){const r=runtime();r.load('hangingGardens');r.drain();r.G.state.enemies=[];r.G.W=736;r.G.H=464;return r;}
function capture(G){const draws=[],stack=[],ctx=new Proxy({globalAlpha:1,measureText:t=>({width:String(t).length*5}),save(){stack.push(this.globalAlpha);},restore(){this.globalAlpha=stack.pop();}},{get:(o,k)=>o[k]??(()=>{}),set:(o,k,v)=>(o[k]=v,true)});G.drawSprite=(c,s,f,x,y)=>draws.push({s,f,x,y,alpha:c.globalAlpha});return {ctx,draws};}
const go=(G,x,y)=>Object.assign(G.state.player,{x:x*16+8,y:y*16+8});
test('authored garden crossings follow real victory and old-save state without creating rewards or changing native routes',()=>{
 const r=setup(),{G}=r,{ctx,draws}=capture(G),S=G.gardensScenery;const draw=()=>{draws.length=0;G.world.draw(ctx,{x:0,y:0},3);for(const d of G.openingDrawables(ctx))d.fn();};
 draw();assert.equal(draws.filter(d=>d.s===S.arch).length,4);assert.equal(draws.filter(d=>d.s===S.planter).length,8);assert.equal(draws.filter(d=>d.s===S.raisedStep).length,0);assert.ok(G.world.solid(248,168));
 G.state.items.push('trophy-old-mason');G.state.worldwake=G.normalizeWorldwake(undefined,{items:G.state.items});G.events.emit('pickup',{item:'trophy-old-mason'});const before=JSON.stringify({items:G.state.items,world:G.state.worldwake,grid:G.state.grid,stars:G.state.stars});draw();assert.equal(draws.filter(d=>d.s===S.raisedStep).length,8);assert.equal(G.world.solid(248,168),false);assert.ok(G.world.solid(280,168));assert.equal(JSON.stringify({items:G.state.items,world:G.state.worldwake,grid:G.state.grid,stars:G.state.stars}),before);
 r.load('hangingGardens');r.drain();draw();assert.equal(draws.filter(d=>d.s===S.raisedStep).length,8);assert.equal(G.state.restorationDetails.length,28);assert.ok(draws.some(d=>d.s===G.groveScenery.flower));assert.ok(draws.some(d=>d.s===G.townScenery.lantern));
 go(G,7,20);Object.assign(G.state.player,{damageTaken:2,mana:0});G.world.checkTriggers(.5);assert.equal(G.state.player.damageTaken,0);assert.equal(G.state.player.mana,G.playerMaxMana());const box=G.state.chests.find(c=>c.chest.item==='garden-keystone');go(G,box.x,box.y);G.world.checkTriggers(.5);r.drain();draw();assert.ok(draws.some(d=>d.s===S.cache&&d.f===1));assert.equal(G.state.items.filter(i=>i==='garden-keystone').length,1);r.load('hangingGardens');r.drain();draw();assert.ok(draws.some(d=>d.s===S.cache&&d.f===1));
 G.state.wayfinder.posts=[];draw();assert.ok(draws.some(d=>d.s===G.greenfieldScenery.postSleeping));G.activateWayfinderPost('hangingGardens',true);draw();assert.ok(draws.some(d=>d.s===G.greenfieldScenery.postAwake));go(G,45,14);G.world.checkTriggers(.5);assert.equal(G.state.mapId,'rootdeepHollow');r.load('hangingGardens');r.drain();go(G,0,14);G.world.checkTriggers(.5);assert.equal(G.state.mapId,'windscarCanyon');assert.equal(G.drawGardensTile(ctx,{tile:'tree'},1,1,3),false);
});
test('planted arches and trees yield to travellers while both pixel settings keep authored frames and saved geometry',()=>{
 const r=setup(),{G}=r,{ctx,draws}=capture(G),S=G.gardensScenery;G.reducedMotion=true;const saved=JSON.stringify({grid:G.state.grid,items:G.state.items,details:G.state.restorationDetails});
 for(const hd of [true,false]){G.hdPilot=hd;for(const sprite of Object.values(S))for(const frame of G.activeSpriteDefinition(sprite).frames)for(const row of frame)for(const p of row)assert.ok(p==='.'||G.activeSpriteDefinition(sprite).palette[p]);go(G,23,9);draws.length=0;G.world.draw(ctx,{x:0,y:0},10);for(const d of G.openingDrawables(ctx))d.fn();assert.ok(draws.some(d=>d.s===S.arch&&d.alpha<=.35));assert.ok(draws.some(d=>d.s===G.prairieScenery.hearth&&d.f===0));for(const id of Object.keys(S).filter(id=>id!=='raisedStep'))assert.ok(draws.some(d=>d.s===S[id]),id);go(G,12,2);draws.length=0;for(const d of G.openingDrawables(ctx))d.fn();assert.ok(draws.some(d=>d.s===S.topiary&&d.alpha<=.35));assert.ok(draws.filter(d=>d.s===S.topiary).every(d=>d.f===0));assert.equal(ctx.globalAlpha,1);}
 assert.equal(JSON.stringify({grid:G.state.grid,items:G.state.items,details:G.state.restorationDetails}),saved);
});
