const {test}=require('node:test'),assert=require('node:assert/strict'),runtime=require('../tools/lib/classic-runtime.cjs');
function setup(){const r=runtime();r.load('glasswaterDesert');r.drain();r.G.state.enemies=[];r.G.W=736;r.G.H=464;return r;}
function capture(G){const draws=[],stack=[],ctx=new Proxy({globalAlpha:1,measureText:t=>({width:String(t).length*5}),save(){stack.push(this.globalAlpha);},restore(){this.globalAlpha=stack.pop();}},{get:(o,k)=>o[k]??(()=>{}),set:(o,k,v)=>(o[k]=v,true)});G.drawSprite=(c,s,f,x,y)=>draws.push({s,f,x,y,alpha:c.globalAlpha});return {ctx,draws};}
const go=(G,x,y)=>Object.assign(G.state.player,{x:x*16+8,y:y*16+8});
test('fitted sundial and meridian slabs follow real alignment while the south gate still requires its own Lantern Mark',()=>{
 const r=setup(),{G}=r,{ctx,draws}=capture(G),S=G.glasswaterScenery,draw=()=>{draws.length=0;G.world.draw(ctx,{x:0,y:0},3);for(const d of G.openingDrawables(ctx))d.fn();};draw();assert.ok(draws.some(d=>d.s===S.sundial&&d.f===0));assert.equal(draws.filter(d=>d.s===S.meridianStone&&d.f===0).length,5);assert.ok(draws.some(d=>d.s===S.lanternGate&&d.f===0));assert.equal(draws.filter(d=>d.s===S.meridianSlab).length,0);
 go(G,23,6);G.tryOpeningInteraction();r.drain();assert.equal(G.glasswaterSurvey().aligned,false);const cache=G.state.chests.find(c=>c.chest.item==='glasswater-prism');go(G,cache.x,cache.y);G.world.checkTriggers(.5);r.drain();require('./helpers/collect-treasure.cjs')(r,'glasswater-prism');draw();assert.ok(draws.some(d=>d.s===S.cache&&d.f===1));assert.equal(G.state.items.filter(i=>i==='glasswater-prism').length,1);go(G,23,6);const spirit=G.ensureTown().spirit;G.tryOpeningInteraction();r.drain();assert.equal(G.ensureTown().spirit,spirit+6);assert.equal(G.glasswaterSurvey().prism,true);const saved=JSON.stringify({grid:G.state.grid,items:G.state.items,world:G.state.worldwake,spirit:G.ensureTown().spirit});draw();assert.ok(draws.some(d=>d.s===S.sundial&&d.f===1));assert.equal(draws.filter(d=>d.s===S.meridianStone&&d.f===1).length,5);assert.equal(draws.filter(d=>d.s===S.meridianSlab).length,6);assert.ok(draws.some(d=>d.s===S.lanternGate&&d.f===0));assert.match(G.world.portalBlockReason(G.state.grid[28][23]).text,/Lantern Mark/);assert.equal(JSON.stringify({grid:G.state.grid,items:G.state.items,world:G.state.worldwake,spirit:G.ensureTown().spirit}),saved);G.tryOpeningInteraction();assert.equal(G.ensureTown().spirit,spirit+6);assert.equal(G.maps.glasswaterDesert.tiles[19][23],'r');
 r.load('glasswaterDesert');r.drain();draw();assert.equal(draws.filter(d=>d.s===S.meridianSlab).length,6);assert.equal(G.world.solid(376,312),false);assert.ok(draws.some(d=>d.s===S.cache&&d.f===1));go(G,23,28);G.world.checkTriggers(.5);r.drain();assert.equal(G.state.mapId,'glasswaterDesert');G.ensureWorldwake().marks.push('light');draw();assert.ok(draws.some(d=>d.s===S.lanternGate&&d.f===1));assert.equal(G.world.portalBlockReason(G.state.grid[28][23]),null);go(G,23,28);G.world.checkTriggers(.5);r.drain();assert.equal(G.state.mapId,'titanGrave');r.load('glasswaterDesert');r.drain();go(G,0,14);G.world.checkTriggers(.5);r.drain();assert.equal(G.state.mapId,'rootdeepHollow');
});
test('sand, glass shelves and fitted props preserve recovery, atlas and collision in both pixel settings, with fins yielding to travellers',()=>{
 const r=setup(),{G}=r,{ctx,draws}=capture(G),S=G.glasswaterScenery;G.reducedMotion=true;go(G,13,2);const saved=JSON.stringify({grid:G.state.grid,items:G.state.items,world:G.state.worldwake});for(const hd of [true,false]){G.hdPilot=hd;draws.length=0;G.world.draw(ctx,{x:0,y:0},10);for(const d of G.openingDrawables(ctx))d.fn();for(const id of Object.keys(S).filter(id=>id!=='meridianSlab'))assert.ok(draws.some(d=>d.s===S[id]),id);assert.ok(draws.some(d=>d.s===S.glassFin&&d.alpha<=.35));assert.ok(draws.filter(d=>d.s===S.glassFin).every(d=>d.f===0));assert.ok(draws.some(d=>d.s===G.prairieScenery.hearth&&d.f===0));assert.ok(draws.some(d=>d.s===G.prairieScenery.fencePost));assert.equal(ctx.globalAlpha,1);for(const sprite of Object.values(S))for(const frame of G.activeSpriteDefinition(sprite).frames)for(const row of frame)for(const p of row)assert.ok(p==='.'||G.activeSpriteDefinition(sprite).palette[p]);}assert.equal(JSON.stringify({grid:G.state.grid,items:G.state.items,world:G.state.worldwake}),saved);assert.ok(G.world.solid(216,72));assert.equal(G.world.solid(376,120),false);
 go(G,7,20);Object.assign(G.state.player,{damageTaken:2,mana:0});G.world.checkTriggers(.5);assert.equal(G.state.player.damageTaken,0);assert.equal(G.state.player.mana,G.playerMaxMana());G.state.wayfinder.posts=[];draws.length=0;G.world.draw(ctx,{x:0,y:0},3);assert.ok(draws.some(d=>d.s===G.greenfieldScenery.postSleeping));G.activateWayfinderPost('glasswaterDesert',true);draws.length=0;G.world.draw(ctx,{x:0,y:0},3);assert.ok(draws.some(d=>d.s===G.greenfieldScenery.postAwake));r.load('rootdeepHollow');r.drain();assert.equal(G.drawGlasswaterTile(ctx,{tile:'rock'},1,1),false);
});
