const {test}=require('node:test'),assert=require('node:assert/strict'),runtime=require('../tools/lib/classic-runtime.cjs');
function capture(G){const draws=[],stack=[],ctx=new Proxy({globalAlpha:1,measureText:t=>({width:String(t).length*5}),save(){stack.push(this.globalAlpha);},restore(){this.globalAlpha=stack.pop();}},{get:(o,k)=>o[k]??(()=>{}),set:(o,k,v)=>(o[k]=v,true)});G.drawSprite=(c,s,f)=>draws.push({s,f});return {ctx,draws};}
test('Greenfield scenery preserves native locked exits, pond crossings and rock collision in both pixel settings',()=>{
  const r=runtime(),{G}=r;r.load('overworld');r.drain();const {ctx,draws}=capture(G),S=G.greenfieldScenery,grid=JSON.stringify(G.state.grid);G.state.stars=0;const dungeon=G.state.grid[0][60],reason=JSON.stringify(G.world.portalBlockReason(dungeon));assert.ok(G.world.solid(968,8));assert.ok(G.world.solid(1192,296));assert.ok(G.world.solid(264,456));assert.ok(!G.world.solid(264,488),'the existing grass passage across the pond remains clear');
  for(const hd of [true,false]){G.hdPilot=hd;G.reducedMotion=true;draws.length=0;G.world.draw(ctx,{x:832,y:0},3);assert.ok(draws.some(d=>d.s===S.dungeonGate&&d.f===1));G.world.draw(ctx,{x:1040,y:210},3);assert.ok(draws.some(d=>d.s===S.rock));for(const sprite of Object.values(S))for(const frame of G.activeSpriteDefinition(sprite).frames)for(const row of frame)for(const p of row)assert.ok(p==='.'||G.activeSpriteDefinition(sprite).palette[p]);}
  assert.equal(JSON.stringify(G.world.portalBlockReason(dungeon)),reason);G.state.stars=3;draws.length=0;G.world.draw(ctx,{x:832,y:0},30);assert.ok(draws.some(d=>d.s===S.dungeonGate&&d.f===0));assert.ok(!G.world.solid(968,8));Object.assign(G.state.player,{x:968,y:8});G.world.checkTriggers(.5);assert.equal(G.state.mapId,'dungeon','the new stone entrance travels through the actual native portal');
  r.load('overworld');assert.equal(JSON.stringify(G.state.grid),grid);r.load('town');assert.equal(G.drawGreenfieldTile(ctx,{tile:'water'},1,1,3),false);assert.equal(G.greenfieldWaterColors(),null);assert.equal(G.drawGreenfieldPortal(ctx,{portal:{map:'dungeon'}},1,1,false),false);
});
test('the atlas post and picnic hamper follow real activation and renewable serving state without granting rewards while drawing',()=>{
  const r=runtime(),{G}=r;r.load('overworld');r.drain();const {ctx,draws}=capture(G),S=G.greenfieldScenery;G.state.wayfinder.posts=[];G.world.draw(ctx,{x:820,y:640},3);assert.ok(draws.some(d=>d.s===S.postSleeping));assert.equal(G.activateWayfinderPost('overworld',true),true);draws.length=0;const journal=JSON.stringify(G.state.wayfinder);G.world.draw(ctx,{x:820,y:640},3);assert.ok(draws.some(d=>d.s===S.postAwake));assert.equal(JSON.stringify(G.state.wayfinder),journal);
  const ch=G.state.chests.find(c=>c.food);G.drawGreenfieldPantry(ctx,ch);assert.equal(draws.pop().s,G.homeScenery.pantryReady);Object.assign(G.state.player,{x:ch.x*16+8,y:ch.y*16+8,damageTaken:2});G.world.checkTriggers(.5);assert.equal(G.state.player.damageTaken,0);assert.equal(G.state.pantries[ch.key].servings,1);G.drawGreenfieldPantry(ctx,ch);assert.equal(draws.pop().s,G.homeScenery.pantryEmpty);const record=JSON.stringify(G.state.pantries);
  G.reducedMotion=true;G.world.draw(ctx,{x:240,y:820},30);assert.equal(JSON.stringify(G.state.pantries),record);r.load('overworld');assert.ok(G.state.chests.find(c=>c.food).opened,'returning early cannot refill the hamper');assert.equal(G.state.pantries[ch.key].servings,1);
});
