const {test}=require('node:test'),assert=require('node:assert/strict'),runtime=require('../tools/lib/classic-runtime.cjs');
const collect=require('./helpers/collect-treasure.cjs');
function capture(G){const draws=[],stack=[],ctx=new Proxy({globalAlpha:1,measureText:t=>({width:String(t).length*5}),save(){stack.push(this.globalAlpha);},restore(){this.globalAlpha=stack.pop();}},{get:(o,k)=>o[k]??(()=>{}),set:(o,k,v)=>(o[k]=v,true)});G.drawSprite=(c,s,f,x,y)=>draws.push({s,f,x,y,alpha:c.globalAlpha});return {ctx,draws};}
test('the authored seed cache, carved stump and shelter follow real pickup and planting without duplicating recovery or saved rewards',()=>{
 const r=runtime(),{G}=r;r.load('whispering-grove');r.drain();G.state.enemies=[];G.W=480;G.H=288;const {ctx,draws}=capture(G),S=G.groveScenery,spirit=G.ensureTown().spirit;const draw=()=>{draws.length=0;G.world.draw(ctx,{x:0,y:0},3);for(const d of G.openingDrawables(ctx))d.fn();};
 draw();assert.ok(draws.some(d=>d.s===S.seedBox&&d.f===0));assert.ok(draws.some(d=>d.s===S.stump));Object.assign(G.state.player,{x:88,y:232});G.tryOpeningInteraction();r.drain();assert.equal(G.groveSurvey().planted,false);assert.ok(G.world.solid(232,136));
 const box=G.state.chests.find(c=>c.chest.item==='whispering-seed');Object.assign(G.state.player,{x:box.x*16+8,y:box.y*16+8});G.world.checkTriggers(.5);r.drain();assert.ok(box.opened);assert.equal(G.groveSurvey().seed,false);collect(r,'whispering-seed');assert.equal(G.groveSurvey().seed,true);draw();assert.ok(draws.some(d=>d.s===S.seedBox&&d.f===1));
 Object.assign(G.state.player,{x:88,y:232,damageTaken:2,mana:0});G.tryOpeningInteraction();r.drain();assert.equal(G.groveSurvey().planted,true);assert.equal(G.ensureTown().spirit,spirit);assert.equal(G.state.player.damageTaken,0);assert.equal(G.state.player.mana,G.playerMaxMana());for(const y of [8,9])assert.equal(G.world.solid(232,y*16+8),false);draw();assert.ok(draws.some(d=>d.s===S.shelterTree&&d.x===88));assert.equal(draws.filter(d=>d.s===S.flower).length,7);assert.ok(!draws.some(d=>d.s===S.stump));const saved=JSON.stringify(G.state.items);draw();G.tryOpeningInteraction();assert.equal(JSON.stringify(G.state.items),saved);assert.equal(G.ensureTown().spirit,spirit);collect(r,'grove-home-tree');assert.equal(G.ensureTown().spirit,spirit+6);
 r.load('whispering-grove');r.drain();draw();assert.ok(draws.some(d=>d.s===S.seedBox&&d.f===1));assert.equal(G.groveSurvey().planted,true);assert.equal(G.maps['whispering-grove'].tiles[8][14],'t');
});
test('grove foliage yields around travellers and NPCs with still poses, retaining water, root curtain, pantry, atlas and exit',()=>{
 const r=runtime(),{G}=r;r.load('whispering-grove');r.drain();G.W=480;G.H=288;G.reducedMotion=true;const {ctx,draws}=capture(G),S=G.groveScenery,grid=JSON.stringify(G.state.grid),items=JSON.stringify(G.state.items);Object.assign(G.state.player,{x:152,y:245});
 for(const hd of [true,false]){G.hdPilot=hd;draws.length=0;G.world.draw(ctx,{x:0,y:0},3);for(const d of G.openingDrawables(ctx))d.fn();assert.ok(draws.some(d=>d.s===S.shelterTree&&d.x===152&&d.alpha<=.35));assert.ok(draws.filter(d=>d.s===S.shelterTree).every(d=>d.f===0));assert.ok(draws.some(d=>d.s===S.hedge));assert.ok(draws.some(d=>d.s===S.notice));assert.ok(draws.some(d=>d.s===S.returnStep));assert.equal(ctx.globalAlpha,1);for(const sprite of Object.values(S))for(const frame of G.activeSpriteDefinition(sprite).frames)for(const row of frame)for(const p of row)assert.ok(p==='.'||G.activeSpriteDefinition(sprite).palette[p]);}
 Object.assign(G.state.player,{x:328,y:24});G.state.npcs=[{x:152,y:245}];draws.length=0;for(const d of G.openingDrawables(ctx))d.fn();assert.ok(draws.some(d=>d.s===S.shelterTree&&d.x===152&&d.alpha<=.35));assert.equal(JSON.stringify(G.state.grid),grid);assert.equal(JSON.stringify(G.state.items),items);assert.ok(G.world.solid(88,72));assert.ok(G.world.solid(232,136));assert.equal(G.world.solid(232,72),false);
 G.state.wayfinder.posts=[];draws.length=0;G.world.draw(ctx,{x:0,y:0},3);assert.ok(draws.some(d=>d.s===G.greenfieldScenery.postSleeping));G.activateWayfinderPost('whispering-grove',true);draws.length=0;G.world.draw(ctx,{x:0,y:0},3);assert.ok(draws.some(d=>d.s===G.greenfieldScenery.postAwake));const ch=G.state.chests.find(c=>c.food);G.drawGrovePantry(ctx,ch);assert.equal(draws.pop().s,G.homeScenery.pantryReady);Object.assign(G.state.player,{x:ch.x*16+8,y:ch.y*16+8,damageTaken:2});G.world.checkTriggers(.5);assert.equal(G.state.pantries[ch.key].servings,1);G.drawGrovePantry(ctx,ch);assert.equal(draws.pop().s,G.homeScenery.pantryEmpty);const pantry=JSON.stringify(G.state.pantries);r.load('whispering-grove');assert.equal(JSON.stringify(G.state.pantries),pantry);Object.assign(G.state.player,{x:328,y:8});G.world.checkTriggers(.5);assert.equal(G.state.mapId,'overworld');assert.equal(G.drawGroveTile(ctx,{tile:'grass'},3,3),false);
});
