const {test}=require('node:test'),assert=require('node:assert/strict'),runtime=require('../tools/lib/classic-runtime.cjs');
function capture(G){const draws=[],stack=[],ctx=new Proxy({globalAlpha:1,measureText:t=>({width:String(t).length*5}),save(){stack.push(this.globalAlpha);},restore(){this.globalAlpha=stack.pop();}},{get:(o,k)=>o[k]??(()=>{}),set:(o,k,v)=>(o[k]=v,true)});G.drawSprite=(c,s,f,x,y)=>draws.push({sprite:s,frame:f,x,y});return {ctx,draws};}
test('native town building replaces its stake with an authored cottage and rendering preserves saved progress',()=>{
 const r=runtime(),{G}=r;G.state.town.founded=true;G.state.town.spirit=100;r.load('town');r.drain();const {ctx,draws}=capture(G),S=G.homeScenery;G.drawSettlementHomes(ctx);assert.ok(draws.some(d=>d.sprite===S.plot));const cost=G.townHouseCost(),spirit=G.state.town.spirit;
 Object.assign(G.state.player,{x:88,y:40});G.world.checkTriggers(.5);assert.ok(G.state.town.houses.includes('a'));assert.equal(G.state.town.spirit,spirit-cost);draws.length=0;const progress=JSON.stringify(G.state.town),grid=JSON.stringify(G.state.grid);G.world.draw(ctx,{x:0,y:0},3);assert.ok(draws.some(d=>d.sprite===S.cottage0));const home=draws.find(d=>d.sprite===S.home);assert.equal(home.x,240);assert.equal(home.y,64);assert.equal(home.x-G.spriteMetrics(S.home).w/2+56/2,232,'authored off-centre door aligns with the real portal');assert.equal(JSON.stringify(G.state.town),progress);assert.equal(JSON.stringify(G.state.grid),grid);
 for(const hd of [true,false]){G.hdPilot=hd;for(const sprite of Object.values(S)){const s=G.activeSpriteDefinition(sprite);for(const frame of s.frames)for(const row of frame)for(const p of row)assert.ok(p==='.'||s.palette[p]);}}
});
test('the furnished home keeps real bed rest, renewable cookies, collision and the native exit',()=>{
 const r=runtime(),{G}=r;r.load('playerHouse');r.drain();const p=G.state.player,{ctx,draws}=capture(G),S=G.homeScenery;Object.assign(p,{x:56,y:40,damageTaken:3,mana:0});G.world.checkTriggers(.5);assert.equal(p.damageTaken,0);assert.equal(p.mana,p.manaMax);
 assert.ok(G.world.solid(88,72));assert.ok(G.world.solid(168,72));assert.ok(!G.world.solid(120,88));const ch=G.state.chests.find(c=>c.food);G.drawHomePantry(ctx,ch,0);assert.equal(draws.pop().sprite,S.pantryReady);Object.assign(p,{x:184,y:40,damageTaken:2});G.world.checkTriggers(.5);assert.equal(G.state.pantries[ch.key].servings,1);assert.equal(p.damageTaken,0);G.drawHomePantry(ctx,ch,0);assert.equal(draws.pop().sprite,S.pantryEmpty);
 const grid=JSON.stringify(G.state.grid),pantries=JSON.stringify(G.state.pantries);G.reducedMotion=true;G.world.draw(ctx,{x:0,y:0},8);for(const id of ['bed','desk','shelf','rug','window','doorMat'])assert.ok(draws.some(d=>d.sprite===S[id]));assert.ok(draws.every(d=>d.frame===0));assert.equal(JSON.stringify(G.state.grid),grid);assert.equal(JSON.stringify(G.state.pantries),pantries);
 Object.assign(p,{x:120,y:104});G.world.checkTriggers(.5);assert.equal(G.state.mapId,'town');assert.equal(G.state.pantries[ch.key].servings,1);r.load('playerHouse');assert.equal(G.state.chests.find(c=>c.food).opened,true,'a return home cannot refill the pantry early');
});

