const {test}=require('node:test'),assert=require('node:assert/strict'),runtime=require('../tools/lib/classic-runtime.cjs');
const collect=require('./helpers/collect-treasure.cjs');
function capture(G){const draws=[],stack=[],ctx=new Proxy({globalAlpha:1,measureText:t=>({width:String(t).length*5}),save(){stack.push(this.globalAlpha);},restore(){this.globalAlpha=stack.pop();}},{get:(o,k)=>o[k]??(()=>{}),set:(o,k,v)=>(o[k]=v,true)});G.drawSprite=(c,s,f,x,y)=>draws.push({s,f,x,y,alpha:c.globalAlpha});return {ctx,draws};}
const stops=[['sluice','marsh-north-sluice',15,3],['sluice','marsh-south-sluice',15,15],['salvageWreck','marsh-ferry-token',3,3]];
test('Marsh art follows native sluice and Rat salvage progress without creating ward damage or repeat rewards',()=>{
 const r=runtime(),{G}=r;r.load('sunkenMarsh');r.drain();const queen=G.state.enemies.find(e=>e.id==='mireQueen');G.state.enemies=[queen];const {ctx,draws}=capture(G),S=G.marshScenery,spirit=G.ensureTown().spirit;
 for(const hd of [true,false]){G.hdPilot=hd;draws.length=0;for(const d of G.openingDrawables(ctx))d.fn();assert.equal(draws.filter(d=>d.s===S.sluice&&d.f===0).length,2);assert.ok(draws.some(d=>d.s===S.salvageWreck&&d.f===0));assert.equal(queen.ward.hp,5);assert.equal(G.marshSurvey().sluices,0);}
 for(const [id,item,x,y]of stops){Object.assign(G.state.player,{x:x*16+8,y:y*16+8});if(id==='salvageWreck'){G.tryOpeningInteraction();r.drain();assert.equal(G.marshSurvey().salvage,false);G.state.formId='rat';}assert.equal(G.tryOpeningInteraction(),true);r.drain();assert.ok(G.groundRewardFor(item));assert.ok(!G.state.items.includes(item));const record=JSON.stringify(G.state.items),ward=queen.ward.hp;draws.length=0;for(const d of G.openingDrawables(ctx))d.fn();assert.ok(draws.some(d=>d.s===S[id]&&d.f===1));assert.equal(JSON.stringify(G.state.items),record);assert.equal(queen.ward.hp,ward);collect(r,item);}
 assert.equal(queen.ward.hp,3);assert.equal(G.ensureTown().spirit,spirit+10);G.tryOpeningInteraction();r.drain();assert.equal(G.ensureTown().spirit,spirit+10);r.load('sunkenMarsh');r.drain();assert.equal(G.marshSurvey().sluices,2);assert.equal(G.marshSurvey().salvage,true);assert.equal(G.state.enemies.find(e=>e.id==='mireQueen').ward.hp,3);
});
test('wetland rendering retains native terrain, collisions, stations and reduced-motion yielding canopies in both pixel settings',()=>{
 const r=runtime(),{G}=r;r.load('sunkenMarsh');r.drain();const {ctx,draws}=capture(G),S=G.marshScenery,grid=JSON.stringify(G.state.grid),items=JSON.stringify(G.state.items);G.W=480;G.H=304;G.reducedMotion=true;Object.assign(G.state.player,{x:8,y:50});
 for(const hd of [true,false]){G.hdPilot=hd;draws.length=0;G.world.draw(ctx,{x:0,y:0},3);for(const d of G.openingDrawables(ctx))d.fn();assert.ok(draws.some(d=>d.s===G.deliveryScenery.willow&&d.x===8&&d.alpha<=.35));assert.ok(draws.filter(d=>d.s===G.deliveryScenery.willow).every(d=>d.f===0));assert.ok(draws.some(d=>d.s===S.lily));assert.ok(draws.some(d=>d.s===S.fencePost));assert.ok(draws.some(d=>d.s===S.wetStep));assert.equal(ctx.globalAlpha,1);for(const sprite of Object.values(S))for(const frame of G.activeSpriteDefinition(sprite).frames)for(const row of frame)for(const p of row)assert.ok(p==='.'||G.activeSpriteDefinition(sprite).palette[p]);}
 Object.assign(G.state.player,{x:248,y:280});G.state.npcs=[{x:8,y:50}];draws.length=0;for(const d of G.openingDrawables(ctx))d.fn();assert.ok(draws.some(d=>d.s===G.deliveryScenery.willow&&d.x===8&&d.alpha<=.35));assert.equal(JSON.stringify(G.state.grid),grid);assert.equal(JSON.stringify(G.state.items),items);assert.ok(G.world.solid(88,88));assert.equal(G.world.solid(248,88),false);
 const pantry=G.state.chests.find(c=>c.food);G.drawMarshPantry(ctx,pantry);assert.equal(draws.pop().s,G.homeScenery.pantryReady);Object.assign(G.state.player,{x:pantry.x*16+8,y:pantry.y*16+8,damageTaken:2});G.world.checkTriggers(.5);assert.equal(G.state.pantries[pantry.key].servings,1);G.drawMarshPantry(ctx,pantry);assert.equal(draws.pop().s,G.homeScenery.pantryEmpty);const served=JSON.stringify(G.state.pantries);r.load('sunkenMarsh');assert.equal(JSON.stringify(G.state.pantries),served);G.state.wayfinder.posts=[];draws.length=0;G.world.draw(ctx,{x:0,y:0},3);assert.ok(draws.some(d=>d.s===G.greenfieldScenery.postSleeping));G.activateWayfinderPost('sunkenMarsh',true);draws.length=0;G.world.draw(ctx,{x:0,y:0},3);assert.ok(draws.some(d=>d.s===G.greenfieldScenery.postAwake));
});
test('regional entrance focus clears the Marsh return gate in desktop and touch HUDs, restores cards away and preserves native travel',()=>{
 const r=runtime(),{G}=r;r.load('sunkenMarsh');r.drain();
 // Isolate entrance/restoration: nearby live foes independently make optional cards yield.
 G.state.enemies=[];r.run('js/engine/ui.js');const c=r.nodes.get('ui').getContext('2d'),labels=[];c.fillText=t=>labels.push(String(t));G.drawGuidanceHud=()=>labels.push('NAVIGATION CHIP');
 for(const touch of [false,true]){G.input.isTouch=touch;Object.assign(G.state.player,{x:440,y:152});assert.equal(G.world.nearPortal(),true);assert.equal(G.nearGreenfieldEntrance(),false);labels.length=0;G.ui.drawHUD({x:160,y:62});assert.ok(!labels.some(t=>/Sunken Marsh|SUNKEN MARSH|NAVIGATION CHIP/.test(t)));assert.ok(labels.some(t=>/Patchling/.test(t)));Object.assign(G.state.player,{x:360,y:152});assert.equal(G.world.nearPortal(),false);labels.length=0;G.ui.drawHUD({x:160,y:62});assert.ok(labels.some(t=>/Sunken Marsh|SUNKEN MARSH/.test(t)));assert.ok(labels.includes('NAVIGATION CHIP'));}
 Object.assign(G.state.player,{x:472,y:152});G.world.checkTriggers(.5);assert.equal(G.state.mapId,'overworld');assert.equal(G.drawMarshTile(c,{tile:'grass'},3,3),false);
});
