const {test}=require('node:test'),assert=require('node:assert/strict'),runtime=require('../tools/lib/classic-runtime.cjs');
function capture(G){const draws=[],stack=[],ctx=new Proxy({globalAlpha:1,measureText:t=>({width:String(t).length*5}),save(){stack.push(this.globalAlpha);},restore(){this.globalAlpha=stack.pop();}},{get:(o,k)=>o[k]??(()=>{}),set:(o,k,v)=>(o[k]=v,true)});G.drawSprite=(c,s,f,x,y)=>draws.push({s,f,x,y,alpha:c.globalAlpha});return {ctx,draws};}
test('Mistwood bells render real restored states while the shortcut and spirit reward remain one-time native progression',()=>{
 const r=runtime(),{G}=r;r.load('mistwood');r.drain();G.state.enemies=[];const {ctx,draws}=capture(G),S=G.mistwoodScenery,spirit=G.ensureTown().spirit;
 const bells=[['fernBell',6,5],['mothBell',23,5],['rootBell',7,13]];
 for(const hd of [true,false]){G.hdPilot=hd;draws.length=0;for(const d of G.openingDrawables(ctx))d.fn();for(const [id]of bells)assert.ok(draws.some(d=>d.s===S[id]&&d.f===0));}
 for(const [id,x,y]of bells){Object.assign(G.state.player,{x:x*16+8,y:y*16+8});assert.equal(G.tryOpeningInteraction(),true);r.drain();draws.length=0;const items=JSON.stringify(G.state.items);for(const d of G.openingDrawables(ctx))d.fn();assert.ok(draws.some(d=>d.s===S[id]&&d.f===1));assert.equal(JSON.stringify(G.state.items),items);}
 assert.equal(G.mistwoodSurvey().open,true);assert.equal(G.ensureTown().spirit,spirit+6);assert.ok(!G.world.solid(232,152));assert.ok(!G.world.solid(232,168));G.tryOpeningInteraction();assert.equal(G.ensureTown().spirit,spirit+6);r.load('mistwood');r.drain();assert.equal(G.mistwoodSurvey().bells,3);assert.equal(G.maps.mistwood.tiles[9][14],'t');
});
test('authored woodland canopies yield around travellers and NPCs without touching collision, travel, pantry or post state',()=>{
 const r=runtime(),{G}=r;r.load('mistwood');r.drain();const {ctx,draws}=capture(G),S=G.mistwoodScenery,grid=JSON.stringify(G.state.grid),items=JSON.stringify(G.state.items);G.reducedMotion=true;
 Object.assign(G.state.player,{x:56,y:40});for(const hd of [true,false]){G.hdPilot=hd;draws.length=0;G.world.draw(ctx,{x:0,y:0},3);for(const d of G.openingDrawables(ctx))d.fn();assert.ok(draws.some(d=>d.s===S.tree&&d.x===56&&d.alpha<=.35));assert.ok(draws.filter(d=>d.s===S.tree).every(d=>d.f===0));assert.equal(ctx.globalAlpha,1);assert.ok(G.world.solid(56,56));assert.ok(G.world.solid(232,152));for(const sprite of Object.values(S))for(const frame of G.activeSpriteDefinition(sprite).frames)for(const row of frame)for(const p of row)assert.ok(p==='.'||G.activeSpriteDefinition(sprite).palette[p]);}
 Object.assign(G.state.player,{x:264,y:280});G.state.npcs=[{x:56,y:40}];draws.length=0;for(const d of G.openingDrawables(ctx))d.fn();assert.ok(draws.some(d=>d.s===S.tree&&d.x===56&&d.alpha<=.35));assert.equal(JSON.stringify(G.state.grid),grid);assert.equal(JSON.stringify(G.state.items),items);
 G.state.wayfinder.posts=[];draws.length=0;G.world.draw(ctx,{x:0,y:0},30);assert.ok(draws.some(d=>d.s===G.greenfieldScenery.postSleeping));G.activateWayfinderPost('mistwood',true);const journal=JSON.stringify(G.state.wayfinder);draws.length=0;G.world.draw(ctx,{x:0,y:0},30);assert.ok(draws.some(d=>d.s===G.greenfieldScenery.postAwake));assert.equal(JSON.stringify(G.state.wayfinder),journal);
 const ch=G.state.chests.find(c=>c.food);G.drawMistwoodPantry(ctx,ch);assert.equal(draws.pop().s,G.homeScenery.pantryReady);Object.assign(G.state.player,{x:ch.x*16+8,y:ch.y*16+8,damageTaken:2});G.world.checkTriggers(.5);assert.equal(G.state.pantries[ch.key].servings,1);G.drawMistwoodPantry(ctx,ch);assert.equal(draws.pop().s,G.homeScenery.pantryEmpty);const pantry=JSON.stringify(G.state.pantries);r.load('mistwood');assert.ok(G.state.chests.find(c=>c.food).opened);assert.equal(JSON.stringify(G.state.pantries),pantry);
 Object.assign(G.state.player,{x:232,y:296});G.world.checkTriggers(.5);assert.equal(G.state.mapId,'overworld');assert.equal(G.drawMistwoodTile(ctx,{tile:'grass'},3,3),false);
});

test('boss combat keeps its warnings clear of mastery cards and ambient chatter, restoring them after victory in both HUD layouts',()=>{
 const r=runtime(),{G}=r;r.load('mistwood');r.drain();r.run('js/engine/ui.js');const c=r.nodes.get('ui').getContext('2d'),labels=[];c.fillText=t=>labels.push(String(t));const boss=G.state.enemies.find(e=>e.def.id==='ancientTreant');G.state.enemies=[boss];Object.assign(G.state.player,{x:boss.x-40,y:boss.y-16});G.fieldMasteryQuest=()=>({form:G.forms.nobody,quest:G.forms.nobody.quests[0],progress:0,slot:0});G.state.npcs=[{x:G.state.player.x,y:G.state.player.y-20,def:{name:'Friendly traveller'},bubble:{text:'ROAD CHATTER',delay:0,t:2,duration:2}}];
 for(const touch of [false,true]){G.input.isTouch=touch;boss.dead=false;boss.bossEngaged=true;labels.length=0;G.ui.drawHUD({x:160,y:124});assert.ok(labels.some(t=>/ANCIENT TREANT/.test(t)));assert.ok(labels.some(t=>/Patchling/.test(t)));assert.ok(!labels.some(t=>/MASTERY|ROAD CHATTER|FRIENDLY TRAVELLER/.test(t)));boss.dead=true;labels.length=0;G.ui.drawHUD({x:160,y:124});assert.ok(labels.some(t=>/MASTERY/.test(t)));assert.ok(labels.includes('ROAD CHATTER'));}
});
