const {test}=require('node:test'),assert=require('node:assert/strict'),runtime=require('../tools/lib/classic-runtime.cjs');
test('incidental NPC speech yields over the traveller including its tail and returns when clear, in keyboard, touch and controller HUDs',()=>{
 const r=runtime(),{G}=r;r.load('frostbellTundra');r.drain();r.run('js/engine/ui.js');G.state.enemies=[];G.state.bossCutscene=null;const c=r.nodes.get('ui').getContext('2d'),labels=[];c.fillText=t=>labels.push(String(t));G.state.npcs=[{x:120,y:168,def:{name:'Road friend'},bubble:{text:'CLEAR ROAD',delay:0,t:2,duration:2}}];const bubble=G.state.npcs[0].bubble,cam={x:0,y:0};
 for(const mode of ['keyboard','touch','controller'])for(const form of ['nobody','dragon']){G.input.isTouch=mode==='touch';G.input.hasGamepad=mode==='controller';G.state.formId=form;Object.assign(G.state.player,{x:120,y:136});labels.length=0;G.ui.update(.01);G.ui.update(.7);G.ui.drawHUD(cam);assert.ok(!labels.includes('CLEAR ROAD'),'the bubble covers the actual sprite');Object.assign(G.state.player,{x:120,y:146+Math.max(28,G.spriteMetrics(G.forms[form].sprite).h)+2});labels.length=0;G.ui.update(.01);G.ui.update(.7);G.ui.drawHUD(cam);assert.ok(!labels.includes('CLEAR ROAD'),'the tail can cover the head even when the panel clears its feet');Object.assign(G.state.player,{x:40,y:136});labels.length=0;G.ui.update(.01);G.ui.update(.7);G.ui.drawHUD(cam);assert.ok(labels.includes('CLEAR ROAD'),'unobstructed nearby chatter remains visible');assert.equal(bubble.t,2);}
});

test('authored NPC chatter yields when the top clamp covers its own head and restores in a clear position without changing timers',()=>{
 const r=runtime(),{G}=r;r.load('town');r.drain();r.run('js/engine/ui.js');G.state.enemies=[];G.state.bossCutscene=null;Object.assign(G.state.player,{x:70,y:130});const labels=[],c=r.nodes.get('ui').getContext('2d');c.fillText=t=>labels.push(String(t));
 for(const hd of [true,false])for(const id of ['pebble','parcel','pending','mayorMaybe']){G.hdPilot=hd;const n={x:160,y:70,def:G.NPCS[id],bubble:{text:'CLEAR SPEECH',delay:0,t:2,duration:2}};G.state.npcs=[n];labels.length=0;G.ui.update(.01);G.ui.update(.7);G.ui.drawHUD({x:0,y:0});assert.ok(!labels.includes('CLEAR SPEECH'),'top-clamped speech would hide its speaker');n.y=130;labels.length=0;G.ui.update(.01);G.ui.update(.7);G.ui.drawHUD({x:0,y:0});assert.ok(labels.includes('CLEAR SPEECH'),'clear speech should return');assert.equal(n.bubble.t,2);}
});
