const {test}=require('node:test'),assert=require('node:assert/strict'),runtime=require('../tools/lib/classic-runtime.cjs');
const ids=['orchardTangle','orchardSpitter','orchardGuard'];
const gameplay=d=>JSON.stringify(Object.fromEntries(Object.entries(d).filter(([k])=>k!=='sprite')));
test('orchard bodies preserve native footprints, frames, directional metadata and exact animation cadence independently of playable Knight',()=>{
 const r=runtime(),{G}=r;r.run('js/data/opening-art.js');r.run('js/data/cute-knight-art.js');const old=new Map(ids.map(id=>[id,{sprite:G.enemies[id].sprite,def:gameplay(G.enemies[id])}])),knight=G.forms.knight.sprite;
 r.run('js/data/orchard-foe-art.js');assert.equal(G.forms.knight.sprite,knight);assert.notEqual(G.enemies.orchardGuard.sprite,knight);assert.deepEqual(Array.from(G.orchardFoeArtIds),ids);
 for(const hd of [true,false]){G.hdPilot=hd;for(const id of ids){const sprite=G.enemies[id].sprite,before=G.activeSpriteDefinition(old.get(id).sprite),after=G.activeSpriteDefinition(sprite);assert.equal(gameplay(G.enemies[id]),old.get(id).def);assert.deepEqual(JSON.parse(JSON.stringify(G.spriteMetrics(sprite))),JSON.parse(JSON.stringify(G.spriteMetrics(old.get(id).sprite))));assert.equal(after.frames.length,before.frames.length);assert.equal(JSON.stringify(after.animations),JSON.stringify(before.animations));assert.equal(JSON.stringify(sprite.directional),JSON.stringify(old.get(id).sprite.directional));for(const mode of ['idle','walk','attack','guard'])for(let tick=0;tick<10;tick+=.25)assert.equal(G.spriteFrame(sprite,mode,tick),G.spriteFrame(old.get(id).sprite,mode,tick));for(const rows of after.frames)for(const row of rows)for(const pixel of row)assert.ok(pixel==='.'||after.palette[pixel]);}}
});
test('actual watchman keeps committed windup and recovery, and every new orchard body still dies through native combat',()=>{
 const r=runtime(),{G}=r;G.state.opening.complete=true;G.state.delivery.complete=true;r.load('orchardRoad');r.drain();const p=G.state.player,e=G.makeEnemy('orchardGuard',p.x+40,p.y);G.state.enemies=[e];assert.equal(G.updateOpeningEnemy(e,p,0),true);assert.equal(e.openingMode,'windup');assert.equal(e.openingTimer,.75);const aim=JSON.stringify(e.openingAim);p.y+=60;G.updateOpeningEnemy(e,p,.76);assert.equal(e.openingMode,'recover');assert.equal(e.openingTimer,.9);assert.equal(JSON.stringify(e.openingAim),aim);G.updateOpeningEnemy(e,p,.5);assert.equal(e.openingMode,'recover');assert.ok(e.openingTimer>0);
 for(const id of ids){const foe=G.makeEnemy(id,p.x+50,p.y);G.state.enemies=[foe];const before=JSON.stringify(foe);G.drawEnemy(new Proxy({globalAlpha:1,measureText:t=>({width:String(t).length*5})},{get:(o,k)=>o[k]??(()=>{}),set:(o,k,v)=>(o[k]=v,true)}),foe);assert.equal(JSON.stringify(foe),before);G.combat.damageEnemy(foe,{type:'blunt',damage:foe.hp,fromX:foe.x+30,fromY:foe.y,knockback:0});assert.equal(foe.dead,true);}
});
