const {test}=require('node:test'),assert=require('node:assert/strict'),runtime=require('../tools/lib/classic-runtime.cjs');
function setup(){const r=runtime();r.load('sunstepPrairie');r.drain();r.G.state.enemies=[];r.G.W=736;r.G.H=464;return r;}
function capture(G){const draws=[],texts=[],stack=[],ctx=new Proxy({globalAlpha:1,measureText:t=>({width:String(t).length*5}),fillText:t=>texts.push(String(t)),save(){stack.push(this.globalAlpha);},restore(){this.globalAlpha=stack.pop();}},{get:(o,k)=>o[k]??(()=>{}),set:(o,k,v)=>(o[k]=v,true)});G.drawSprite=(c,s,f,x,y)=>draws.push({s,f,x,y,alpha:c.globalAlpha});return {ctx,draws,texts};}
const points=[[12,8],[31,8],[34,20],[11,20]],go=(G,[x,y])=>Object.assign(G.state.player,{x:x*16+8,y:y*16+8});
test('sewn pennants track the actual courier order, resume their resting pose, and keep the saved completed desk',()=>{
 const r=setup(),{G}=r,{ctx,draws,texts}=capture(G),S=G.prairieScenery;G.reducedMotion=true;
 const draw=()=>{draws.length=0;texts.length=0;for(const d of G.openingDrawables(ctx))d.fn();};
 draw();assert.equal(draws.filter(d=>d.s===S.pennant&&d.f===0).length,4);assert.ok(draws.some(d=>d.s===S.desk&&d.f===0));assert.ok(texts.includes('COURIER')&&texts.includes('CAMP SOUTH'));go(G,points[3]);assert.equal(G.tryOpeningInteraction(),true);draw();assert.equal(draws.filter(d=>d.s===S.pennant&&d.f===1).length,1);assert.equal(draws.find(d=>d.s===S.pennant&&d.f===1).x,200);
 go(G,points[0]);G.updateOpening(2);draw();assert.equal(draws.filter(d=>d.s===S.pennant&&d.f===2).length,1);assert.equal(draws.find(d=>d.s===S.pennant&&d.f===1).x,504);const spirit=G.ensureTown().spirit;for(const p of points.slice(1)){go(G,p);G.updateOpening(2);}draw();assert.equal(G.prairieSurvey().best,8);assert.equal(G.ensureTown().spirit,spirit);require('./helpers/collect-treasure.cjs')(r,'sunstep-courier');assert.equal(G.ensureTown().spirit,spirit+6);assert.ok(draws.some(d=>d.s===S.desk&&d.f===1));assert.equal(draws.filter(d=>d.s===S.pennant&&d.f===0).length,4);const saved=JSON.stringify(G.state.items);draw();assert.equal(JSON.stringify(G.state.items),saved);
 r.load('sunstepPrairie');r.drain();G.state.enemies=[];draw();assert.ok(draws.some(d=>d.s===S.desk&&d.f===1));assert.equal(G.prairieSurvey().best,8);go(G,points[3]);G.tryOpeningInteraction();G.updateOpening(46);draw();assert.equal(draws.filter(d=>d.s===S.pennant&&d.f===0).length,4);assert.ok(draws.some(d=>d.s===S.desk&&d.f===1));assert.equal(G.ensureTown().spirit,spirit+6);
});
test('prairie materials, camp, cache and yielding shared trees preserve native collision, recovery and both travel directions',()=>{
 const r=setup(),{G}=r,{ctx,draws}=capture(G),S=G.prairieScenery;G.reducedMotion=true;const draw=()=>{draws.length=0;G.world.draw(ctx,{x:0,y:0},3);for(const d of G.openingDrawables(ctx))d.fn();},grid=JSON.stringify(G.state.grid),items=JSON.stringify(G.state.items);
 go(G,[7,2]);for(const hd of [true,false]){G.hdPilot=hd;draw();for(const id of Object.keys(S))assert.ok(draws.some(d=>d.s===S[id]),id);assert.ok(draws.some(d=>d.s===G.groveScenery.shelterTree&&d.alpha<=.35));assert.ok(draws.filter(d=>d.s===S.hearth).every(d=>d.f===0));assert.equal(ctx.globalAlpha,1);for(const sprite of Object.values(S))for(const frame of G.activeSpriteDefinition(sprite).frames)for(const row of frame)for(const p of row)assert.ok(p==='.'||G.activeSpriteDefinition(sprite).palette[p]);}
 assert.equal(JSON.stringify(G.state.grid),grid);assert.equal(JSON.stringify(G.state.items),items);assert.ok(G.world.solid(120,72));for(const p of points)assert.equal(G.world.isSafeSpawn(p[0]*16+8,p[1]*16+8),true);go(G,[7,20]);Object.assign(G.state.player,{damageTaken:2,mana:0});G.world.checkTriggers(.5);assert.equal(G.state.player.damageTaken,0);assert.equal(G.state.player.mana,G.playerMaxMana());
 const box=G.state.chests.find(c=>c.chest.item==='sunstep-ribbon');go(G,[box.x,box.y]);G.world.checkTriggers(.5);r.drain();require('./helpers/collect-treasure.cjs')(r,'sunstep-ribbon');draw();assert.ok(draws.some(d=>d.s===S.cache&&d.f===1));assert.equal(G.state.items.filter(i=>i==='sunstep-ribbon').length,1);r.load('sunstepPrairie');r.drain();draw();assert.ok(draws.some(d=>d.s===S.cache&&d.f===1));G.state.wayfinder.posts=[];draw();assert.ok(draws.some(d=>d.s===G.greenfieldScenery.postSleeping));G.activateWayfinderPost('sunstepPrairie',true);draw();assert.ok(draws.some(d=>d.s===G.greenfieldScenery.postAwake));
 go(G,[45,14]);G.world.checkTriggers(.5);assert.equal(G.state.mapId,'windscarCanyon');r.load('sunstepPrairie');r.drain();go(G,[0,14]);G.world.checkTriggers(.5);assert.equal(G.state.mapId,'overworld');assert.equal(G.drawPrairieTile(ctx,{tile:'grass'},1,1),false);
});
