const {test}=require('node:test'),assert=require('node:assert/strict'),runtime=require('../tools/lib/classic-runtime.cjs');
function capture(G){const draws=[],stack=[],ctx=new Proxy({globalAlpha:1,measureText:t=>({width:String(t).length*5}),save(){stack.push(this.globalAlpha);},restore(){this.globalAlpha=stack.pop();}},{get:(o,k)=>o[k]??(()=>{}),set:(o,k,v)=>(o[k]=v,true)});G.drawSprite=(c,s,f,x,y)=>draws.push({s,f,x,y,alpha:c.globalAlpha});return {ctx,draws};}
test('authored watchfires stay cold until awakening, show guarded flame during the native fight and restore once after victory',()=>{
 const r=runtime(),{G}=r;r.load('emberRidge');r.drain();G.state.enemies=[];const {ctx,draws}=capture(G),S=G.ridgeScenery,spirit=G.ensureTown().spirit;G.reducedMotion=true;
 const draw=()=>{draws.length=0;for(const d of G.openingDrawables(ctx))d.fn();return draws.filter(d=>d.s===S.watchfire);};
 for(const hd of [true,false]){G.hdPilot=hd;assert.ok(draw().every(d=>d.f===0));assert.equal(G.ridgeSurvey().lit,0);}
 Object.assign(G.state.player,{x:168,y:72});assert.equal(G.tryOpeningInteraction(),true);assert.equal(G.state.enemies.length,2);assert.ok(draw().some(d=>d.f===1));assert.equal(G.ensureTown().spirit,spirit);G.state.enemies[0].dead=true;G.updateOpening(.05);assert.ok(draw().some(d=>d.f===1));assert.equal(G.ridgeSurvey().lit,0);
 G.state.player.damageTaken=2;G.state.player.mana=0;G.state.enemies[1].dead=true;G.updateOpening(.05);assert.ok(draw().some(d=>d.f===2));assert.equal(G.ridgeSurvey().lit,1);assert.equal(G.ensureTown().spirit,spirit+3);assert.equal(G.state.player.damageTaken,0);assert.equal(G.state.player.mana,G.playerMaxMana());const saved=JSON.stringify(G.state.items);draw();assert.equal(JSON.stringify(G.state.items),saved);assert.equal(G.ensureTown().spirit,spirit+3);r.load('emberRidge');r.drain();assert.ok(draw().some(d=>d.f===2));assert.equal(G.ridgeSurvey().lit,1);
});
test('the ash road, basalt boundaries, sewn standards and shared resting places retain native collision and return in both pixel settings',()=>{
 const r=runtime(),{G}=r;r.load('emberRidge');r.drain();G.W=480;G.H=304;const {ctx,draws}=capture(G),S=G.ridgeScenery,grid=JSON.stringify(G.state.grid),items=JSON.stringify(G.state.items);G.reducedMotion=true;
 for(const hd of [true,false]){G.hdPilot=hd;draws.length=0;G.world.draw(ctx,{x:0,y:0},3);for(const d of G.openingDrawables(ctx))d.fn();for(const id of ['basalt','cliff','notice','returnStep','standard'])assert.ok(draws.some(d=>d.s===S[id]),id);assert.equal(draws.filter(d=>d.s===S.standard).length,4);for(const sprite of Object.values(S))for(const frame of G.activeSpriteDefinition(sprite).frames)for(const row of frame)for(const p of row)assert.ok(p==='.'||G.activeSpriteDefinition(sprite).palette[p]);}
 assert.equal(JSON.stringify(G.state.grid),grid);assert.equal(JSON.stringify(G.state.items),items);assert.ok(G.world.solid(88,104));assert.ok(G.world.solid(8,8));assert.equal(G.world.solid(168,72),false);G.state.wayfinder.posts=[];draws.length=0;G.world.draw(ctx,{x:0,y:0},3);assert.ok(draws.some(d=>d.s===G.greenfieldScenery.postSleeping));G.activateWayfinderPost('emberRidge',true);draws.length=0;G.world.draw(ctx,{x:0,y:0},3);assert.ok(draws.some(d=>d.s===G.greenfieldScenery.postAwake));
 const ch=G.state.chests.find(c=>c.food);G.drawRidgePantry(ctx,ch);assert.equal(draws.pop().s,G.homeScenery.pantryReady);Object.assign(G.state.player,{x:ch.x*16+8,y:ch.y*16+8,damageTaken:2});G.world.checkTriggers(.5);assert.equal(G.state.pantries[ch.key].servings,1);G.drawRidgePantry(ctx,ch);assert.equal(draws.pop().s,G.homeScenery.pantryEmpty);const pantry=JSON.stringify(G.state.pantries);r.load('emberRidge');assert.equal(JSON.stringify(G.state.pantries),pantry);Object.assign(G.state.player,{x:8,y:152});G.world.checkTriggers(.5);assert.equal(G.state.mapId,'overworld');assert.equal(G.drawRidgeTile(ctx,{tile:'floor'},3,3),false);
});

test('watchfire encounters keep guards visible beneath both HUD layouts and restore mastery after the actual victory',()=>{
 const r=runtime(),{G}=r;r.load('emberRidge');r.drain();r.run('js/engine/ui.js');const c=r.nodes.get('ui').getContext('2d'),labels=[];c.fillText=t=>labels.push(String(t));G.state.enemies=[];Object.assign(G.state.player,{x:168,y:72});G.tryOpeningInteraction();G.fieldMasteryQuest=()=>({form:G.forms.nobody,quest:G.forms.nobody.quests[0],progress:0,slot:0});
 for(const touch of [false,true]){G.input.isTouch=touch;labels.length=0;G.ui.drawHUD({x:8,y:0});assert.ok(!labels.some(t=>/MASTERY|EMBER RIDGE/.test(t)));assert.ok(labels.some(t=>/Patchling/.test(t)));}
 for(const e of G.state.enemies)e.dead=true;G.updateOpening(.05);for(const touch of [false,true]){G.input.isTouch=touch;labels.length=0;G.ui.drawHUD({x:8,y:0});assert.ok(labels.some(t=>/MASTERY/.test(t)));}assert.equal(G.ridgeSurvey().lit,1);
});
