const {test}=require('node:test'),assert=require('node:assert/strict'),runtime=require('../tools/lib/classic-runtime.cjs');
const ids=['pebble','parcel','pending'];
test('road companions retain native identities and actual talk/save keys with four authored poses in both settings',()=>{
 const r=runtime(),{G}=r,registry=G.NPCS,placements=G.NPC_PLACEMENTS;r.run('js/data/npcs.js');const before=new Map(ids.map(id=>[id,JSON.stringify({name:G.NPCS[id].name,icon:G.NPCS[id].icon,chapters:G.NPCS[id].chapters})]));G.NPCS=registry;G.NPC_PLACEMENTS=placements;r.run('js/data/road-companion-art.js');
 for(const id of ids){const def=G.NPCS[id];assert.equal(JSON.stringify({name:def.name,icon:def.icon,chapters:def.chapters}),before.get(id));assert.equal(def.sprite.integratedEquipment,true);for(const hd of [true,false]){G.hdPilot=hd;const a=G.activeSpriteDefinition(def.sprite);assert.equal(a.frames.length,4);assert.equal(G.spriteMetrics(def.sprite).w,18);assert.equal(G.spriteMetrics(def.sprite).h,22);assert.notDeepEqual(a.frames[0],a.frames[2]);for(const frame of a.frames)for(const row of frame)for(const pixel of row)assert.ok(pixel==='.'||a.palette[pixel]);}}
 G.state.opening.complete=true;G.state.delivery.complete=true;r.load('orchardRoad');r.drain();G.state.enemies=[];G.state.npcArrivalGrace=0;G.state.bossCutscene=null;
 for(const id of ids){const n=G.state.npcs.find(n=>n.id===id);assert.ok(n);const home=JSON.stringify(n.home);Object.assign(G.state.player,{x:n.x+12,y:n.y});assert.equal(G.npcTalkCandidate(),n);const chapter=G.storyChapter(),key=id+':'+chapter,count=G.state.npcTalk[key]||0;assert.equal(G.tryNpcTalk(),true);assert.equal(G.state.npcTalk[key],count+1);assert.equal(JSON.stringify(n.home),home);r.drain();}
 G.saveGame();const save=G.loadSaveData();assert.equal(save.mapId,'orchardRoad');assert.deepEqual(JSON.parse(JSON.stringify(save.npcTalk)),JSON.parse(JSON.stringify(G.state.npcTalk)));
});
test('integrated work poses keep tools in the authored body and talk/guidance clear heads without changing NPC state',()=>{
 const r=runtime(),{G}=r;r.load('orchardRoad');r.drain();G.state.enemies=[];G.state.npcArrivalGrace=0;G.state.bossCutscene=null;
 const draws=[],rects=[],moves=[],ctx=new Proxy({globalAlpha:1,save(){},restore(){},measureText:t=>({width:t.length*5}),fillRect(x,y,w,h){rects.push({x,y,w,h});},translate(x,y){moves.push({x,y});}},{get:(o,k)=>o[k]??(()=>{}),set:(o,k,v)=>(o[k]=v,true)});G.drawSprite=(c,s,f,x,y,flip)=>draws.push({s,f,x,y,flip});
 for(const id of ids)for(const hd of [true,false])for(const left of [false,true])for(const activity of [null,'notes','parcel','polish'])for(const quiet of [false,true]){G.hdPilot=hd;G.reducedMotion=quiet;const n=G.state.npcs.find(n=>n.id===id);Object.assign(n,{x:200,y:150,path:[],anim:.5,facingLeft:left,activity,guidancePoint:true});Object.assign(G.state.player,{x:212,y:150});const before=JSON.stringify(n);draws.length=rects.length=moves.length=0;G.drawNpc(ctx,n);assert.equal(JSON.stringify(n),before);assert.equal(draws[0].s,n.def.sprite);assert.equal(draws[0].flip,left);assert.ok(rects.every(q=>q.h===8||(q.x===-3&&q.y===-3&&q.w===6&&q.h===6)||(q.y>=n.y-3&&q.h<=4)),'only talk/guidance and grounded shadow paint outside the sprite');assert.ok(rects.find(q=>q.h===8).y+8<=n.y-22);assert.ok(moves[0].y+5<=n.y-22);if(quiet){assert.equal(draws[0].f,activity?2:0);assert.equal(draws[0].y,n.y);}}
});
test('actual opening dialogue uses Parcel and Pending aliases instead of an unrelated guardian',()=>{
 const r=runtime(),{G}=r;r.load('orchardRoad');r.drain();const drawn=[],ctx=new Proxy({globalAlpha:1,measureText:t=>({width:t.length*5})},{get:(o,k)=>o[k]??(()=>{}),set:(o,k,v)=>(o[k]=v,true)});G.drawSprite=(c,s)=>drawn.push(s);
 for(const hd of [true,false])for(const [speaker,id]of [['PEBBLE','pebble'],['PARCEL','parcel'],['PARCEL, FROM THE OTHER SIDE','parcel'],['COURIER PARCEL · A RUMOR','parcel'],['SER PENDING','pending'],['! Sir Pending · A Stitch in the Road','pending']]){G.hdPilot=hd;drawn.length=0;assert.equal(G.drawOpeningDialogue(ctx,{speaker,text:'The road is open.',shown:99},(c,t)=>[t]),true);assert.equal(drawn[0],G.NPCS[id].sprite);}
 assert.equal(G.roadCompanionSpeaker('PARCELMAN'),null);
});
