const {test}=require('node:test'),assert=require('node:assert/strict'),runtime=require('../tools/lib/classic-runtime.cjs');
function setup(){const r=runtime(),{G}=r;r.load('overworld');r.drain();G.state.opening.complete=true;G.state.delivery.complete=true;G.state.claimedForms=['rat','knight','ranger'];G.questsDone=['nobody','knight'].flatMap(id=>G.forms[id].quests.map(q=>q.id));G.state.loadouts.nobody=['slap','cartwheel','spinSlash'];assert.ok(G.startManyfoldExpedition(3));r.drain();G.W=448;G.H=272;return r;}
function capture(G){const draws=[],texts=[],stack=[],ctx=new Proxy({globalAlpha:1,measureText:t=>({width:String(t).length*5}),save(){stack.push(this.globalAlpha);},restore(){this.globalAlpha=stack.pop();},fillText(t){texts.push(t);}},{get:(o,k)=>o[k]??(()=>{}),set:(o,k,v)=>(o[k]=v,true)});G.drawSprite=(c,s,f,x,y)=>draws.push({s,f,x,y,alpha:c.globalAlpha});return {ctx,draws,texts};}
function paint(G,ctx){G.world.draw(ctx,{x:0,y:0},3);const props=G.openingDrawables(ctx);for(const d of props)d.fn();return props;}
test('guide stones follow all three actual deterministic chamber layouts and leave every native route connected',()=>{
 const r=setup(),{G}=r,{ctx,draws}=capture(G),S=G.shiftingScenery,run=G.state.expeditionRun;assert.equal(paint(G,ctx).length,7);assert.equal(draws.filter(d=>d.s===S.guideStone).length,4);assert.ok(draws.some(d=>d.s===S.notice));G.chooseExpeditionDraft(0);run.routeChoices=[{id:'skirmish'}];assert.ok(G.chooseExpeditionRoute('skirmish'));const seenLayouts=new Set();for(let seed=1;seed<100&&seenLayouts.size<3;seed++){run.seed=seed;G.resumeManyfoldExpedition();if(seenLayouts.has(run.roomName))continue;seenLayouts.add(run.roomName);const grid=JSON.stringify(G.state.grid),saved=JSON.stringify(run),enemies=JSON.stringify(G.state.enemies),rocks=G.state.grid.flatMap((row,y)=>row.flatMap((cell,x)=>cell.tile==='rock'?[[x,y]]:[]));draws.length=0;assert.equal(paint(G,ctx).length,rocks.length+3);assert.equal(draws.filter(d=>d.s===S.guideStone).length,rocks.length);assert.equal(draws.filter(d=>d.s===S.notice).length,0);assert.equal(JSON.stringify(G.state.grid),grid);assert.equal(JSON.stringify(run),saved);assert.equal(JSON.stringify(G.state.enemies),enemies);G.resumeManyfoldExpedition();assert.equal(JSON.stringify(G.state.grid),grid);const seen=new Set(['6,8']),queue=[[6,8]];for(let i=0;i<queue.length;i++)for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){const x=queue[i][0]+dx,y=queue[i][1]+dy,key=x+','+y;if(seen.has(key)||G.world.solid(x*16+8,y*16+8))continue;seen.add(key);queue.push([x,y]);}for(const e of G.state.enemies)assert.ok(seen.has(Math.floor(e.x/16)+','+Math.floor(e.y/16)));}assert.deepEqual([...seenLayouts].sort(),['Open Crossing','Split Pillars','The Needle']);
});
test('the contained camp hearth follows native healing, while caches and borrowed arts retain their original effects and home restoration',()=>{
 const r=setup(),{G}=r,{ctx,draws,texts}=capture(G),run=G.state.expeditionRun,S=G.shiftingScenery,backup=JSON.stringify(run.backup);G.reducedMotion=true;const frame=()=>{draws.length=0;texts.length=0;paint(G,ctx);return draws.find(d=>d.s===S.hearth).f;};assert.equal(frame(),0);assert.ok(texts.includes('DRAFT'));G.chooseExpeditionDraft(0);assert.equal(frame(),0);assert.ok(texts.includes('ROUTE'));run.routeChoices=[{id:'camp'}];G.state.player.damageTaken=2;G.state.player.mana=1;assert.ok(G.chooseExpeditionRoute('camp'));assert.equal(run.room,1);assert.equal(G.state.player.damageTaken,0);assert.equal(G.state.player.mana,G.playerMaxMana());assert.equal(frame(),1);assert.ok(texts.includes('NEXT 2/3'));const state=JSON.stringify(G.state);frame();assert.equal(JSON.stringify(G.state),state);run.draftOptions=[{kind:'ability',id:'arrow'}];assert.ok(G.chooseExpeditionDraft(0,1));assert.equal(frame(),0);assert.equal(G.getLoadout('nobody')[1],'arrow');run.routeChoices=[{id:'cache'}];G.state.player.damageTaken=2;G.state.player.mana=1;assert.ok(G.chooseExpeditionRoute('cache'));assert.equal(frame(),0);assert.equal(G.state.player.damageTaken,2);assert.equal(G.state.player.mana,1);assert.equal(run.draftOptions.length,4);assert.equal(JSON.stringify(run.backup),backup);assert.ok(G.failManyfoldExpedition(null,true));r.drain();assert.equal(G.state.mapId,'overworld');assert.equal(G.getLoadout('nobody').join(','),'slap,cartwheel,spinSlash');assert.equal(G.state.expeditionRun,null);
});
test('all authored frames work in both settings, guide stones and fittings yield over actors, and other maps retain their art',()=>{
 const r=setup(),{G}=r,{ctx,draws}=capture(G),S=G.shiftingScenery;for(const hd of [true,false]){G.hdPilot=hd;for(const s of Object.values(S))for(const frame of G.activeSpriteDefinition(s).frames)for(const row of frame)for(const px of row)assert.ok(px==='.'||G.activeSpriteDefinition(s).palette[px]);G.state.player.x=72;G.state.player.y=36;draws.length=0;paint(G,ctx);assert.ok(draws.some(d=>d.s===S.guideStone&&d.alpha===.35));G.state.player.x=88;G.state.player.y=136;draws.length=0;paint(G,ctx);assert.ok(draws.some(d=>d.s===S.notice&&d.alpha===.35));G.state.player.x=104;G.state.player.y=136;G.state.npcs=[{x:328,y:24}];draws.length=0;paint(G,ctx);assert.ok(draws.some(d=>d.s===S.trailRack&&d.alpha===.35));assert.equal(ctx.globalAlpha,1);}assert.equal(Object.keys(S).length,6);r.load('overworld');assert.equal(G.drawShiftingTile(ctx,{tile:'floor'},1,1),false);assert.equal(G.drawShiftingNotice(ctx,{message:'test'},1,1),false);
});
