const {test}=require('node:test'),assert=require('node:assert/strict'),runtime=require('../tools/lib/classic-runtime.cjs');
function capture(G){const draws=[],stack=[],ctx=new Proxy({globalAlpha:1,measureText:t=>({width:String(t).length*5}),save(){stack.push(this.globalAlpha);},restore(){this.globalAlpha=stack.pop();}},{get:(o,k)=>o[k]??(()=>{}),set:(o,k,v)=>(o[k]=v,true)});G.drawSprite=(c,s,f,x,y)=>draws.push({s,f,x,y,alpha:c.globalAlpha});return {ctx,draws};}
test('observatory lenses and mounted spindle indicators follow actual alignment and the one-time thread reward',()=>{
 const r=runtime(),{G}=r;r.load('starfallRuins');r.drain();G.state.enemies=[];const {ctx,draws}=capture(G),S=G.starfallScenery,spirit=G.ensureTown().spirit;const draw=()=>{draws.length=0;for(const d of G.openingDrawables(ctx))d.fn();};
 for(const hd of [true,false]){G.hdPilot=hd;draw();for(const id of ['dawnLens','duskLens','midnightLens','starSpindle'])assert.ok(draws.some(d=>d.s===S[id]&&d.f===0));assert.equal(G.starfallSurvey().aligned,0);}
 Object.assign(G.state.player,{x:248,y:248});G.tryOpeningInteraction();r.drain();assert.equal(G.starfallSurvey().thread,false);let picked=0;G.events.on('pickup',e=>{if(e.item==='starfall-thread')picked++;});
 for(const [id,x,y]of [['midnightLens',24,14],['dawnLens',5,5],['duskLens',24,5]]){Object.assign(G.state.player,{x:x*16+8,y:y*16+8});G.tryOpeningInteraction();r.drain();draw();assert.ok(draws.some(d=>d.s===S[id]&&d.f===1));assert.ok(draws.some(d=>d.s===S.starSpindle&&d.f===0));}
 Object.assign(G.state.player,{x:248,y:248,damageTaken:2,mana:0});G.tryOpeningInteraction();r.drain();draw();assert.ok(draws.some(d=>d.s===S.starSpindle&&d.f===1));assert.equal(G.ensureTown().spirit,spirit+8);assert.equal(picked,1);assert.equal(G.state.player.damageTaken,0);assert.equal(G.state.player.mana,G.playerMaxMana());const items=JSON.stringify(G.state.items);draw();G.tryOpeningInteraction();assert.equal(JSON.stringify(G.state.items),items);assert.equal(G.ensureTown().spirit,spirit+8);r.load('starfallRuins');r.drain();assert.equal(G.starfallSurvey().aligned,3);assert.equal(G.starfallSurvey().thread,true);draw();assert.ok(draws.some(d=>d.s===S.starSpindle&&d.f===1));
});
test('quiet gallery materials and authored stations retain native terrain, pantry, post and return across both pixel settings',()=>{
 const r=runtime(),{G}=r;r.load('starfallRuins');r.drain();G.W=480;G.H=304;const {ctx,draws}=capture(G),S=G.starfallScenery,grid=JSON.stringify(G.state.grid),items=JSON.stringify(G.state.items);
 for(const hd of [true,false]){G.hdPilot=hd;draws.length=0;G.world.draw(ctx,{x:0,y:0},3);for(const d of G.openingDrawables(ctx))d.fn();for(const id of Object.keys(S))assert.ok(draws.some(d=>d.s===S[id]),id);for(const sprite of Object.values(S))for(const frame of G.activeSpriteDefinition(sprite).frames)for(const row of frame)for(const p of row)assert.ok(p==='.'||G.activeSpriteDefinition(sprite).palette[p]);}
 assert.equal(JSON.stringify(G.state.grid),grid);assert.equal(JSON.stringify(G.state.items),items);assert.ok(G.world.solid(168,88));assert.equal(G.world.solid(88,88),false);G.state.wayfinder.posts=[];draws.length=0;G.world.draw(ctx,{x:0,y:0},3);assert.ok(draws.some(d=>d.s===G.greenfieldScenery.postSleeping));G.activateWayfinderPost('starfallRuins',true);draws.length=0;G.world.draw(ctx,{x:0,y:0},3);assert.ok(draws.some(d=>d.s===G.greenfieldScenery.postAwake));
 const ch=G.state.chests.find(c=>c.food);G.drawStarfallPantry(ctx,ch);assert.equal(draws.pop().s,G.homeScenery.pantryReady);Object.assign(G.state.player,{x:ch.x*16+8,y:ch.y*16+8,damageTaken:2});G.world.checkTriggers(.5);assert.equal(G.state.pantries[ch.key].servings,1);G.drawStarfallPantry(ctx,ch);assert.equal(draws.pop().s,G.homeScenery.pantryEmpty);const pantry=JSON.stringify(G.state.pantries);r.load('starfallRuins');assert.equal(JSON.stringify(G.state.pantries),pantry);Object.assign(G.state.player,{x:248,y:8});G.world.checkTriggers(.5);assert.equal(G.state.mapId,'overworld');assert.equal(G.drawStarfallTile(ctx,{tile:'floor'},3,3),false);
});
