const {test}=require('node:test'),assert=require('node:assert/strict'),runtime=require('../tools/lib/classic-runtime.cjs');
function setup(){const r=runtime();r.load('astronomerTrial');r.drain();r.G.state.enemies=[];r.G.W=448;r.G.H=272;return r;}
function capture(G){const draws=[],bars=[],stack=[],ctx=new Proxy({globalAlpha:1,measureText:t=>({width:String(t).length*5}),save(){stack.push(this.globalAlpha);},restore(){this.globalAlpha=stack.pop();},fillRect(x,y,w,h){bars.push({x,y,w,h,color:this.fillStyle});}},{get:(o,k)=>o[k]??(()=>{}),set:(o,k,v)=>(o[k]=v,true)});G.drawSprite=(c,s,f,x,y)=>draws.push({s,f,x,y,alpha:c.globalAlpha});return {ctx,draws,bars};}
const go=(G,x,y)=>Object.assign(G.state.player,{x:x*16+8,y:y*16+8});
test('Starpath keeps four solid cover points and the native coastal entry and west return',()=>{
 const r=setup(),{G}=r,{ctx,draws}=capture(G),S=G.starpathScenery,cover=[[8,4],[16,3],[12,13],[21,13]],saved=JSON.stringify(G.state.grid);
 for(const [x,y]of cover)assert.ok(G.world.solid(x*16+8,y*16+8));assert.equal(G.state.grid.flat().filter(c=>c.tile==='rock').length,4);G.world.draw(ctx,{x:0,y:0},3);for(const d of G.openingDrawables(ctx))d.fn();assert.equal(draws.filter(d=>d.s===S.instrumentStand).length,4);assert.ok(draws.some(d=>d.s===S.skyChart));assert.ok(draws.some(d=>d.s===S.telescope));assert.ok(draws.some(d=>d.s===S.notice));assert.ok(draws.some(d=>d.s===S.returnStep));assert.equal(JSON.stringify(G.state.grid),saved);
 go(G,0,8);G.world.checkTriggers(.5);r.drain();assert.equal(G.state.mapId,'shattercoast');assert.equal(G.state.player.x,10*16+8);assert.equal(G.state.player.y,23*16+8);assert.ok(G.world.isSafeSpawn(G.state.player.x,G.state.player.y));assert.equal(G.world.isSafeSpawn(11*16+8,24*16+8),false);const entry=G.state.grid.flatMap((row,y)=>row.flatMap((cell,x)=>cell.portal?.map==='astronomerTrial'?[{cell,x,y}]:[]))[0];assert.equal(entry.cell.stars||0,0);G.state.stars=0;assert.equal(G.world.portalBlockReason(entry.cell),null);go(G,entry.x,entry.y);G.state.portalNeedsRelease=false;G.state.portalGrace=0;G.world.checkTriggers(.5);r.drain();assert.equal(G.state.mapId,'astronomerTrial');assert.equal(JSON.stringify(G.state.grid),saved);
});
test('Starpath biscuit pantry follows actual renewable pantry healing, cooldown, leave-to-refill and saved servings',()=>{
 const r=setup(),{G}=r,{ctx,draws,bars}=capture(G),ch=G.state.chests[0],S=G.starpathScenery;assert.equal(ch.food,true);assert.equal(ch.key,'astronomerTrial:6,11');const draw=()=>{draws.length=0;bars.length=0;G.drawStarpathCache(ctx,G.state.chests[0]);};draw();assert.equal(draws[0].f,0);G.state.player.damageTaken=2;go(G,6,11);G.world.checkTriggers(.5);r.drain();assert.equal(G.state.player.damageTaken,0);assert.equal(G.state.pantries[ch.key].servings,1);assert.ok(ch.readyAt>Date.now());draw();assert.equal(draws[0].s,S.cookieJar);assert.equal(draws[0].f,1);assert.ok(bars.some(b=>b.w===20&&b.color==='#303f4c'));assert.ok(!G.state.opened.includes(ch.key));G.world.checkTriggers(.5);assert.equal(G.state.pantries[ch.key].servings,1);
 r.load('astronomerTrial');r.drain();G.state.enemies=[];draw();assert.equal(draws[0].f,1);const current=G.state.chests[0];G.state.pantries[ch.key].readyAt=Date.now()-1;go(G,6,11);G.world.checkTriggers(.5);assert.equal(current.opened,false);assert.equal(current.needsLeave,true);G.world.checkTriggers(.5);assert.equal(G.state.pantries[ch.key].servings,1);go(G,8,11);G.world.checkTriggers(.5);go(G,6,11);G.world.checkTriggers(.5);assert.equal(G.state.pantries[ch.key].servings,2);const journal=JSON.stringify(G.state.pantries);draw();assert.equal(JSON.stringify(G.state.pantries),journal);
});
test('braced instruments and mounted sky fittings yield to player and NPCs in both pixel settings without changing terrain or painter state',()=>{
 const r=setup(),{G}=r,{ctx,draws}=capture(G),S=G.starpathScenery;G.reducedMotion=true;go(G,8,3);const saved=JSON.stringify(G.state.grid);for(const hd of [true,false]){G.hdPilot=hd;draws.length=0;for(const d of G.openingDrawables(ctx))d.fn();assert.ok(draws.some(d=>d.s===S.instrumentStand&&d.alpha<=.35));assert.ok(draws.filter(d=>d.s===S.instrumentStand).every(d=>d.f===0));for(const sprite of Object.values(S))for(const frame of G.activeSpriteDefinition(sprite).frames)for(const row of frame)for(const p of row)assert.ok(p==='.'||G.activeSpriteDefinition(sprite).palette[p]);assert.equal(ctx.globalAlpha,1);}assert.equal(JSON.stringify(G.state.grid),saved);go(G,13,8);G.state.npcs=[{x:136,y:56}];draws.length=0;for(const d of G.openingDrawables(ctx))d.fn();assert.ok(draws.some(d=>d.s===S.instrumentStand&&d.alpha<=.35));G.state.npcs=[{x:120,y:24}];draws.length=0;for(const d of G.openingDrawables(ctx))d.fn();assert.ok(draws.some(d=>d.s===S.skyChart&&d.alpha<=.35));r.load('overworld');assert.equal(G.drawStarpathTile(ctx,{tile:'floor'},1,1),false);assert.equal(G.drawStarpathCache(ctx,{x:1,y:1}),false);
});
test('live safe-orbit text remains clear of a lens stand, while cancellation restores it and drawing preserves hazard clocks',()=>{
 const r=runtime(),{G}=r;r.load('astronomerTrial');r.drain();const e=G.state.enemies.find(e=>e.def.id==='professorPerihelion');G.state.enemies=[e];G.state.bossCutscene=null;Object.assign(G.state.player,{x:e.x-60,y:e.y});Object.assign(e,{bossEngaged:true,bossIntroT:0,bossPhase:3,hp:e.def.hp*.3,bossTelegraphT:.01,bossPendingAction:'orbitalBand'});G.updateEnemies(.02);Object.assign(G.state.player,{x:40,y:136});const {ctx,draws}=capture(G),h=G.state.bossHazards[0],saved=JSON.stringify(h),grid=JSON.stringify(G.state.grid);for(const hd of [true,false]){G.hdPilot=hd;draws.length=0;for(const d of G.openingDrawables(ctx))d.fn();assert.ok(draws.some(d=>d.s===G.starpathScenery.instrumentStand&&d.x===344&&d.alpha<=.15));assert.equal(ctx.globalAlpha,1);assert.equal(JSON.stringify(h),saved);assert.equal(JSON.stringify(G.state.grid),grid);}G.cancelBossHazards(e);draws.length=0;for(const d of G.openingDrawables(ctx))d.fn();assert.ok(draws.some(d=>d.s===G.starpathScenery.instrumentStand&&d.x===344&&d.alpha===1));
});
