const {test}=require('node:test'),assert=require('node:assert/strict'),runtime=require('../tools/lib/classic-runtime.cjs');
function setup(){const r=runtime(),{G}=r;G.state.opening.complete=true;G.state.delivery.complete=true;r.load('dungeon');r.drain();r.run('js/engine/ui.js');G.state.bossCutscene=null;G.state.enemies=[];G.state.npcs=[];G.world.nearPortal=()=>null;G.tutorial.prompt=()=>null;const c=r.nodes.get('ui').getContext('2d'),rects=[],labels=[],stack=[];let dx=0,dy=0;c.save=()=>stack.push([dx,dy,c.globalAlpha]);c.restore=()=>{[dx,dy,c.globalAlpha]=stack.pop();};c.translate=(x,y)=>{dx+=x;dy+=y;};c.fillRect=(x,y,w,h)=>rects.push({x:x+dx,y:y+dy,w,h,color:c.fillStyle});c.fillText=(t,x,y)=>labels.push({text:String(t),x:x+dx,y:y+dy});const draw=cam=>{rects.length=labels.length=0;G.ui.drawHUD(cam);assert.equal(dx,0);assert.equal(dy,0);assert.equal(stack.length,0);};return {r,G,rects,labels,draw};}
function actor(G,cam){const m=G.spriteMetrics(G.playerForm().sprite),p=G.state.player;return {x:p.x-cam.x-Math.max(12,m.w/2)-2,y:p.y-cam.y-Math.max(28,m.h)-2,w:Math.max(12,m.w/2)*2+4,h:Math.max(28,m.h)+6};}
const overlaps=(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
function status(rects){const mana=rects.find(q=>q.w===42&&q.h===5);assert.ok(mana,'mana remains visible');return mana;}
test('essential status clears both dungeon vault corners and northern actors, then returns to its familiar anchor in every input mode and pixel setting',()=>{
 const {G,rects,labels,draw}=setup(),cam={x:128,y:96};
 for(const hd of [true,false])for(const mode of ['keyboard','touch','controller'])for(const id of ['nobody','dragon']){G.hdPilot=hd;G.input.isTouch=mode==='touch';G.input.hasGamepad=mode==='controller';G.state.formId=id;
  for(const [x,y]of [[24,24],[40,40],[136,24],[160,24]]){Object.assign(G.state.player,{x:cam.x+x,y:cam.y+y});draw(cam);const bar=status(rects),chip=labels.find(q=>q.text.includes(' Lv'));assert.ok(chip);const box={x:bar.x-1,y:bar.y-11,w:Math.max(chip.text.length*5+9,G.playerMaxHearts()*9+3,43),h:30};assert.ok(!overlaps(box,actor(G,cam)),`${mode}/${id} at ${x},${y}: status reveals sprite`);assert.ok(bar.x>=6&&chip.x>=8);assert.ok(chip.x+chip.text.length*5<=G.W-55,'status clears the map/pause buttons');if(x===160)assert.ok(!labels.some(q=>/old dungeon/i.test(q.text)),'location title yields above the traveller');}
  Object.assign(G.state.player,{x:cam.x+160,y:cam.y+140});draw(cam);assert.equal(status(rects).x,6);assert.equal(status(rects).y,16);if(mode==='touch')assert.ok(labels.some(q=>/old dungeon/i.test(q.text)),'location returns where the status leaves room');
 }
});
test('a wide buffed status uses a lower clear row while story, lesson and incidental speech yield to essential information without ticking buffs or progress',()=>{
 const {G,rects,labels,draw}=setup(),cam={x:0,y:0};G.input.isTouch=true;G.state.formId='nobody';Object.assign(G.state.player,{x:100,y:24,pantryGuard:2,pantryHasteT:8,pantryQuickT:8,pantryMagnetT:8,passiveBarrier:3});G.guidanceShowStoryCard=()=>true;G.state.npcs=[{x:100,y:80,def:{name:'Road friend'},bubble:{text:'CLEAR ROAD',delay:0,t:2,duration:2}}];const before=JSON.stringify({p:G.state.player,counts:G.questCounts,items:G.state.items,time:G.state.time,bubble:G.state.npcs[0].bubble});draw(cam);const bar=status(rects);assert.ok(bar.y>=51,'wide status moves below the actor');for(const word of ['WARD','FAST','QUICK','MAG'])assert.ok(labels.some(q=>q.text===word));assert.ok(!labels.some(q=>q.text.includes('MAIN STORY')));assert.ok(!labels.some(q=>q.text==='CLEAR ROAD'));assert.equal(JSON.stringify({p:G.state.player,counts:G.questCounts,items:G.state.items,time:G.state.time,bubble:G.state.npcs[0].bubble}),before);assert.ok(!overlaps(bar,actor(G,cam)));Object.assign(G.state.player,{x:160,y:150});draw(cam);assert.equal(status(rects).y,16);assert.ok(labels.some(q=>q.text.includes('MAIN STORY')));
});
test('rendering the revealed Crest corner preserves the real pickup and legacy saved item, and boss information stays visible',()=>{
 const {r,G,rects,labels,draw}=setup(),cam={x:0,y:0};Object.assign(G.state.player,{x:24,y:24});G.world.checkTriggers(.5);r.drain();require('./helpers/collect-treasure.cjs')(r,'knights-crest');assert.ok(G.state.items.includes('knights-crest'));assert.ok(G.state.opened.includes('dungeon:1,1'));const before=JSON.stringify({items:G.state.items,opened:G.state.opened,damage:G.state.player.damageTaken,mana:G.state.player.mana});draw(cam);assert.ok(!overlaps(status(rects),actor(G,cam)));assert.equal(JSON.stringify({items:G.state.items,opened:G.state.opened,damage:G.state.player.damageTaken,mana:G.state.player.mana}),before);r.load('jesterTrial');r.drain();G.state.bossCutscene=null;const e=G.state.enemies.find(e=>e.def.id==='royalFool');e.bossEngaged=true;Object.assign(G.state.player,{x:24,y:24});draw(cam);assert.ok(labels.some(q=>q.text.includes('TANSY')));assert.ok(labels.some(q=>q.text.includes(' Lv')));const bar=status(rects),boss=rects.find(q=>q.w===150&&q.h===17);assert.ok(boss);assert.ok(!overlaps({x:bar.x-1,y:bar.y-11,w:100,h:30},boss),'essential health/form and boss information cannot cover each other');
});
