const {test}=require('node:test'),assert=require('node:assert/strict'),runtime=require('../tools/lib/classic-runtime.cjs');
function setup(){const r=runtime();r.load('stormspinePeaks');r.drain();r.G.state.enemies=[];r.G.W=736;r.G.H=464;return r;}
function capture(G){const draws=[],stack=[],ctx=new Proxy({globalAlpha:1,measureText:t=>({width:String(t).length*5}),save(){stack.push(this.globalAlpha);},restore(){this.globalAlpha=stack.pop();}},{get:(o,k)=>o[k]??(()=>{}),set:(o,k,v)=>(o[k]=v,true)});G.drawSprite=(c,s,f,x,y)=>draws.push({s,f,x,y,alpha:c.globalAlpha});return {ctx,draws};}
const go=(G,x,y)=>Object.assign(G.state.player,{x:x*16+8,y:y*16+8});
test('eight mounted lamps and sixteen fitted passes read the native Lantern victory while the eastern gate still requires Echo',()=>{
 const r=setup(),{G}=r,{ctx,draws}=capture(G),S=G.stormspineScenery,draw=()=>{draws.length=0;G.world.draw(ctx,{x:0,y:0},3);for(const d of G.openingDrawables(ctx))d.fn();};draw();assert.equal(draws.filter(d=>d.s===S.lantern&&d.f===0).length,8);assert.equal(draws.filter(d=>d.s===S.litSlab).length,0);assert.ok(draws.some(d=>d.s===S.echoGate&&d.f===0&&d.x+12<=736));assert.ok(G.world.solid(248,312));G.events.emit('pickup',{item:'trophy-lantern-keeper'});draw();assert.equal(draws.filter(d=>d.s===S.lantern&&d.f===1).length,8);assert.equal(draws.filter(d=>d.s===S.litSlab).length,16);assert.equal(G.world.solid(248,312),false);assert.equal(G.state.grid[19][17].tile,'rock');assert.ok(draws.some(d=>d.s===S.echoGate&&d.f===0));assert.match(G.world.portalBlockReason(G.state.grid[14][45]).text,/Echo Mark/);assert.equal(G.maps.stormspinePeaks.tiles[19][15],'r');
 r.load('stormspinePeaks');r.drain();G.state.enemies=[];draw();assert.equal(draws.filter(d=>d.s===S.litSlab).length,16);assert.equal(G.state.restorationDetails.length,28);assert.ok(draws.some(d=>d.s===G.townScenery.lantern));assert.ok(draws.some(d=>d.s===G.groveScenery.flower));assert.ok(draws.some(d=>d.s===S.tuft));const saved=JSON.stringify({items:G.state.items,world:G.state.worldwake,grid:G.state.grid,details:G.state.restorationDetails});draw();assert.equal(JSON.stringify({items:G.state.items,world:G.state.worldwake,grid:G.state.grid,details:G.state.restorationDetails}),saved);go(G,45,14);G.world.checkTriggers(.5);r.drain();assert.equal(G.state.mapId,'stormspinePeaks');G.events.emit('pickup',{item:'trophy-bell-titan'});draw();assert.ok(draws.some(d=>d.s===S.echoGate&&d.f===1));assert.equal(G.world.portalBlockReason(G.state.grid[14][45]),null);go(G,45,14);G.world.checkTriggers(.5);r.drain();assert.equal(G.state.mapId,'titanGrave');r.load('stormspinePeaks');r.drain();go(G,0,14);G.world.checkTriggers(.5);r.drain();assert.equal(G.state.mapId,'frostbellTundra');
});
test('Stormglass cache, pantry recovery and atlas retain actual state and one-time collection',()=>{
 const r=setup(),{G}=r,{ctx,draws}=capture(G),S=G.stormspineScenery,draw=()=>{draws.length=0;G.world.draw(ctx,{x:0,y:0},3);};draw();assert.ok(draws.some(d=>d.s===S.cache&&d.f===0));const box=G.state.chests.find(c=>c.chest.item==='stormglass-lantern');go(G,box.x,box.y);G.world.checkTriggers(.5);r.drain();require('./helpers/collect-treasure.cjs')(r,'stormglass-lantern');draw();assert.ok(draws.some(d=>d.s===S.cache&&d.f===1));assert.equal(G.state.items.filter(i=>i==='stormglass-lantern').length,1);r.load('stormspinePeaks');r.drain();G.state.enemies=[];draw();assert.ok(draws.some(d=>d.s===S.cache&&d.f===1));go(G,7,20);Object.assign(G.state.player,{damageTaken:2,mana:0});G.world.checkTriggers(.5);assert.equal(G.state.player.damageTaken,0);assert.equal(G.state.player.mana,G.playerMaxMana());G.state.wayfinder.posts=[];draw();assert.ok(draws.some(d=>d.s===G.greenfieldScenery.postSleeping));G.activateWayfinderPost('stormspinePeaks',true);draw();assert.ok(draws.some(d=>d.s===G.greenfieldScenery.postAwake));
});
test('slate spires and mounted lamps yield around travellers or NPCs while both pixel settings preserve scenery footprints and collision',()=>{
 const r=setup(),{G}=r,{ctx,draws}=capture(G),S=G.stormspineScenery;G.reducedMotion=true;go(G,12,2);const saved=JSON.stringify({grid:G.state.grid,items:G.state.items});for(const hd of [true,false]){G.hdPilot=hd;draws.length=0;G.world.draw(ctx,{x:0,y:0},10);for(const d of G.openingDrawables(ctx))d.fn();assert.ok(draws.some(d=>d.s===S.spire&&d.alpha<=.35));assert.ok(draws.filter(d=>d.s===S.spire).every(d=>d.f===0));assert.ok(draws.some(d=>d.s===G.prairieScenery.hearth&&d.f===0));for(const sprite of Object.values(S))for(const frame of G.activeSpriteDefinition(sprite).frames)for(const row of frame)for(const p of row)assert.ok(p==='.'||G.activeSpriteDefinition(sprite).palette[p]);assert.equal(ctx.globalAlpha,1);}assert.equal(JSON.stringify({grid:G.state.grid,items:G.state.items}),saved);go(G,10,6);draws.length=0;for(const d of G.openingDrawables(ctx))d.fn();assert.ok(draws.some(d=>d.s===S.lantern&&d.alpha<=.35));go(G,23,14);G.state.npcs=[{x:168,y:100}];draws.length=0;for(const d of G.openingDrawables(ctx))d.fn();assert.ok(draws.some(d=>d.s===S.lantern&&d.x===168&&d.alpha<=.35));assert.ok(G.world.solid(216,88));r.load('frostbellTundra');r.drain();assert.equal(G.drawStormspineTile(ctx,{tile:'grass'},1,1),false);assert.equal(G.drawStormspineLantern(ctx,0,0,true),false);
});
