const {test}=require('node:test'),assert=require('node:assert/strict'),runtime=require('../tools/lib/classic-runtime.cjs');
const collect=require('./helpers/collect-treasure.cjs'),cross=require('./helpers/cross-road.cjs');
const sources=[['beacon',22,20,8,'pebble'],['recipes',12,12,5,'quayBaker'],['dragon',28,26,6,'quayPip'],['welcome',30,13,5,'quayMara']];
function setup(){const r=runtime(),{G}=r;G.state.opening.complete=G.state.delivery.complete=true;G.state.stars=28;G.state.claimedForms=G.formOrder.filter(f=>!['nobody','god'].includes(f));G.questsDone=G.formOrder.flatMap(f=>G.forms[f].quests.map(q=>q.id));Object.assign(G.ensureTown(),{founded:true,introduced:true,spirit:20,requests:[]});r.load('sunriseQuay');r.drain();G.state.enemies=[];return r;}
function ready(G,id){if(id==='beacon')G.state.items.push('trophy-mire-pearl');if(id==='recipes')G.state.items.push('brindles-recipes');if(id==='dragon')G.ensureExpeditionProgress().victories=1;if(id==='welcome')G.ensureTown().projects.welcomeLodge=true;}
function at(G,x,y){Object.assign(G.state.player,{x:x*16+8,y:y*16+8});}
for(const [id,x,y,amount,npc]of sources)test(`${id}: native thanks completes the promise immediately, but the saved gift pays only on collection`,()=>{
 const r=setup(),{G}=r,item=`sunrise-thanks-${id}`,events=[];G.events.on('pickup',e=>{if(e.item===item)events.push(e.item);});ready(G,id);G.followSunriseRequest(id);at(G,x,y);const items=[...G.state.items];assert.equal(G.deliveryCandidate().id,id);G.tryOpeningInteraction();r.drain();
 const gift={...G.groundRewardFor(item)},promise=G.sunriseRequests().find(q=>q.id===id);assert.ok(promise.done);assert.ok(promise.pending);assert.ok(G.world.isSafeSpawn(gift.x,gift.y));assert.equal(G.ensureTown().spirit,20);assert.equal(G.followedSunriseRequest(),null);assert.deepEqual([...G.state.items],items);assert.equal(events.length,0);assert.match(G.npcDialogue(npc,0,0),/waits beside me/);
 G.tryOpeningInteraction();r.drain();assert.equal(G.state.groundRewards.filter(g=>g.item===item).length,1);G.saveGame();const saved=G.loadSaveData();assert.ok(saved.town.requests.includes(id));assert.ok(saved.groundRewards.some(g=>g.item===item));
 cross(r,'town');assert.equal(G.groundRewardsHere().length,0);cross(r,'sunriseQuay');r.drain();G.state.enemies=[];
 G.state.town=G.normalizeTown(saved.town);G.state.groundRewards=G.normalizeGroundRewards(saved.groundRewards.map(g=>({...g,spirit:9999})));r.load('sunriseQuay');r.drain();G.state.enemies=[];assert.ok(G.sunriseRequests().find(q=>q.id===id).pending);
 G.state.player.invuln=0;G.damagePlayer(100);r.drain();assert.ok(G.groundRewardFor(item));Object.assign(G.state.player,G.world.safeArrival(gift.x,gift.y-24));G.state.player.damageTaken=2;const stars=G.state.stars;collect(r,item);
 assert.equal(G.ensureTown().spirit,20+amount);assert.equal(G.state.stars,stars);assert.equal(G.state.player.damageTaken,2,'thanks does not add recovery');assert.equal(events.length,1);assert.equal(G.sunriseRequests().find(q=>q.id===id).pending,false);assert.ok(!G.npcDialogue(npc,0,0).includes('waits beside me'));at(G,x,y);G.tryOpeningInteraction();r.drain();assert.equal(G.ensureTown().spirit,20+amount);assert.equal(G.revealRegionalReward(item,gift.x,gift.y),null);G.saveGame();assert.equal(G.normalizeGroundRewards(saved.groundRewards).length,0);
});
test('legacy completed requests never manufacture new thanks; a returned promise preserves another selected task',()=>{
 for(const [id,x,y]of sources){const r=setup(),{G}=r,item=`sunrise-thanks-${id}`,raw={source:'regional',item,mapId:'sunriseQuay',x:x*16+8,y:y*16+8+24};assert.equal(G.normalizeGroundRewards([raw]).length,0);G.ensureTown().requests.push(id);assert.equal(G.normalizeGroundRewards([{...raw,mapId:'town'}]).length,0);at(G,x,y);G.tryOpeningInteraction();r.drain();assert.equal(G.groundRewardFor(item),null);assert.equal(G.ensureTown().spirit,20);assert.equal(G.sunriseRequests().find(q=>q.id===id).pending,false);}
 const r=setup(),{G}=r;G.followSunriseRequest('recipes');ready(G,'beacon');at(G,22,20);G.tryOpeningInteraction();r.drain();assert.equal(G.followedSunriseRequest().id,'recipes');assert.ok(G.groundRewardFor('sunrise-thanks-beacon'));collect(r,'sunrise-thanks-beacon');assert.equal(G.followedSunriseRequest().id,'recipes');
});
