const {test}=require('node:test'),assert=require('node:assert/strict'),runtime=require('../tools/lib/classic-runtime.cjs');
function setup(){const r=runtime();r.load('titanGrave');r.drain();r.G.state.enemies=[];r.G.W=736;r.G.H=464;return r;}
function capture(G){const draws=[],stack=[],ctx=new Proxy({globalAlpha:1,measureText:t=>({width:String(t).length*5}),save(){stack.push(this.globalAlpha);},restore(){this.globalAlpha=stack.pop();}},{get:(o,k)=>o[k]??(()=>{}),set:(o,k,v)=>(o[k]=v,true)});G.drawSprite=(c,s,f,x,y)=>draws.push({s,f,x,y,alpha:c.globalAlpha});return {ctx,draws};}
const go=(G,x,y)=>Object.assign(G.state.player,{x:x*16+8,y:y*16+8});
const items=['trophy-sky-sovereign','trophy-old-mason','trophy-silk-matriarch','trophy-bell-titan','trophy-lantern-keeper'];
test('five fitted memorials read individual actual keepsakes and the southern arch keeps its independent Worldheart requirement',()=>{
 const r=setup(),{G}=r,{ctx,draws}=capture(G),S=G.titanScenery,draw=()=>{draws.length=0;G.world.draw(ctx,{x:0,y:0},3);for(const d of G.openingDrawables(ctx))d.fn();};draw();for(let i=0;i<5;i++)assert.ok(draws.some(d=>d.s===S['memorial'+i]&&d.f===0));assert.ok(draws.some(d=>d.s===S.heartArch&&d.f===0));for(let i=0;i<5;i++){G.state.items.push(items[i]);draw();for(let j=0;j<5;j++)assert.ok(draws.some(d=>d.s===S['memorial'+j]&&d.f===(j<=i?1:0)));}G.state.worldwake=G.normalizeWorldwake(undefined,{items:G.state.items});r.load('titanGrave');r.drain();G.state.enemies=[];draw();assert.ok(draws.some(d=>d.s===S.heartArch&&d.f===0));assert.match(G.world.portalBlockReason(G.state.grid[28][23]).text,/Worldheart Mark/);const saved=JSON.stringify({grid:G.state.grid,items:G.state.items,world:G.state.worldwake,stars:G.state.stars});draw();assert.equal(JSON.stringify({grid:G.state.grid,items:G.state.items,world:G.state.worldwake,stars:G.state.stars}),saved);go(G,23,28);G.world.checkTriggers(.5);r.drain();assert.equal(G.state.mapId,'titanGrave');G.state.items.push('trophy-last-worldbearer');G.state.worldwake=G.normalizeWorldwake(undefined,{items:G.state.items});r.load('titanGrave');r.drain();G.state.enemies=[];draw();assert.ok(draws.some(d=>d.s===S.heartArch&&d.f===1));assert.equal(G.state.restorationDetails.length,28);assert.ok(draws.some(d=>d.s===G.townScenery.lantern));assert.ok(draws.some(d=>d.s===G.groveScenery.flower));assert.equal(G.world.portalBlockReason(G.state.grid[28][23]),null);assert.equal(G.maps.titanGrave.tiles[14][0],'x');go(G,23,28);G.world.checkTriggers(.5);r.drain();assert.equal(G.state.mapId,'overworld');
 r.load('titanGrave');r.drain();go(G,23,0);G.world.checkTriggers(.5);r.drain();assert.equal(G.state.mapId,'glasswaterDesert');r.load('titanGrave');r.drain();go(G,0,14);G.world.checkTriggers(.5);r.drain();assert.equal(G.state.mapId,'stormspinePeaks');
});
test('Memory cache, atlas and caravan art retain native one-time pickup and recovery',()=>{
 const r=setup(),{G}=r,{ctx,draws}=capture(G),S=G.titanScenery,draw=()=>{draws.length=0;G.world.draw(ctx,{x:0,y:0},3);};draw();assert.ok(draws.some(d=>d.s===S.cache&&d.f===0));const box=G.state.chests.find(c=>c.chest.item==='titan-memory');go(G,box.x,box.y);G.world.checkTriggers(.5);r.drain();draw();assert.ok(draws.some(d=>d.s===S.cache&&d.f===1));assert.equal(G.state.items.filter(i=>i==='titan-memory').length,1);r.load('titanGrave');r.drain();G.state.enemies=[];draw();assert.ok(draws.some(d=>d.s===S.cache&&d.f===1));go(G,7,20);Object.assign(G.state.player,{damageTaken:2,mana:0});G.world.checkTriggers(.5);assert.equal(G.state.player.damageTaken,0);assert.equal(G.state.player.mana,G.playerMaxMana());G.state.wayfinder.posts=[];draw();assert.ok(draws.some(d=>d.s===G.greenfieldScenery.postSleeping));G.activateWayfinderPost('titanGrave',true);draw();assert.ok(draws.some(d=>d.s===G.greenfieldScenery.postAwake));
});
test('stone ribs, memorials and the Heart arch yield over travellers in both pixel settings without changing terrain or painter state',()=>{
 const r=setup(),{G}=r,{ctx,draws}=capture(G),S=G.titanScenery;G.reducedMotion=true;go(G,9,2);const saved=JSON.stringify({grid:G.state.grid,items:G.state.items});for(const hd of [true,false]){G.hdPilot=hd;draws.length=0;G.world.draw(ctx,{x:0,y:0},10);for(const d of G.openingDrawables(ctx))d.fn();assert.ok(draws.some(d=>d.s===S.rib&&d.alpha<=.35));assert.ok(draws.filter(d=>d.s===S.rib).every(d=>d.f===0));for(const sprite of Object.values(S))for(const frame of G.activeSpriteDefinition(sprite).frames)for(const row of frame)for(const p of row)assert.ok(p==='.'||G.activeSpriteDefinition(sprite).palette[p]);assert.equal(ctx.globalAlpha,1);}assert.equal(JSON.stringify({grid:G.state.grid,items:G.state.items}),saved);go(G,10,22);draws.length=0;for(const d of G.openingDrawables(ctx))d.fn();assert.ok(draws.some(d=>d.s===S.memorial0&&d.alpha<=.35));go(G,23,25);draws.length=0;for(const d of G.openingDrawables(ctx))d.fn();assert.ok(draws.some(d=>d.s===S.heartArch&&d.alpha<=.35));go(G,23,14);G.state.npcs=[{x:168,y:368}];draws.length=0;for(const d of G.openingDrawables(ctx))d.fn();assert.ok(draws.some(d=>d.s===S.memorial0&&d.alpha<=.35));assert.ok(G.world.solid(152,88));r.load('overworld');r.drain();assert.equal(G.drawTitanTile(ctx,{tile:'grass'},1,1),false);assert.equal(G.drawTitanMemorial(ctx,0,0,items[0]),false);assert.ok(G.drawGreenfieldHeartArch(ctx,1832,40,true));
});
