const {test}=require('node:test'),assert=require('node:assert/strict'),runtime=require('../tools/lib/classic-runtime.cjs');
test('native civic purchases, beautification and festival expiry select authored town art without changing routes or saves',()=>{
  const r=runtime(),{G}=r;G.state.town.founded=true;G.state.town.introduced=true;G.state.town.spirit=1000;G.state.town.houses=['a'];r.load('town');r.drain();
  const draws=[],stack=[],ctx=new Proxy({globalAlpha:1,measureText:t=>({width:String(t).length*5}),save(){stack.push(this.globalAlpha);},restore(){this.globalAlpha=stack.pop();}},{get:(o,k)=>o[k]??(()=>{}),set:(o,k,v)=>(o[k]=v,true)});G.drawSprite=(c,s,f,x,y)=>draws.push({s,f,x,y});const S=G.townScenery,grid=JSON.stringify(G.state.grid),fences=JSON.stringify(G.state.mapDef.fences),solid=G.world.solid(72,58);
  G.world.draw(ctx,{x:0,y:0},3);assert.ok(draws.some(d=>d.s===S.mailbox));assert.ok(!draws.some(d=>d.s===S.stage));
  for(const project of G.TOWN_PROJECTS){const before=G.state.town.spirit;assert.equal(G.buyTownProject(project.id),true);assert.equal(G.state.town.spirit,before-project.cost);assert.equal(G.buyTownProject(project.id),false);}
  assert.equal(G.beautifyTown(),true);assert.equal(G.state.town.beautifications,1);assert.equal(G.holdTownFestival(),true);const festivalUntil=G.state.town.festivalUntil;assert.equal(G.holdTownFestival(),false);draws.length=0;const town=JSON.stringify(G.state.town);G.reducedMotion=true;
  for(const hd of [true,false]){G.hdPilot=hd;G.world.draw(ctx,{x:0,y:0},30);for(const id of ['fenceRail','fencePost','mailbox','garden','lantern','welcomeSign','builderSign','bench','crates','stage','banner','monument','bunting'])assert.ok(draws.some(d=>d.s===S[id]),id);for(const sprite of Object.values(S))for(const frame of G.activeSpriteDefinition(sprite).frames)for(const row of frame)for(const pixel of row)assert.ok(pixel==='.'||G.activeSpriteDefinition(sprite).palette[pixel]);}
  assert.equal(JSON.stringify(G.state.town),town);assert.equal(JSON.stringify(G.state.grid),grid);assert.equal(JSON.stringify(G.state.mapDef.fences),fences);assert.equal(G.world.solid(72,58),solid);
  assert.equal(G.townFestivalActive(festivalUntil+1),false);G.state.town.festivalUntil=0;draws.length=0;G.world.draw(ctx,{x:0,y:0},40);assert.ok(!draws.some(d=>d.s===S.bunting),'expired festivals do not keep festival flags');assert.ok(draws.some(d=>d.s===S.stage),'permanent civic projects remain after the festival');
  G.world.draw(ctx,{x:0,y:128},40);assert.ok(draws.some(d=>d.s===S.exitGate));Object.assign(G.state.player,{x:232,y:264});G.world.checkTriggers(.5);assert.equal(G.state.mapId,'overworld','the authored town gate still uses the native return portal');
  assert.equal(G.drawTownDetail(ctx,{kind:'lantern',x:10,y:10}),false);assert.equal(G.drawTownFence(ctx,{style:'town',x:4,y:3,length:3,dir:'h'}),false);assert.equal(G.drawTownFestival(ctx),false);assert.equal(G.drawTownPortal(ctx,{portal:{map:'overworld'}},14,16),false);
});
