const {test}=require('node:test'),assert=require('node:assert/strict'),runtime=require('../tools/lib/classic-runtime.cjs');
function setup(){const r=runtime();r.load('windscarCanyon');r.drain();r.G.state.enemies=[];r.G.W=736;r.G.H=464;return r;}
function capture(G){const draws=[],stack=[],ctx=new Proxy({globalAlpha:1,measureText:t=>({width:String(t).length*5}),save(){stack.push(this.globalAlpha);},restore(){this.globalAlpha=stack.pop();}},{get:(o,k)=>o[k]??(()=>{}),set:(o,k,v)=>(o[k]=v,true)});G.drawSprite=(c,s,f,x,y)=>draws.push({s,f,x,y,alpha:c.globalAlpha});return {ctx,draws};}
const go=(G,x,y)=>Object.assign(G.state.player,{x:x*16+8,y:y*16+8});
test('authored wind landings follow the Sky Mark and real two-way safety, with old trophies restoring still cloth',()=>{
 const r=setup(),{G}=r,{ctx,draws}=capture(G),S=G.windscarScenery;G.reducedMotion=true;const draw=()=>{draws.length=0;for(const d of G.openingDrawables(ctx))d.fn();};draw();assert.equal(draws.filter(d=>d.s===S.windLift&&d.f===0).length,2);go(G,11,20);G.tryOpeningInteraction();r.drain();assert.equal(G.state.player.x,184);assert.equal(G.windscarLiftSurvey().unlocked,false);
 G.state.items.push('trophy-sky-sovereign');G.state.worldwake=G.normalizeWorldwake(undefined,{items:G.state.items});r.load('windscarCanyon');r.drain();G.state.enemies=[];draw();assert.equal(draws.filter(d=>d.s===S.windLift&&d.f===1).length,2);go(G,11,20);const before=JSON.stringify({items:G.state.items,world:G.state.worldwake,mana:G.state.player.mana,damage:G.state.player.damageTaken});assert.equal(G.tryOpeningInteraction(),true);assert.equal(G.state.player.x,536);assert.equal(G.state.player.y,136);assert.equal(G.tryOpeningInteraction(),true);assert.equal(G.state.player.x,184);assert.equal(G.state.player.y,328);assert.equal(JSON.stringify({items:G.state.items,world:G.state.worldwake,mana:G.state.player.mana,damage:G.state.player.damageTaken}),before);
 G.state.projectiles=[{x:536,y:131,fromPlayer:false}];assert.match(G.openingInteractionCandidate().label,/unsafe/i);G.tryOpeningInteraction();assert.equal(G.state.player.x,184);draw();assert.equal(draws.filter(d=>d.s===S.windLift&&d.f===1).length,2);G.state.projectiles=[];assert.equal(G.tryOpeningInteraction(),true);assert.equal(G.state.player.x,536);
});
test('canyon strata, feather cache and shared camp retain collision, recovery, atlas, native exits and yielding cliff views',()=>{
 const r=setup(),{G}=r,{ctx,draws}=capture(G),S=G.windscarScenery;G.reducedMotion=true;go(G,35,2);const grid=JSON.stringify(G.state.grid),items=JSON.stringify(G.state.items),draw=()=>{draws.length=0;G.world.draw(ctx,{x:0,y:0},3);for(const d of G.openingDrawables(ctx))d.fn();};for(const hd of [true,false]){G.hdPilot=hd;draw();for(const id of Object.keys(S))assert.ok(draws.some(d=>d.s===S[id]),id);assert.ok(draws.some(d=>d.s===S.scarp&&d.alpha<=.35));assert.ok(draws.some(d=>d.s===G.prairieScenery.hearth&&d.f===0));assert.ok(draws.some(d=>d.s===G.prairieScenery.fencePost));assert.equal(ctx.globalAlpha,1);for(const sprite of Object.values(S))for(const frame of G.activeSpriteDefinition(sprite).frames)for(const row of frame)for(const p of row)assert.ok(p==='.'||G.activeSpriteDefinition(sprite).palette[p]);}
 assert.equal(JSON.stringify(G.state.grid),grid);assert.equal(JSON.stringify(G.state.items),items);assert.ok(G.world.solid(264,72));assert.equal(G.world.solid(232,120),false);go(G,7,20);Object.assign(G.state.player,{damageTaken:2,mana:0});G.world.checkTriggers(.5);assert.equal(G.state.player.damageTaken,0);assert.equal(G.state.player.mana,G.playerMaxMana());const box=G.state.chests.find(c=>c.chest.item==='windscar-feather');go(G,box.x,box.y);G.world.checkTriggers(.5);r.drain();draw();assert.ok(draws.some(d=>d.s===S.cache&&d.f===1));assert.equal(G.state.items.filter(i=>i==='windscar-feather').length,1);r.load('windscarCanyon');r.drain();draw();assert.ok(draws.some(d=>d.s===S.cache&&d.f===1));
 G.state.wayfinder.posts=[];draw();assert.ok(draws.some(d=>d.s===G.greenfieldScenery.postSleeping));G.activateWayfinderPost('windscarCanyon',true);draw();assert.ok(draws.some(d=>d.s===G.greenfieldScenery.postAwake));go(G,45,14);G.world.checkTriggers(.5);assert.equal(G.state.mapId,'hangingGardens');r.load('windscarCanyon');r.drain();go(G,0,14);G.world.checkTriggers(.5);assert.equal(G.state.mapId,'sunstepPrairie');assert.equal(G.drawWindscarTile(ctx,{tile:'rock'},1,1),false);
 for(const [map,trophy]of [['windscarCanyon','trophy-sky-sovereign'],['mistwood','trophy-heartwood-crown'],['sunkenMarsh','trophy-mire-pearl'],['emberRidge','trophy-eclipse-sigil']]){G.state.items.push(trophy);G.state.worldwake=G.normalizeWorldwake(undefined,{items:G.state.items});r.load(map);r.drain();assert.equal(G.state.restorationDetails.length,28,map);const saved=JSON.stringify({items:G.state.items,details:G.state.restorationDetails});draws.length=0;G.drawLivingWorldGround(ctx,{x:0,y:0},3);assert.ok(draws.some(d=>d.s===G.groveScenery.flower));assert.ok(draws.some(d=>d.s===G.townScenery.lantern));assert.equal(JSON.stringify({items:G.state.items,details:G.state.restorationDetails}),saved);}

});
