const {test}=require('node:test'),assert=require('node:assert/strict'),runtime=require('../tools/lib/classic-runtime.cjs');
const rooms=[['griffinWorldback','windscarCanyon','skySovereign',4],['golemWorldback','hangingGardens','oldMason',4],['weaverWorldback','rootdeepHollow','silkMatriarch',4],['bellWorldback','frostbellTundra','bellTitan',4],['lanternWorldback','stormspinePeaks','lanternKeeper',4],['colossusWorldback','titanGrave','lastWorldbearer',5]];
function setup(){const r=runtime();r.G.state.opening.complete=true;r.G.state.delivery.complete=true;return r;}
function capture(G){const draws=[],stack=[],ctx=new Proxy({globalAlpha:1,measureText:t=>({width:String(t).length*5}),save(){stack.push(this.globalAlpha);},restore(){this.globalAlpha=stack.pop();}},{get:(o,k)=>o[k]??(()=>{}),set:(o,k,v)=>(o[k]=v,true)});G.drawSprite=(c,s,f,x,y)=>draws.push({s,f,x,y,alpha:c.globalAlpha});return {ctx,draws};}
function paint(G,c){G.world.draw(c,{x:0,y:0},3);const props=G.openingDrawables(c);for(const d of props)d.fn();return props;}
const go=(G,x,y)=>Object.assign(G.state.player,{x:x*16+8,y:y*16+8});
// Each existing rest bench now also carries two help lamps and a camp bag.
test('all six old-save shelters retain native cover and reachable rest/return paths, without duplicating their regional rulers',()=>{
 const r=setup(),{G}=r,{ctx}=capture(G);for(const [id,exit,boss,count]of rooms){r.load(id);r.drain();assert.equal(G.state.mapW,38);assert.equal(G.state.mapH,23);assert.equal(G.state.enemies.length,0);const grid=JSON.stringify(G.state.grid);assert.equal(G.state.grid.flat().filter(c=>c.tile==='rock').length,count);assert.equal(paint(G,ctx).length,count+5);assert.equal(JSON.stringify(G.state.grid),grid);const seen=new Set(['3,11']),q=[[3,11]];for(let i=0;i<q.length;i++)for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){const x=q[i][0]+dx,y=q[i][1]+dy,key=x+','+y;if(seen.has(key)||G.world.solid(x*16+8,y*16+8))continue;seen.add(key);q.push([x,y]);}for(const key of ['0,11','4,11','8,18','31,11'])assert.ok(seen.has(key),id+' retains '+key);assert.equal(G.state.grid[11][0].portal.map,exit);assert.equal(G.world.portalBlockReason(G.state.grid[11][0]),null);go(G,0,11);G.state.portalGrace=0;G.state.portalNeedsRelease=false;G.world.checkTriggers(.5);r.drain();assert.equal(G.state.mapId,exit);assert.ok(G.world.isSafeSpawn(G.state.player.x,G.state.player.y));assert.equal(G.state.enemies.filter(e=>e.def.id===boss).length,1,'the ruler stays in its original region');}
});
test('shelter seating follows the actual native rest event, never heals by drawing, and requires leaving before another rest',()=>{
 const r=setup(),{G}=r,{ctx,draws}=capture(G);for(const [id]of rooms){r.load(id);r.drain();Object.assign(G.state.player,{damageTaken:2,mana:0});draws.length=0;paint(G,ctx);assert.equal(draws.find(d=>d.s===G.worldbackScenery.restBench).f,0);assert.equal(G.state.player.damageTaken,2);assert.equal(G.state.player.mana,0);go(G,8,18);G.world.checkTriggers(.5);r.drain();assert.equal(G.state.player.damageTaken,0);assert.equal(G.state.player.mana,G.state.player.manaMax);const cell=G.state.lastRest;draws.length=0;paint(G,ctx);assert.equal(draws.find(d=>d.s===G.worldbackScenery.restBench).f,1);assert.equal(G.state.lastRest,cell);Object.assign(G.state.player,{damageTaken:1,mana:0});G.world.checkTriggers(.5);assert.equal(G.state.player.damageTaken,1);go(G,8,17);G.world.checkTriggers(.5);draws.length=0;paint(G,ctx);assert.equal(draws.find(d=>d.s===G.worldbackScenery.restBench).f,0);go(G,8,18);G.world.checkTriggers(.5);assert.equal(G.state.player.damageTaken,0);assert.equal(G.state.player.mana,G.state.player.manaMax);}
});
test('every shelter frame works in both settings and every region has distinct fitted cover and a workshop that yields over actors',()=>{
 const r=setup(),{G}=r,{ctx,draws}=capture(G),covers=new Set(),benches=new Set();assert.equal(Object.keys(G.worldbackScenery).length,16);for(const hd of [true,false]){G.hdPilot=hd;for(const sprite of Object.values(G.worldbackScenery)){const a=G.activeSpriteDefinition(sprite);assert.equal(a.frames.length,4);for(const frame of a.frames){assert.equal(frame.length,a.frames[0].length);for(const row of frame){assert.equal(row.length,a.frames[0][0].length);for(const pixel of row)assert.ok(pixel==='.'||a.palette[pixel]);}}for(let f=0;f<4;f++)G.drawSprite(ctx,sprite,f,100,100,false);}
 for(const [id,,,count]of rooms){r.load(id);r.drain();draws.length=0;const props=paint(G,ctx);assert.equal(props.length,count+5);const cover=draws.find(d=>d.x>100&&d.y<150&&d.s!==G.worldbackScenery.wall).s;covers.add(cover);const bench=draws.find(d=>d.x===504&&d.y===192);benches.add(bench.s);go(G,31,11);draws.length=0;paint(G,ctx);assert.ok(draws.find(d=>d.s===bench.s).alpha<1);go(G,8,18);draws.length=0;paint(G,ctx);assert.ok(draws.find(d=>d.s===G.worldbackScenery.restBench).alpha<1);G.state.npcs=[{x:504,y:184,def:{name:'Review traveller'}}];go(G,3,11);draws.length=0;paint(G,ctx);assert.ok(draws.find(d=>d.s===bench.s).alpha<1);assert.equal(ctx.globalAlpha,1);assert.ok(G.isAuthoredWorldback());}
 assert.equal(covers.size,6);assert.equal(benches.size,6);r.load('dungeon');r.drain();assert.equal(G.isAuthoredWorldback(),false);assert.equal(G.drawWorldbackTile(ctx,{tile:'floor'},3,3),false);assert.equal(G.drawWorldbackNotice(ctx,{message:'native'},3,3),false);assert.equal(G.drawWorldbackPortal(ctx,{portal:{}},3,3),false);assert.equal(G.openingDrawables(ctx).length,4);
 }
});
