/* Architecture follows the existing teacher portals and saved Chronicle. */
"use strict";
(()=>{
 const here=()=>G.state&&G.state.mapId==='shattercoast',S=G.coastScenery,rect=(c,x,y,w,h,col)=>{c.fillStyle=col;c.fillRect(x,y,w,h);},courts={turtle:'bastion',samurai:'foldHall',astronomer:'observatory',druid:'walkingGarden',god:'coliseum'};
 G.coastWaterColors=()=>here()?['#507f83','#82aaa2','#b7cdc0']:null;
 G.drawCoastTile=(c,cell,x,y,time)=>{if(!here()||!['grass','path','rock','water'].includes(cell.tile))return false;const px=x*16,py=y*16,r=G.util.hash2(x+313,y+163)*2,patch=G.util.hash2(Math.floor(x/5)+151,Math.floor(y/4)+37)*2;if(cell.tile==='water'){rect(c,px,py,16,16,['#507f83','#59878a','#4b767f'][Math.floor(patch*3)]);if(r>.67){const wave=G.reducedMotion?0:Math.floor(time*.7+r*3)%3;rect(c,px+3+wave,py+7,6,1,'#82aaa2');rect(c,px+9+wave,py+8,2,1,'#b7cdc0');}}else{rect(c,px,py,16,16,cell.tile==='path'?['#b5b095','#c1bba0','#aaa98d'][Math.floor(patch*3)]:['#879d8a','#91a68f','#809783'][Math.floor(patch*3)]);if(cell.tile==='rock'){G.drawSprite(c,S.shelf,Math.floor(r*4),px+8,py+16,false);if(G.state.grid[y-1]?.[x]?.tile!=='rock')rect(c,px,py,16,1,'#bdc7af');}else if(cell.tile==='grass'&&r>.95)G.drawSprite(c,S.saltGrass,Math.floor(r*4),px+8,py+16,false);else if(cell.tile==='path'&&r>.65)rect(c,px+4,py+9,7,1,'#ded4b4');}return true;};
 G.drawCoastPortal=(c,cell,x,y)=>{if(!here()||!cell.portal)return false;if(cell.portalStyle!=='trial'){c.save();c.translate(x*16+8,y*16+16);if(y===0){c.translate(0,8);c.rotate(-Math.PI/2);}G.drawSprite(c,S.roadStep,0,0,0,false);c.restore();}return true;};
 G.drawCoastTrial=(c,cell,x,y,locked)=>{if(!here()||!courts[cell.portalTheme])return false;const cx=x*16+8,by=y*16+24;c.save();const hidden=a=>a&&Math.abs(a.x-cx)<28&&a.y>by-50&&a.y<by-12;if(hidden(G.state.player)||(G.state.npcs||[]).some(hidden))c.globalAlpha*=.35;if(locked)c.globalAlpha*=.65;G.drawSprite(c,S[courts[cell.portalTheme]],0,cx,by,false);c.restore();return true;};
 G.drawCoastNotice=(c,cell,x,y)=>{if(!here()||!cell.message)return false;G.drawSprite(c,S.notice,0,x*16+8,y*16+16,false);return true;};
 G.drawCoastPantry=(c,ch)=>{if(!here()||!ch.food)return false;G.drawSprite(c,G.homeScenery[ch.opened?'pantryEmpty':'pantryReady'],0,ch.x*16+8,ch.y*16+16,false);if(ch.opened){const p=1-Math.min(1,Math.max(0,(ch.readyAt||0)-Date.now())/G.PANTRY_REFILL_MS);rect(c,ch.x*16+3,ch.y*16+14,10,1,'#394d52');rect(c,ch.x*16+3,ch.y*16+14,Math.round(10*p),1,'#b5d0bf');}return true;};
 G.drawCoastPost=(c,post,awake,near)=>{if(!here())return false;G.drawSprite(c,G.greenfieldScenery[awake?'postAwake':'postSleeping'],0,Math.round(post.x),Math.round(post.y)+6,false);if(near){rect(c,post.x-9,post.y-20,18,1,'#ddc295');rect(c,post.x-9,post.y-20,1,4,'#ddc295');rect(c,post.x+8,post.y-20,1,4,'#ddc295');}return true;};
 G.drawCoastFence=(c,f)=>here()?G.drawCaravanFence(c,f):false;
 G.drawCoastCairn=(c,x,y,lit)=>{if(!here())return false;G.drawSprite(c,S.cairn,lit?1:0,x,y+8,false);['tide-shell','paper-crane','orrery-key','elder-acorn'].forEach((item,i)=>{if(G.state.items.includes(item))G.drawSprite(c,S[['shell','crane','key','acorn'][i]],0,x-12+i*8,y-1,false);});return true;};
})();
