/* Native cover and recovery state, without changing the procession or its rewards. */
"use strict";
(()=>{
 const here=()=>G.state&&G.state.mapId==='gauntletArena',S=G.coliseumScenery,rect=(c,x,y,w,h,col)=>{c.fillStyle=col;c.fillRect(x,y,w,h);};
 G.drawColiseumTile=(c,cell,x,y)=>{if(!here()||!['floor','wall','rock'].includes(cell.tile))return false;const px=x*16,py=y*16,r=G.util.hash2(x+317,y+127)*2,patch=G.util.hash2(Math.floor(x/5)+89,Math.floor(y/4)+71)*2;rect(c,px,py,16,16,['#9b8881','#a08c82','#97847e'][Math.floor(patch*3)]);if(cell.tile==='wall')G.drawSprite(c,S.wall,Math.floor(r*4),px+8,py+16,false);else if(r>.82){rect(c,px+4,py+10,5,1,'#b29b8d');rect(c,px+9,py+11,3,1,'#8d7874');}return true;};
 G.drawColiseumPortal=(c,cell,x,y)=>{if(!here()||!cell.portal)return false;G.drawSprite(c,S.returnStep,0,x*16+8,y*16+16,false);return true;};
 G.drawColiseumNotice=(c,cell,x,y)=>{if(!here()||!cell.message)return false;const px=x*16+8,py=y*16+16,m=G.spriteMetrics(S.notice),hidden=a=>a&&Math.abs(a.x-px)<m.w/2+6&&a.y>py-m.h&&a.y<py+4;c.save();if(hidden(G.state.player)||(G.state.npcs||[]).some(hidden))c.globalAlpha*=.35;G.drawSprite(c,S.notice,0,px,py,false);c.restore();return true;};
 const old=G.openingDrawables;
 G.openingDrawables=c=>{const list=old(c);if(!here())return list;const prop=(id,x,y,depth)=>list.push({y:depth,fn:()=>{c.save();const s=G.state,m=G.spriteMetrics(S[id]),hidden=a=>a&&Math.abs(a.x-x)<m.w/2+12&&a.y<y+4&&a.y>y-m.h-2;if(hidden(s.player)||(s.npcs||[]).some(hidden))c.globalAlpha*=.35;const lit=id==='brazier'&&s.gauntletRun?.recovery&&s.gauntletBetween&&!s.gauntletBetween.opening;G.drawSprite(c,S[id],lit?(G.reducedMotion?1:1+2*(Math.floor(s.time*4)%2)):0,x,y,false);if(id==='recordBoard'){c.fillStyle='#ead7b0';c.font='4px monospace';c.textAlign='left';c.fillText('REST '+(s.gauntletBest||0),x-17,y-24);c.fillText('IRON '+(s.gauntletIronBest||0),x-17,y-14);}c.restore();}});for(let ty=0;ty<G.state.mapH;ty++)for(let tx=0;tx<G.state.mapW;tx++)if(G.state.grid[ty][tx].tile==='rock')prop('bench',tx*16+8,ty*16+16,ty*16+15);for(const [id,tx,bottom]of [['routeBanner',10,42],['recordBoard',19,42]])prop(id,tx*16+8,bottom,16);prop('brazier',3*16+8,96,95);return list;};
})();
