/* Four braced instruments keep Starpath's native solid cover. */
"use strict";
(()=>{
 const here=()=>G.state&&G.state.mapId==='astronomerTrial',S=G.starpathScenery,rect=(c,x,y,w,h,col)=>{c.fillStyle=col;c.fillRect(x,y,w,h);};
 G.drawStarpathTile=(c,cell,x,y)=>{if(!here()||!['floor','wall','rock'].includes(cell.tile))return false;const px=x*16,py=y*16,r=G.util.hash2(x+227,y+461)*2,patch=G.util.hash2(Math.floor(x/4)+173,Math.floor(y/3)+293)*2;rect(c,px,py,16,16,['#70818a','#75868e','#6d7e86'][Math.floor(patch*3)]);if(cell.tile==='wall')G.drawSprite(c,S.wall,Math.floor(r*4),px+8,py+16,false);else{if(y%3===0)rect(c,px,py,16,1,'#62747d');if(x%4===0)rect(c,px,py,1,16,'#62747d');if(r>.82){rect(c,px+4,py+10,5,1,'#8c9b9f');rect(c,px+9,py+11,3,1,'#74868e');}}return true;};
 G.drawStarpathPortal=(c,cell,x,y)=>{if(!here()||!cell.portal)return false;G.drawSprite(c,S.returnStep,0,x*16+8,y*16+16,false);return true;};
 G.drawStarpathNotice=(c,cell,x,y)=>{if(!here()||!cell.message)return false;G.drawSprite(c,S.notice,0,x*16+8,y*16+16,false);return true;};
 G.drawStarpathCache=(c,ch)=>{if(!here())return false;const x=ch.x*16+8,y=ch.y*16+16;G.drawSprite(c,S.cookieJar,ch.opened?1:0,x,y,false);if(ch.food&&ch.opened){const progress=1-Math.min(1,Math.max(0,(ch.readyAt||0)-Date.now())/G.PANTRY_REFILL_MS);rect(c,x-10,y-5,20,1,'#303f4c');rect(c,x-10,y-5,Math.round(20*progress),1,'#ead096');}return true;};
 const old=G.openingDrawables;
 G.openingDrawables=c=>{const list=old(c);if(!here())return list;const prop=(id,x,y,depth)=>list.push({y:depth,fn:()=>{c.save();const m=G.spriteMetrics(S[id]),hidden=a=>a&&Math.abs(a.x-x)<m.w/2+12&&a.y<y+4&&a.y>y-m.h-2;const warning=(G.state.bossHazards||[]).some(h=>{if(h.kind!=='orbitalBand'||h.owner?.def?.id!=='professorPerihelion'||h.owner.dead)return false;const local=h.t-(h.delay||0),ly=h.y+(h.inner+h.outer)/2+3;return local>=0&&local<h.warning+h.active&&x+m.w/2+1>h.x-20&&x-m.w/2-1<h.x+20&&y+1>ly-8&&y-m.h-1<ly+2;});if(warning)c.globalAlpha*=.15;else if(hidden(G.state.player)||(G.state.npcs||[]).some(hidden))c.globalAlpha*=.35;G.drawSprite(c,S[id],0,x,y,false);c.restore();}});for(let ty=0;ty<G.state.mapH;ty++)for(let tx=0;tx<G.state.mapW;tx++)if(G.state.grid[ty][tx].tile==='rock')prop('instrumentStand',tx*16+8,ty*16+16,ty*16+15);for(const [id,tx,bottom]of [['skyChart',7,42],['telescope',19,42]])prop(id,tx*16+8,bottom,16);return list;};
})();
