/* The six fitted glass cabinets occupy exactly the native solid-cover tiles. */
"use strict";
(()=>{
 const here=()=>G.state&&G.state.mapId==='riftbladeTrial',S=G.wayglassScenery,rect=(c,x,y,w,h,col)=>{c.fillStyle=col;c.fillRect(x,y,w,h);};
 G.drawWayglassTile=(c,cell,x,y)=>{if(!here()||!['floor','wall','rock'].includes(cell.tile))return false;const px=x*16,py=y*16,r=G.util.hash2(x+431,y+227)*2,patch=G.util.hash2(Math.floor(x/4)+109,Math.floor(y/4)+193)*2;rect(c,px,py,16,16,['#6d858d','#758e94','#657d86'][Math.floor(patch*3)]);if(cell.tile==='wall')G.drawSprite(c,S.wall,Math.floor(r*4),px+8,py+16,false);else{if(y%2===0)rect(c,px,py,16,1,'#5e7780');if(x%2===0)rect(c,px,py,1,16,'#5e7780');if(r>.8){rect(c,px+4,py+9,6,1,'#94a6a6');rect(c,px+9,py+10,2,1,'#778c93');}}return true;};
 G.drawWayglassPortal=(c,cell,x,y)=>{if(!here()||!cell.portal)return false;G.drawSprite(c,S.returnStep,0,x*16+8,y*16+16,false);return true;};
 G.drawWayglassNotice=(c,cell,x,y)=>{if(!here()||!cell.message)return false;G.drawSprite(c,S.notice,0,x*16+8,y*16+16,false);return true;};
 G.drawWayglassCache=(c,ch)=>{if(!here())return false;const x=ch.x*16+8,y=ch.y*16+16;G.drawSprite(c,S.cookieCase,ch.opened?1:0,x,y,false);if(ch.food&&ch.opened){const progress=1-Math.min(1,Math.max(0,(ch.readyAt||0)-Date.now())/G.PANTRY_REFILL_MS);rect(c,x-9,y-5,18,1,'#3c5260');rect(c,x-9,y-5,Math.round(18*progress),1,'#b8d4d1');}return true;};
 const old=G.openingDrawables;
 G.openingDrawables=c=>{const list=old(c);if(!here())return list;for(let ty=0;ty<G.state.mapH;ty++)for(let tx=0;tx<G.state.mapW;tx++)if(G.state.grid[ty][tx].tile==='rock'){const x=tx*16+8,y=ty*16+16;list.push({y:y-1,fn:()=>{c.save();const hidden=a=>a&&Math.abs(a.x-x)<14&&a.y<y&&a.y>y-38;if(hidden(G.state.player)||(G.state.npcs||[]).some(hidden))c.globalAlpha*=.35;G.drawSprite(c,S.pedestal,G.reducedMotion?0:Math.floor(G.state.time*.2+tx)%4,x,y,false);c.restore();}});}for(const [id,tx]of [['chart',8],['keyCabinet',17]]){const x=tx*16+8,y=32;list.push({y:16,fn:()=>{c.save();const hidden=a=>a&&Math.abs(a.x-x)<23&&a.y<y&&a.y>y-36;if(hidden(G.state.player)||(G.state.npcs||[]).some(hidden))c.globalAlpha*=.35;G.drawSprite(c,S[id],0,x,y,false);c.restore();}});}return list;};
})();
